### ISSUE TITLE
Feature request: add option to switch from generateSW to injectManifest  

### ISSUE THREAD

**Issue by DavidGolodetsky** [antfu/vite-plugin-pwa#1]
I'd like to add push notifications to my app builded with Vitesse. I found out that if I want to tweak my service-worker I need to use `injectManifest ` Workbox option instead of `generateSW`. 
Would be great to add this abstraction to plugin config options.

**Comment by DavidGolodetsky** [comment]
I can give it a try, if you approve this feature

**Comment by antfu** [comment]
I am actually planned to do that. It will be great if you are interested in working on this, let's see the PR thanks!

**Comment by DavidGolodetsky** [comment]
Well, I gave it a try, but it requires more deep understanding of Rollup. I thought it could be configured on Workbox level alone. Anyway thank you for this great template!

**Comment by antfu** [comment]
Supported in #15
