### ISSUE TITLE
Can it cache scripts embedded with a <script> tag?

### ISSUE THREAD

**Issue by DeFUCC** [antfu/vite-plugin-pwa#10]
I use some old style non ES module <script> tags in the index.html and they fail to load with the default config. May be there's a simple way to fix it without digging all the Workbox docs?

**Comment by hannoeru** [comment]
**Need more describe on witch module type and is from cdn or local.**

This plugin only precaching all files in outDir which by default is `dist` folder,
so files needs to be placed in the src or public folder.

**Comment by DeFUCC** [comment]
Take I have a folder `public/js` with files I include with a `<script>` tag in the `index.html`. I couldn't make them load.

**Comment by hannoeru** [comment]
@DeFUCC can you provide a link to a repo that can reproduce the problem?

**Comment by DeFUCC** [comment]
Sorry, I was checking the plugin about a month ago with vite 1. But now with recent vite 2 this plugin work like a charm! I'm really impressed to make my app work full screen and offline so easily!
