### ISSUE TITLE
Overwrites HTML lang attribute

### ISSUE THREAD

**Issue by idleberg** [antfu/vite-plugin-pwa#131]
I'm using this plugin for a Svelte project and have noticed that it will override an existing `lang` property in my HTML template.

Without VitePWA config:

```html
<html lang="de-AT">
```

With VitePWA config:

```html
<html lang="en-US">
```

I have tried specifying the lang attribute in my web manifest as suggested by [MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest/lang), but to no avail. Also I didn't find a setting to pass to Workbox.

**Comment by userquin** [comment]
@idleberg This plugin doesn't change any html element/attr, only include the manifest and the script to register the sw.

**Comment by userquin** [comment]
@idleberg can you show the `VitePWA` configuration?

**Comment by userquin** [comment]
You must configure the `lang` attr on your html (on on your svelte layout), the `lang` on the `manifest.webmanifest` is for the manifest not for the html. You can see the html page on this svelte example: https://github.com/antfu/vite-plugin-pwa/blob/main/examples/svelte-basic/index.html

**Comment by idleberg** [comment]
As mentioned in my initial post, I did specify the lang attribute in my HTML. I added the `manifest.lang` only after noticing that it's being overwritten. When I remove the VitePWA block from my config, the manifest stays as defined in the HTML.

**Comment by userquin** [comment]
@idleberg I'll check it, but I'm 99.9% sure that this plugin doesn't change the html lang attr. Can you test on private window? I have some browser plugins doing strange things...

**Comment by idleberg** [comment]
It appears that the Brave browser is responsible for this. So maybe it was a coincidence that it seemed right when I disabled the config. Let's close this issue and move on to another browser for development testing ;)

Thanks for you help!

**Comment by dheimoz** [comment]
@idleberg thanks for reporting that Brave is creating this inconsistencies.
