### ISSUE TITLE
Multiple manifest files for i18n

### ISSUE THREAD

**Issue by husayt** [antfu/vite-plugin-pwa#132]
I need to generate multiple manifest files, one for each language. How could that be supported?

For certain pages will be this manifest
```
<link rel="manifest" href="/en/admin-manifest.json"> 
```
and for other pages this one, for example
```
 <link rel="manifest" href="/jp/user-manifest.json">
 ```

**Comment by userquin** [comment]
https://docs.google.com/document/d/1Vwi_u7RP-HrzCz389Qp4EPKrWhanetu8ivcJmGbhwFc/edit

**Comment by husayt** [comment]
@userquin these are just proposals. For now we can have one manifest file per html file. What I intend to do to have multiple manifest files one per each language and  set in html file for each language the appropriate manifest file, like specified above. That's cleanest thing one can do with SSG.

**Comment by husayt** [comment]
İ just set manifest to false and placed files manually. That works like a charm

**Comment by userquin** [comment]
@husayt so, there is no problem when chaning the manifest? can you see it on the dev tools or when prompt for install on the brpwser (chrome for example)?

Can you share the configuration, maybe I can add it to the docs, or maybe you can make a PR for it...

**Comment by husayt** [comment]
See koran.center and koran.center/en
@userquin

**Comment by userquin** [comment]
> 
> 
> See koran.center and koran.center/en
> @userquin

FYI: You need to reload the page when chaning the lang from app, the manifest on dev tools not updated and also not updated on install button (I mean, the title and description are loaded from lang where the page load).

**Comment by husayt** [comment]
Yes, there were few rough edges(all fixed now), but that was due to some reactivity issues. Anyway all should be resolved now.

**Comment by userquin** [comment]
@husayt sorry to ping you here: I'll try to add support for i18n

![imagen](https://user-images.githubusercontent.com/6311119/211003532-121540af-adfb-495b-a84b-038477a2c68e.png)

**Comment by rafalm1** [comment]
@userquin Any update on that? Is it in progress, maybe there is recomended approach for vite-plugin-pwa with i18n?

**Comment by userquin** [comment]
@rafalm1 this is on hold, client side is too complex to be supported in frameworks (I'm also too busy)

You can generate them manually with a Vite plugin (using `generateBudle` hook) and configuring `manifest: false` in pwa plugin options. You will need to add the logic to write the corresponding link in the header when switching lang.

You can check how I included in a Vue project (Nuxt 3):
- pwa base configuration: https://github.com/elk-zone/elk/blob/main/config/pwa.ts#L14 (`VitePWANuxtOptions` is the equivalent to `VitePWAOptions`
- i18n configuration: https://github.com/elk-zone/elk/blob/main/modules/pwa/i18n.ts (also included dark and light variants)
- generating i18n web manifests: https://github.com/elk-zone/elk/blob/main/modules/pwa/index.ts#L53 (just add the code to vite plugins entry before the pwa plugin)
- serving i18n web manifests: add this another plugin if you want to test them in dev server https://github.com/elk-zone/elk/blob/main/modules/pwa/index.ts#L71
- add logic to change the webmanifest when locale changes: https://github.com/elk-zone/elk/blob/main/composables/setups.ts#L52 (also included theme variants)
