### ISSUE TITLE
docs: Worker example of Web Share Target API

### ISSUE THREAD

**Issue by oliverpool** [antfu/vite-plugin-pwa#133]
Hi,

after a bit of struggling, I finally managed to have a working PWA with Web Share Target API (so you can choose a picture in your gallery, click "share" and send them to my PWA :tada: )

It uses the (default) `generateWS` mode and the following config:
```js
        manifest: {
          //...
          share_target: {
            action: "/share",
            method: "POST",
            enctype: "multipart/form-data",
            params: {
              files: [
                {
                  name: "images",
                  accept: ["image/*"],
                },
              ],
            },
          },
        },
        workbox: {
          importScripts: ["sw-next-message.js"],
          runtimeCaching: [
            {
              handler: ({ event }) => {
                const dataPromise = event.request.formData();
                event.waitUntil(
                  (async function () {
                    // defined in sw-next-message.js
                    await nextMessage("share-ready");
                    const client = await self.clients.get(
                      event.resultingClientId
                    );

                    const formData = await dataPromise;
                    client.postMessage({
                      images: formData.getAll("images") || [],
                      uri: "/share",
                    });
                  })()
                );
                return Response.redirect("/share");
              },
              urlPattern: "/share",
              method: "POST",
            },
          ],
        }
```

Do you think that it would be worth integrating such an example in the documentation? 

If yes, where ? (Maybe a new category `Examples > Workbox > Web Share Target API`)

I can try to craft a working minimal example in vue.

**Comment by userquin** [comment]
@oliverpool But what is the flow? I mean, if you share a photo, the pwa , what will do with that photo (open share api)? Maybe you should create a minimal example repo and explain it a bit more...

**Comment by oliverpool** [comment]
My PWA is like a social network and I want to let the people share their own pictures easily.

There is this "Web Share Target API" to let the browser/smartphone know that my PWA wants to be included in the possibilities to share a picture. For this API to work, the files reception must be handled by the worker:

- a POST request is made to the worker on the specified URL of the `share_target`
- the data can be received by the worker using:
```
                const formData = await event.request.formData();
                const files = formData.getAll("images")
                // do whatever you want with the files
```
- if you want to send this files to the frontend (for the user to add a message to it for instance), you must post a message from the worker to the frontend (which requires some synchronization between them)
- once in the frontend, you can do whatever you want with the files

Before I take the time to make a working minimal example using this library, I wanted to know if this would be a good example to include in this repo (to show the worker customization possibilities allowed by your great library).

Shall I take your comment as a "yes, please show us a working example, just make a PR with an example under `vite-plugin-pwa/examples/vue-web-share-target`"? :angel:

**Comment by userquin** [comment]
@oliverpool closing this since there are a few resources from `Google` and `Microsoft` about pwa stuff, including your example:
- https://web.dev/progressive-web-apps/
- https://microsoft.github.io/win-student-devs/#/30DaysOfPWA/kickoff
