### ISSUE TITLE
docs: add `autoUpdate` usage

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-pwa#145]
To be included, seems it is not clear on docs how to use it and where/how to make the call to the virtual module (using import or dynamic import):
- add `useRegisterSW` fw variants on `Prompt for update` and `Auto Update` guide entries
- add `autoUpdate` entry on each fw with an small code snippet
- add `autoUpdate` with `vue-router` hint, maybe add small code snippet and add how to use it with SSR/SSG, with reference to `vitesse` template maybe will be sufficient

/cc @unpseudocomplique

**Comment by userquin** [comment]
add also a link to this guide (not yet finished): https://web.dev/learn/pwa/

**Comment by userquin** [comment]
@unpseudocomplique @johannschopplich can you take a look at this https://deploy-preview-153--vite-plugin-pwa.netlify.app/guide/faq.html#navigator-window-is-undefined?

**Comment by johannschopplich** [comment]
@userquin Great update! I like it a lot, especially the explanation of the `<ClientOnly>` component at the end.

The only complaint I have is the wording of the intro section – maybe you could use a list instead of the multiple `when`s?

**Comment by userquin** [comment]
> 
> 
> @userquin Great update! I like it a lot, especially the explanation of the `<ClientOnly>` component at the end.
> 
> The only complaint I have is the wording of the intro section – maybe you could use a list instead of the multiple `when`s?

after 3000 lines of code, tmr I'll take a look, and thanks for the review

**Comment by userquin** [comment]
https://github.com/antfu/vite-plugin-pwa/pull/153#issuecomment-968159191

**Comment by johannschopplich** [comment]
@userquin Not that important compared to your terrific work. 🙂

**Comment by userquin** [comment]
@johannschopplich can you take a look again to the FAQ entry? wait to prompt for update, and then reload and review it: or just go to the PR and see it here: https://github.com/antfu/vite-plugin-pwa/blob/c0b6b5552d06e437def31ea328aa6afd189dcd23/docs/guide/faq.md
