### ISSUE TITLE
Subpar documentation and guidline

### ISSUE THREAD

**Issue by Moerning** [antfu/vite-plugin-pwa#148]
The documentation and examples, provided for this plugin lacks the much needed sophistication and care.
I mean look here for example:
https://github.com/antfu/vite-plugin-pwa/blob/main/examples/vue-basic-inject-manifest/vite.config.ts
This is a vue js example to demonstrate the inject manifest strategy and yet when you look at it you see that the inject manifest option in vite.config.ts is not even used and the whole thing is handled in app.vue which is a sacred file for most vue developers and minimum coding is what you want in that file.
There is no Api definition page only a lazy types.ts file and everything seems to be based on the assumption that the developer already knows what to do with the plugin

**Comment by userquin** [comment]
@Moerning you can read the docs entry here https://vite-plugin-pwa.netlify.app/frameworks/vue.html and the exampe docs here https://vite-plugin-pwa.netlify.app/examples/vue.html

The logic is not on the `App.vue` component, it is on `ReloadPrompt.vue` component.

The api definition can be found here https://github.com/antfu/vite-plugin-pwa/blob/main/client.d.ts#L13  (`vite-plugin-pwa/client`)

**Comment by userquin** [comment]
@Moerning next version of docs will include the type declarations for each framework, for exmaple for vue3 you can see it here: https://github.com/antfu/vite-plugin-pwa/pull/153/commits/5c511bfc593bddd7abdc3d9ce0f5134f3717f7de#diff-9075b210cd8e92ede71398f203f0e70790b5d5e3f85a294b560b3cd1839a3c67R12

**Comment by Moerning** [comment]
Ok My Bad,
now that i got the hang of it,
It's actually working pretty good,
The docs helped too.
Apologies
