### ISSUE TITLE
not working while using preact

### ISSUE THREAD

**Issue by WhoAdarshPandya** [antfu/vite-plugin-pwa#151]
hey @antfu , awesome library for vite, I'm making an interesting project using vite + preact though plugin works fine with react, it's not working with preact. can we expect something in future? Thanks

**Comment by userquin** [comment]
@WhoAdarshPandya we'll add support for `preact` when we have time to do if (PR are welcome), in the mean time you can use vanilla javascript virtual module to add preact reactivity system using https://github.com/antfu/vite-plugin-pwa/blob/main/src/client/build/react.ts as a guide.

**Comment by userquin** [comment]
@WhoAdarshPandya add repo where we can check what's failing using this plugin with `preact`
