### ISSUE TITLE
The images in /dist/assets are not cached

### ISSUE THREAD

**Issue by akirarika** [antfu/vite-plugin-pwa#155]
I changed the SVG image in the demo to PNG, and then placed it in `/src/assets`. This image will not be displayed offline

I tried to write `['*.png']` in `includeAssets`, it didn't seem to work

I uploaded the demo code [here](https://github.com/akirarika/vite-plugin-pwa-demo)

**Comment by userquin** [comment]
@akirarika it is a `fast-glob` pattern, you should use `['assets/*.png']`: see this entry from docs https://vite-plugin-pwa.netlify.app/guide/static-assets.html#static-assets-handling

If you want to add `svg` and `png` files, just combine into one `['assets/*.{png|svg}']` or include both `['assets/*.png', 'assets/*.svg']`.

You can see also `fast-glob` docs: https://www.npmjs.com/package/fast-glob

**Comment by userquin** [comment]
@akirarika if you change your resources from directories (public to assets), you should read the `publicDir` entry on vite docs

**Comment by akirarika** [comment]
@userquin thank you!

add these in `VitePWA` options in `vite.config.js`, it works for me:

```js
workbox: {
  globPatterns: [
    // all packaged resources are stored here
    "assets/*",
    // add HTML and other resources for the root directory
    "*.{svg,png,jpg}",
    "*.html",
    "manifest.webmanifest",
    // be careful, not to add sw.js
  ],
},
```

although this solves the problem, I don't know if it's right, I've tried to writing `includeAssets: ["assets/*"]` or `['assets/*.png']` is invalid.

thank you again! @userquin

**Comment by userquin** [comment]
@akirarika both are equivalent, the main diference is that with your solution, you sould take care including all assets. `includeAssets` will add the result on `[workbox/injectManifest].additionalManifestEntries` instead manipulating `[workbox/injectManifest].globPatterns`: https://github.com/antfu/vite-plugin-pwa/blob/main/src/assets.ts#L32, https://github.com/antfu/vite-plugin-pwa/blob/main/src/assets.ts#L58 and https://github.com/antfu/vite-plugin-pwa/blob/main/src/assets.ts#L101

**Comment by mykwillis** [comment]
I have the same question as @akirarika and I don't see how the above comment from @userquin resolves it.

I started with the Vue starter app:

    npm create vite@latest vite-vue-pwa

I then added the vite-plugin-pwa in `vite.configt.ts` and added the `registerSW` call to my main.ts. I verified I have a working service worker - great!

I noticed from the developer console that the Vue logo used in the sample app (/src/assets/logo.png) was not being pre-cached, so I thought this would be an easy way to test `includeAssets` (i.e., to add the logo to the pre-cached files). But no matter what I specified in the `includeAssets` array, I couldn't get this file to be cached: 

```
export default defineConfig({
  plugins: [
    vue(),
    VitePWA({
      includeAssets: ["assets/*"],
    }),
  ],
});
```

![image](https://user-images.githubusercontent.com/976776/156937907-17eecf08-3ba7-4a5d-9917-9f21d278537f.png)

After playing around with lots of variants for what to put in `includeAssets`, I tried specifying workbox globPatterns directly:

```
export default defineConfig({
  plugins: [
    vue(),
    VitePWA({
      workbox: {
        globPatterns: ["assets/*"],
      },
    }),
  ],
});
```

and with this configuration, the logo was being cached by the service worker:

![image](https://user-images.githubusercontent.com/976776/156937985-8be14b13-488e-4aec-bacb-1c081b033d2f.png)


I haven't changed any other configurations from the defaults that were spit out by `npm create vite@latest vite-vue-pwa`, so why does the vite-plugin-pwa `includeAssets` not seem to work?

**Comment by userquin** [comment]
@mykwillis read this entry form docs (check the warning section): https://vite-plugin-pwa.netlify.app/guide/static-assets.html

**Comment by mykwillis** [comment]
Thanks for the pointer @userquin. I've read that section several times while trying to get this to work and I still can't see how it helps.

To be clear, the only reason I touched `workbox.globPatterns` is to troubleshoot why I couldn't get `includeAssets` to work. Point taken that using "assets/*" as the value of `workbox.globPatterns` will break things (because it tries to pre-cache the service worker?), but I did that in the example above just to show that adjusting `workbox.globPatterns` did, in fact, work to pre-cache the .png, while setting `includeAssets` did not.

I think my entire question boils down to "why doesn't `includeAssets` work?" I'm no expert on Vite, but I'm just using an out-of-the-box Vue3 template, and that .png asset is placed in my public assets folder as part of the build, so why doesn't it get picked up and pre-cached when I add it to `includeAssets`?

Incidentally, I found the wording of that warning very confusing, because it seems to be mixing two use cases.  Perhaps instead of:

> If you configure globPatterns on workbox or injectManifest plugin option, you MUST include all your assets patterns: globPatterns will be used by workbox-build to match files on dist folder. By default, globPatterns will be **.{js,css,html}: workbox will use [glob primer](https://github.com/isaacs/node-glob#glob-primer)

It might be better to say something like:

> By default, workbox will use a [glob](https://github.com/isaacs/node-glob#glob-primer) pattern like "**.{js,css,html}" to match assets to include in the service worker's precache. If you specify `workbox.globPatterns` in your configuration, you are replacing (not adding to) this default. Typically, you'll want to add an entry like "**.{js,css,html}" whenever specifying custom patterns for `workbox.globPatterns` to be sure the default assets continue to be pre-cached.

(I'm not sure why "injectManifest" is mentioned in the original note at all; as far as I can tell, the default glob of "**.{js,css,html}" is used as expected when no setting is provided by the user, so simply using "injectManifest" does not force you to manually specify asset patterns).

**Comment by mykwillis** [comment]
Regarding the warning message, I see now my confusion.

This note:

> If you configure globPatterns on workbox or injectManifest plugin option, you MUST include all your assets patterns: globPatterns will be used by workbox-build to match files on dist folder. By default, globPatterns will be **.{js,css,html}: workbox will use [glob primer](https://github.com/isaacs/node-glob#glob-primer)

Might be more clear if it said:

> If you provide a value for either `workbox.globPatterns` (when using generateSW strategy) or for `injectManifest.globPatterns` (when using injectManifest strategy), you MUST include all of...

Sorry for my confusion on that.

**Comment by Polm90** [comment]
I'm using the plugin versione 0.14.1

But I do not understand how to tell the sw to pre-fetch all assets included in the 'src/assets' folder.

I've tried configuring the workbox plugin like this:
```
workbox: {
				globPatterns: ['**/*.{js,css,html,json,ico,svg,ttf,webmanifest}'],
			}
```

and using the includeAssets options like this
`includeAssets: ['favicon.ico', 'apple-icon-180.png', 'masked-icon.svg', '**/*.{js,css,html,json,ico,svg,ttf,webmanifest}']`

but none of them has worked. I always get the message in console: "<workbox> Precaching 2 files." (which are the sw file and the index.html file)

What am I doing wrong?
