### ISSUE TITLE
No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest.

### ISSUE THREAD

**Issue by Whirl21** [antfu/vite-plugin-pwa#156]
Hey there i am facing this issue -
No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest.
My plugin is setup correctly 
- my vite.config.ts file -
 ```typescript
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      includeAssets: [
        "favicon.svg",
        "favicon.ico",
        "robots.txt",
        "apple-touch-icon.png",
      ],
      registerType: "autoUpdate",
      manifest: {
        name: "IMG To PDF",
        short_name: "iTp",
        icons: [
          {
            src: "/android-chrome-192x192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "/android-chrome-512x512.png",
            sizes: "512x512",
            type: "image/png",
          },
          {
            src: "/android-chrome-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any maskable",
          },
        ],
        theme_color: "#2a2e38",
        background_color: "#2a2e38",
        display: "standalone",
        start_url: "/",
        lang: "en-US",
        orientation: "portrait-primary",
      },
    }),
  ],
}); 
```

**Comment by Whirl21** [comment]
all the icons and assets are present in my public folder ( im testing over https aswell )

**Comment by vijayRT** [comment]
I'm facing this issue as well.

* OS: Ubuntu 20.04 LTS
* Node.js: v16.13.0
* PNPM: v6.22.2
* Vite: v2.6.4
* vite-plugin-pwa: v0.11.5

Repo for repro: https://github.com/vijayRT/rummy-scoreboard 

Using the default plugin config provided in the docs at https://vite-plugin-pwa.netlify.app/guide/generate.html

When the build command is run it also generates `registerSW.js` and `sw.js`

![image](https://user-images.githubusercontent.com/11785068/141928809-1b9687f9-9e31-42d6-a452-d5accdc83845.png)

**Comment by Whirl21** [comment]
same it generates the files for me aswell

**Comment by userquin** [comment]
@Whirl21 @vijayRT you need to import the virtual module and call it to register the service worker: https://vite-plugin-pwa.netlify.app/frameworks/#usage

@vijayRT since you're using `autoUpdate` strategy just add this to your `main.ts`:
```ts
import { registerSW } from 'virtual:pwa-register'
...
registerSW({ immediate: true })
```

You can see the `examples/vue-*` directories on this repo. Instead using vanilla version of the virtual module, they're using the vue 3 variant `import { useRegisterSW } from 'virtual:pwa-register/vue'` on `ReloadPrompt.vue` component, that's included on `App.vue`.

**Comment by userquin** [comment]
Yu should read this https://vite-plugin-pwa.netlify.app/guide/auto-update.html, the guide has a configuration and a runtime sections.

The confifugration is used to configure the behavior, the runtime to install and interact with the service worker.

**Comment by Whirl21** [comment]
ic
thanks i will take a look

**Comment by Whirl21** [comment]
hey @userquin i tried doing that and updated my main.tsx to look like this , however im still facing the same issue
```tsx
import React from "react";
import ReactDOM from "react-dom";
import "./css/Index.css";
import Core from "./Core";
//@ts-ignore:next-line
import swal from "sweetalert2/dist/sweetalert2.all.min.js";
const Toast = swal.mixin({
  toast: true,
  position: "bottom-right",
  showConfirmButton: true,
  showCancelButton: true,
  confirmButtonText: "Refresh",
  cancelButtonText: "No Thanks",
  timer: 10000,
  timerProgressBar: true,
  didOpen: (toast: any) => {
    toast.addEventListener("mouseenter", swal.stopTimer);
    toast.addEventListener("mouseleave", swal.resumeTimer);
  },
});
const Toast2 = swal.mixin({
  toast: true,
  position: "bottom-right",
  showConfirmButton: true,
  showCancelButton: false,
  confirmButtonText: "Refresh",
  timer: 10000,
  timerProgressBar: true,
  didOpen: (toast: any) => {
    toast.addEventListener("mouseenter", swal.stopTimer);
    toast.addEventListener("mouseleave", swal.resumeTimer);
  },
});
//@ts-ignore:next-line
import { registerSW } from "virtual:pwa-register";
const updateSW = registerSW({
  onNeedRefresh() {
    Toast.fire({
      icon: "info",
      title: "New Content Available",
    }).then((result: any) => {
      if (result.isConfirmed) {
        updateSW();
      }
    });
  },
  onOfflineReady() {
    Toast2.fire({
      icon: "info",
      title: "App is Ready To Work Offline",
    });
  },
});
ReactDOM.render(
  <React.StrictMode>
    <Core />
  </React.StrictMode>,
  document.getElementById("application")
);
```

**Comment by Whirl21** [comment]
ok well i took another look at the examples seems im doing something wrong

**Comment by userquin** [comment]
@Whirl21 you can check the `react` examples.

**Comment by Whirl21** [comment]
i actually made it work with the vanilla example 😄.
thank you for the help

**Comment by Whirl21** [comment]
**To Anyone Having the same issue** -
you might not have followed the steps in guide page 3 & 4 like me and just thought you don't need those, while you actually do!

**Comment by danykina** [comment]
@Whirl21 How did you solve? Thanks

**Comment by ayandebnath** [comment]
If you have any **AdBlock** extension installed, then **disable** it.
