### ISSUE TITLE
network-first strategy?

### ISSUE THREAD

**Issue by FezVrasta** [antfu/vite-plugin-pwa#157]
Hi, is it possible to use this plugin to setup a network-first strategy service worker?

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/141996770-b97cd23e-640d-4f56-8cec-8dd3a21693f2.png)

**Comment by FezVrasta** [comment]
Why isn't it part of the docs? Looking into a closed PR doesn't seem intuitive.

**Comment by userquin** [comment]
You can do whatever you want with a custom service worker, we can't cover all use cases, go to the workbox documentation, how to implement the service worker with your requirements is something you should investigate yourself.

**Comment by userquin** [comment]
> 
> 
> Why isn't it part of the docs? Looking into a closed PR doesn't seem intuitive.

You have the branch on my repo
