### ISSUE TITLE
[Question] sw.js injected inline

### ISSUE THREAD

**Issue by domsen123** [antfu/vite-plugin-pwa#16]
Hi,
im running VitePWA with ViteSSG.
The build process is injecting the sw.js into index.html as inline script..

Can I move this into a separate file?
Don't want to inject this as inline script cause of my Content Security Policy.

**Comment by antfu** [comment]
Not sure how would that affect PWA registration, but if everything works the same, I am happy to have an option to config whether to inject as an inline script or a separate file. Would you mind to give it a shot and draft a PR? Thanks.

**Comment by domsen123** [comment]
#17

**Comment by antfu** [comment]
Released in 0.3.9 as `inlineRegister: false`
