### ISSUE TITLE
self.registration is undefined

### ISSUE THREAD

**Issue by SebT** [antfu/vite-plugin-pwa#162]
Greetings. When I try to run `self.registration.showNotification` inside my service worker, it throws an error because `self.registration` is undefined.

I tried with both "injectManifest" & "generateSW" strategies. I managed to show notifications on chrome desktop with `new Notification`, but on mobile it throws an error and tells me to use `ServiceWorkerRegistration.pushNotification`. I see self.registration used a lot in service workers examples/doc so I'm kind of lost here. I found a navigator.serviceWorker.getRegistration

Any idea on how to access service registration please?

Code sample: 
```js
// notifications-worker.js
self.onmessage = (e) => {
  console.log('self.registration', self.registration) // <- this is undefined, why??
  self.registration.showNotification(e.data.title)
  // new Notification(e.data.title) works on Chrome, but not on android (app installed from manifest)
}

// main.js (app entry point)
import NotificationsWorker from './notifications-woker?worker'

const worker = new NotificationsWorker()
worker.postMessage({ title: 'test notif' }) // <- correctly runs the code above.

// I do have code to manage requestPermission to show notifications elsewhere
```

And when I try to debug the worker is chrome devTools (with vite dev service), I don't see the worker nor the manifest. But in production I see the manifest correctly, not the worker. Is this normal?

I may confuse things, I'm not familiar with service workers. Thanks in advance for your help.

**Comment by userquin** [comment]
@SebT https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications

I need to rewrite the docs.
