### ISSUE TITLE
Workbox appears to be needlessly generating revision hashes

### ISSUE THREAD

**Issue by arackaf** [antfu/vite-plugin-pwa#163]
I'm in the process of writing a blog post about the Vite-pwa plugin (it's amazing and thanks for your wonderful work).

Jeff Posnick (works on Workbox for Google) was reviewing it, and he called this minor point out, which relates to how this plugin works. Just as an fyi I thought I'd pass it along. 

![image](https://user-images.githubusercontent.com/11261266/143059203-24c37be8-83d3-4268-9515-8750696c5a06.png)

**Comment by userquin** [comment]
Since you can access to the `workbox` or `injectManifest` configuration, you can configure `dontCacheURLMatching` on the pwa plugin configuration, when I have time I'll add the suggestion from `Jeff Posnick` as the default.

**Comment by userquin** [comment]
/cc @antfu the changes are minimal, I'll add the default value `/\.[a-f0-9]{8}\./` on `options` module for both strategies.

@arackaf here the results running `exmaples/vue-router` twice:

![imagen](https://user-images.githubusercontent.com/6311119/143076153-5368148e-4d90-48a5-ac20-bc0af279d2d7.png)

![imagen](https://user-images.githubusercontent.com/6311119/143076385-27c418c8-cbba-4ddc-b40a-7f5c72239bdf.png)

**Comment by arackaf** [comment]
@userquin looks great! And yeah I know about the workbox config option - like I said, I was just passing along the suggestion from Jeff about changing the defaults.

Thanks a ton for looking, and thanks for the plugin. It works wonderfully!

**Comment by userquin** [comment]
@arackaf I'm adding `local-pkg` to make it working on `esm` avoiding using `__dirname`. do you know if `workbox` works on `esm` environment?

**Comment by arackaf** [comment]
I don't think Service Workers currently support esm, but Jeff Posnick would know more - I'll ping him.

**Comment by jeffposnick** [comment]
In some browsers (Safari and Chrome; not Firefox) the service worker runtime supports ES modules: https://web.dev/es-modules-in-sw/

But it's honestly a mess to feature detect, and you effectively need to generate multiple flavors of service worker, and potentially multiple flavors of registration code. Additionally, while Workbox is authored using ES modules, we don't publish ready-to-use built libraries to `npm` in ES module format at the moment (see https://github.com/GoogleChrome/workbox/issues/2797).

So, I would not attempt to use ES modules in this context today.

**Comment by userquin** [comment]
@jeffposnick the problem is when generating the client module on build time.

You can see we use `__dirname` on `src/modules.ts` (https://github.com/antfu/vite-plugin-pwa/blob/main/src/modules.ts#L13), and so on `esm` environment the plugin will fail.

This plugin will load the `src/client/build/xxx.mjs` to replace `base` and `scope`, so the client is not the problem.

So, running `workbox-build`, `generateSW` or `injectManifest` will work on `esm` environment?.

**Comment by userquin** [comment]
For example, we have a similar problem on another plugin, see the changes: https://github.com/antfu/unplugin-auto-import/pull/80/files#diff-cda0303e4203d40c6d10808af40ddbea15cb676da0dd85c57f78f035bc1f26c4L11

The change I'll make here is the same, changing the name to resolve `vite-plugin-pwa/client/${mode}/${source}.mjs` file on https://github.com/antfu/vite-plugin-pwa/blob/main/src/modules.ts#L13.

**Comment by arackaf** [comment]
@userquin am I understanding you right that this is only a problem at build time, if someone were to try to run the Vite-pwa plugin in the native Node esm environment?

**Comment by userquin** [comment]
@arackaf yes, I think I don't need to change it, since it is only at build time, sorry for the noise...

**Comment by arackaf** [comment]
@userquin No worries at all. Node esm has been such a mess - sorry it's causing you problems here. Ultimately I wouldn't sweat it though. This plugin is fantastic!

**Comment by userquin** [comment]
@arackaf I use this plugin on an `sveltekit` project with static adapter (esm: type module) here https://github.com/userquin/sveltesociety.dev and it is working...

**Comment by userquin** [comment]
@arackaf @jeffposnick you have it on new release `0.11.7`
