### ISSUE TITLE
react: `onRegistered` is called a lot

### ISSUE THREAD

**Issue by wavebeem** [antfu/vite-plugin-pwa#171]
I'm using `useRegisterSW` from `virtual:pwa-register/react` and the `onRegistered` callback is called more than once on a given page load.

I would expect this would only be called once per page load. I looked at the `useRegisterSW` hook and it appears to register the SW outside of a `useEffect`. It seems like this should be inside a `useEffect(fn, [])` call so it only gets called on component mount, not every render.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/176815/143718805-afd0afc9-41cf-449b-9b97-632317ed895e.png">

Generally it appears 3x when I'm loading my page, but I've had it sometimes appear a 4th time. I'm using `onRegistered` to start an interval to check for SW updates, and I don't want 4 intervals running at once.

**Comment by userquin** [comment]
@wavebeem can you try using `virtual:pwa-register` and wrap it with your ui logic?

PR welcome.

**Comment by wavebeem** [comment]
Thanks @userquin, I'll see what I can do!

**Comment by userquin** [comment]
you should use ReloadPrompt component without side effects (maybe memo or something similar reat provide), the dialog/prompt will be shown only once

**Comment by userquin** [comment]
@wavebeem in the `react-router` example it is called twice, the second time seem to be once the `ready to work offline` is shown.
On `vue-router` example is called only once since vue works complety different.
On `preact-router` the same result as `react-router`, called twice.
On `svelte-routify `the same result as `vue-router`, called only once.
On `solid-router` the same result as `vue-router`, called only once.

We need to figure out how to exclude the `useRegisterSW`  to be called multiple times, the caller is the problem, not this plugin.

**Comment by wavebeem** [comment]
OK, I think this code will fix the problem. I tested it on my own site and it seems to work correctly.

The main difference is `useState` with an initializer function so that `registerSW` is only called once, and then we store the update function.

```ts
export function useRegisterSW(options: RegisterSWOptions = {}) {
  const needRefresh = useState(false);
  const offlineReady = useState(false);
  const [updateServiceWorker] = useState(() => {
    const {
      immediate = true,
      onNeedRefresh,
      onOfflineReady,
      onRegistered,
      onRegisterError,
    } = options;
    return registerSW({
      immediate,
      onOfflineReady() {
        offlineReady[1](true);
        onOfflineReady?.();
      },
      onNeedRefresh() {
        needRefresh[1](true);
        onNeedRefresh?.();
      },
      onRegistered,
      onRegisterError,
    });
  });
  return {
    needRefresh,
    offlineReady,
    updateServiceWorker,
  };
}
```

**Comment by userquin** [comment]
@wavebeem it seems your suggestion fix both, react and preact, I will keep the options outside the `useState` for `updateServiceWorker`. On the pwa examples it works in both, only one registration log, can you test it?:

```ts
// src/client/build/react.ts
import { useState } from 'react'
import { RegisterSWOptions } from '../type'
import { registerSW } from './register'

export type { RegisterSWOptions }

export function useRegisterSW(options: RegisterSWOptions = {}) {
  const {
    immediate = true,
    onNeedRefresh,
    onOfflineReady,
    onRegistered,
    onRegisterError,
  } = options

  const [needRefresh, setNeedRefresh] = useState(false)
  const [offlineReady, setOfflineReady] = useState(false)

  const [updateServiceWorker] = useState(() => {
    return registerSW({
      immediate,
      onOfflineReady() {
        setOfflineReady(true)
        onOfflineReady?.()
      },
      onNeedRefresh() {
        setNeedRefresh(true)
        onNeedRefresh?.()
      },
      onRegistered,
      onRegisterError,
    })
  })

  return {
    needRefresh: [needRefresh, setNeedRefresh],
    offlineReady: [offlineReady, setOfflineReady],
    updateServiceWorker,
  }
}
```

**Comment by userquin** [comment]
@wavebeem try update and test with new release `0.11.8`

**Comment by wavebeem** [comment]
Thanks! It's working well! 😄
