### ISSUE TITLE
`offlineReady` is never true

### ISSUE THREAD

**Issue by wavebeem** [antfu/vite-plugin-pwa#172]
It seems `offlineReady` is never true. I'm using the `useRegisterSW` plugin and only have 3 files in my `includeAssets`.

On page load, the Network panel shows that all 3 files have been loaded via SW, but `offlineReady` is never true (https://deploy-preview-118--pkmn-help.netlify.app/offense/)

The code is in this branch: https://github.com/wavebeem/pkmn.help/pull/118/files

This is my `VitePWA` configuration:

```js
VitePWA({
  mode: env.mode !== "development" ? "production" : "development",
  includeAssets: ["data-pkmn.json", "svg/*.svg"],
  manifest: {
    name: "Pokémon Type Calculator",
    short_name: "pkmn.help",
    description:
      "A Pokémon type calculator to show strengths/weaknesses of different type combinations",
    theme_color: "#ffffff",
    icons: [
      {
        src: "favicon-192x192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "favicon-512x512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "favicon-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any maskable",
      },
    ],
  },
});
```

**Comment by userquin** [comment]
@wavebeem this can be a side effect from workbox (from #171 ), since the sw is registered multiple times, the logic on the workbox window module will handle as external update and will notify as ready to work offline.

**Comment by wavebeem** [comment]
Oh, I think I saw something about this in the docs. I'll see if working on #171 fixes this. Thanks!

**Comment by userquin** [comment]
yeah, when running the examples and you forget to go online testing offline mode

**Comment by wavebeem** [comment]
Yeah, I just used `virtual:pwa-register` directly and I got the "offline ready" status as soon as I cleared the SW and registered a new one. I'll close this and re-open only if #171 doesn't fix this. Thanks!
