### ISSUE TITLE
Make crossorigin attribute for link[rel="manifest"] configurable

### ISSUE THREAD

**Issue by jonaskuske** [antfu/vite-plugin-pwa#178]
When a site sits behind authentication, you need to use

```html
<link rel="manifest" href="/..." crossorigin="use-credentials" />
```

so that the browser sends credentials along with the request and thus receives the manifest instead of a 401.

**Comment by userquin** [comment]
@jonaskuske this makes sense? I mean, that resource should be public, also all icons for the manifest. If you secure your application you should be logged-in before access it.

You can configure `manifest: false` on the pwa plugin configuration and then do the registration yourself, but you'll need to create also the `manifest` yourself.

**Comment by jonaskuske** [comment]
@userquin 

> If you secure your application you should be logged-in before access it.

Yeah, but that's the point – *even if you logged in*, the browser won't send the credentials along with the request for the manifest, so while the application itself loads, the manifest doesn't and the app isn't installable.

From web.dev:

![Screenshot_20211129-150653.png](https://user-images.githubusercontent.com/30421456/143882416-8483fadc-54cc-4650-b005-3a7a80391c04.png)

(https://web.dev/add-manifest/#link-manifest)

Happy to submit a PR :)

**Comment by userquin** [comment]
@jonaskuske are you working on the PR or do you prefer me to include it?

**Comment by userquin** [comment]
If you're working on it, add also an entry here on the pwa docs: https://github.com/antfu/vite-plugin-pwa/blob/main/docs/guide/faq.md

Add it as the after `## IDE errors 'Cannot find module' (ts2307)` and before `## Service Worker Registration Errors` with its own section (mention also the 401 status code), for example:
```md
## Web app manifest and 401 status code (Unauthorized)

Hint the user how to enable it using the new configuration option

```

**Comment by jonaskuske** [comment]
Working on it, and alright, will do 👍🏻

**Comment by userquin** [comment]
@jonaskuske you don't need to test it, just check the build script works, I'll review it tmr or maybe `@antfu`: `pnpm run build`. Don't forget to run before `pnpm install` to install the dependencies.

If you want to test it use `pnpm run examples` after run the build script, then select `vue + generateSW + prompt + no for cheks` on the `cli`, then open `https://localhost`  and check the manifest entry has the `crossorigin` header on the html page.
