### ISSUE TITLE
AutoUpdate problems with lazy loaded esm modules

### ISSUE THREAD

**Issue by samuel-git** [antfu/vite-plugin-pwa#180]
Thanks for the amazing plugin!

When using Vue3 + TS + Vite + autoUpdate with lazy loaded routes, the clients sometimes try to request a .js file with outdated hash for the new route when navigating on the site after an update (e.g. old Home.8769440d.js instead of the new Home.e58cddfc.js). This throws an error (see below for details) and nothing happens navigation wise. A manual reload / revisiting of the site and everything is okay again.
Most of the time the clients detect the new service worker and reload as intended.

Error: Loading module was blocked because of a disallowed MIME type (“text/html”)
The old hash does not exists and the 404.html page served instead is not a esModule.

One solution might be to keep the old hashed files on deployment but this seems not right.

**Comment by userquin** [comment]
@samuel-git check issue #177 again, you will have there some hints, also check PR #181

**Comment by samuel-git** [comment]
Thanks, I need some time to test properly but I think it was the short caching time for js files.

I use the netlify config from your awesome vitesse template now und will report back if this did not help.

**Comment by samuel-git** [comment]
Just a short heads up for everyone encountering this: Migrating from a DIY i18n plugin to the official one for Vue 3 along with the changes suggested by @userquin fixed the issue for me.
