### ISSUE TITLE
ReloadPrompt example not functional

### ISSUE THREAD

**Issue by hafidk** [antfu/vite-plugin-pwa#183]
Hi there! 

I've been going through the docs and got the pwa in react working, even if the sw it's pretty barebones it installs and activates as inteded, the issue I have is following the ReloadPrompt.tsx example within the [docs](https://vite-plugin-pwa.netlify.app/frameworks/react.html#prompt-for-update) . I tried to add a button to skipWaiting once the user chooses to install the new version but the current example does nothing of the sort.

I am having issues with this specifically:

```
 const {
    offlineReady: [offlineReady, setOfflineReady],
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegistered(r) {
        // eslint-disable-next-line prefer-template
        console.log('SW Registered: ' + r)
    },
    onRegisterError(error) {
        console.log('SW registration error', error)
    },
  })

  const close = () => {
    setOfflineReady(false)
    setNeedRefresh(false)
  }

```
For starters, the function updateServiceWorker appears to be an empty promise, even if we call it nothing happens, secondly, the close function whenever we call it, it sets the value of need refresh to false but immediately logs that the SW got registered again and shows the prompt, I tried to encapsulate that within a useEffect so it would only run once but to no avail.

It detects corerctly when it needs to refresh whenever detects a new version, but reloading or using the updateServiceWorker function don't seem to do the trick.

Thanks!

**Comment by userquin** [comment]
you should call `updateServiceWorker` only when `needRefresh` is activated, otherwise the call does nothing.

**Comment by hafidk** [comment]
Hey, thanks for the quick response.

But this is precisely what the example does (I ommited some code but it's verbatim the same as the example).

`{ needRefresh && <button className="ReloadPrompt-toast-button" onClick={() => updateServiceWorker(true)}>Reload</button> }`

When we `needRefresh`, the button appears correctly, I already tested that and the SW detects the new changes and is waiting for a reload, but then calling `updateServiceWorker` right here does nothing.

**Comment by userquin** [comment]
Check if you have some warning/error on the console about the service worker.

You can clone this repo and run `pnpm install && pnpm run build`, then `pnpm run examples` and select `react + generateSW + prompt + no check for updates` and open `https://localhost`, check that `App ready to work offline is shown`, then stop the server and rerun `pnpm run example`, select again the same options on the `cli` and once started F5 on the page again to check if working.

**Comment by userquin** [comment]
maybe it is related to #171: uninstall `vite-plugin-pwa` and install it again, you should use `0.11.8` version, we have fix some `side effects`.

**Comment by hafidk** [comment]
Updating to `0.11.8` did the trick, thanks!
