### ISSUE TITLE
Issue deploying to Netlify

### ISSUE THREAD

**Issue by doutatsu** [antfu/vite-plugin-pwa#186]
I am trying to get a basic configuration going, but when I try to deploy to Netlify, it fails during the vite build:

```
7:39:24 PM: $ yarn build
7:39:24 PM: yarn run v1.13.0
7:39:24 PM: $ vite build
7:39:25 PM: failed to load config from /opt/build/repo/vite.config.js
7:39:25 PM: error during build:
7:39:25 PM: Error: You gave us a visitor for the node type StaticBlock but it's not a valid type
    at verify (/opt/build/repo/node_modules/@babel/traverse/lib/visitors.js:114:13)
7:39:25 PM:     at explode (/opt/build/repo/node_modules/@babel/traverse/lib/visitors.js:36:3)
7:39:25 PM:     at Object.merge (/opt/build/repo/node_modules/@babel/traverse/lib/visitors.js:149:5)
7:39:25 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/@babel/helper-replace-supers/lib/index.js:68:44)
7:39:25 PM:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
7:39:25 PM:     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
7:39:25 PM:     at Object.require.extensions.<computed> [as .js] (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:68716:13)
7:39:25 PM:     at Module.load (node:internal/modules/cjs/loader:981:32)
7:39:25 PM:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
7:39:25 PM:     at Module.require (node:internal/modules/cjs/loader:1005:19)
7:39:26 PM: error Command failed with exit code 1.
```

I only use babel for my tests, so they shouldn't affect anything, but even removing the configuration still results in this error, so I am not even sure it's that at fault. Here the rest of my code:

### Reload Prompt
```js
<script setup>
  import { useRegisterSW } from 'virtual:pwa-register/vue';

  const {
    offlineReady,
    needRefresh,
    updateServiceWorker,
  } = useRegisterSW();

  const close = async () => {
    offlineReady.value = false;
    needRefresh.value = false;
  };
</script>

<template>
  <div
    v-if="offlineReady || needRefresh"
    class="pwa-toast"
    role="alert"
  >
    <div class="message">
      <span v-if="offlineReady">
        App ready to work offline
      </span>
      <span v-else>
        New content available, click on reload button to update.
      </span>
    </div>
    <button
      v-if="needRefresh"
      @click="updateServiceWorker()"
    >
      Reload
    </button>
    <button @click="close">
      Close
    </button>
  </div>
</template>

<style>
.pwa-toast {
  position: fixed;
  right: 0;
  bottom: 0;
  margin: 16px;
  padding: 12px;
  border: 1px solid #8885;
  border-radius: 4px;
  z-index: 1;
  text-align: left;
  box-shadow: 3px 4px 5px 0px #8885;
}
.pwa-toast .message {
  margin-bottom: 8px;
}
.pwa-toast button {
  border: 1px solid #8885;
  outline: none;
  margin-right: 5px;
  border-radius: 2px;
  padding: 3px 10px;
}
</style>
```

## Vite Config
```js
import path from 'path';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueI18n from '@intlify/vite-plugin-vue-i18n';
import { VitePWA } from 'vite-plugin-pwa';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueI18n({
      include: path.resolve(__dirname, './src/locales/**'),
    }),
    VitePWA({
      includeAssets: ['favicon.ico', 'robots.txt', 'apple-icon-180.png'],
      manifest: {
        short_name: 'Short Name',
        name: 'Name',
        icons: [
          {
            src: 'manifest-icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable any',
          },
          {
            src: 'manifest-icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable any',
          },
        ],
        start_url: '/dashboard',
        background_color: '#FFFFFF',
        display: 'standalone',
        scope: '/',
        theme_color: '#FFFFFF',
        description: 'Description',
      },
    }),
  ],
  server: {
    port: 8080,
  },
  build: {
    sourcemap: true,
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
```

**Comment by doutatsu** [comment]
Any idea about this @antfu? 😢

**Comment by userquin** [comment]
@doutatsu babel is there, you can try `rm -rf ./node_modules && rm yarn.lock && yarn`

**Comment by doutatsu** [comment]
I was absolutely sure that I have tried that already - but as I was trying again, it did go through without issues. My bad, that was a dumb mistake
![image](https://user-images.githubusercontent.com/4270980/146648842-e56b060a-1e06-4796-be84-bd37e7113615.png)

Unfortunately, even though it seems to be building the app, the service worker is not working - even after I followed the Vue 3 example...
![image](https://user-images.githubusercontent.com/4270980/146648866-4c8e34a7-0588-4ded-9e4c-a083402d0729.png)

I find the instructions a bit unclear, so I am probably missing something. I've followed the site documentation, but when I started looking into the vue example repo itself - there is some setup that is not mentioned in the documentation itself... for example, do I need to have this file in my repo https://github.com/antfu/vite-plugin-pwa/blob/main/examples/vue-router/src/claims-sw.ts? Am I missing something else? It's quite hard to tell to be honest

**Comment by userquin** [comment]
@doutatsu you need to call `registerSW` from `virtual:pwa-register` or if using vue, `useRegisterSW` from `virtual:pwa-register/vue`. If you don't call `registerSW` or `useRegisterSW` the sw will not be registered.

**Comment by userquin** [comment]
the example projects are condensed to allow test each framework with the same codebase using different strategies and behavior (`registerType`): if you use `generateSW` strategy you don't need any of the sw.

**Comment by KenEucker** [comment]
I have an issue with my vite built pwa site on netlify where every time a new deploy is published all clients have to hard refresh the site or else they get a blank screen, forever. I have to hard refresh on desktop and it requires opening and closing chrome on android several times as well to get it to load properly again. After this, the "new content has loaded" dialog pops and is confusing because it doesn't reload after you've already gone through the process I described.

In some cases, if I am using the site after a deploy, I will see the new content dialog pop and I can click reload and the client reloads fine.

**Comment by doutatsu** [comment]
On my side - I did manage to get it working and service worker seems to be working as expected. Not sure what it was in the end - but seems to be the combination of the correct Netlify configuration and properly calling `registerSW`, but I tried a lot of things, so not sure what exactly got it working for me
