### ISSUE TITLE
how to off strict  mode for assets  ?

### ISSUE THREAD

**Issue by reslear** [antfu/vite-plugin-pwa#187]
<img width="557" alt="Screenshot 2021-12-03 at 13 34 01" src="https://user-images.githubusercontent.com/12596485/144550886-f443f834-c781-4340-83d7-c093305209b0.png">

how to skip assets and continue build, is not found
right now i'm get build fail on production

**Comment by userquin** [comment]
@reslear the error is not from pwa plugin, this plugin only fails when the vite build fails, you've an error on `src/composable/useAlert.ts` module. The build script will also fails if you remove this plugin from your application.

**Comment by userquin** [comment]
Use dynamic import on `onMount` hook, catch the error and add the image only if that var is set, use ref for it:

```ts
const img = ref(null)
onMount(async()=>{
  try {
    Img.value = await import('...').default
  } catch(_) {}
})
```
Then in your template
```html
<template v-if="img">
  <img src="img"....>
```

**Comment by reslear** [comment]
good, thanks
would like to have a mode in which, due to the lack of assets, the build did not stop

**Comment by userquin** [comment]
@reslear if your codebase import resources you later remove what do you expect to happen?
