### ISSUE TITLE
getting started doc

### ISSUE THREAD

**Issue by softboy99** [antfu/vite-plugin-pwa#19]
Hi,
i'm newer to pwa, is there any doc/example for getting started? is there "registerServiceWorker.js" like vue cli? where to put the "maniestfest" file? Thanks a lot for your great help.

**Comment by softboy99** [comment]
sw.js error in console after build for production, "cannot use import statement outside module" ,"failed to register service worker"

**Comment by hannoeru** [comment]
example:
https://github.com/antfu/vitesse/blob/8e492449b6a0caebab183d07f9fee0ff3cb09a5e/vite.config.ts#L58-L76
