### ISSUE TITLE
[feat] Add option to disable for production mode

### ISSUE THREAD

**Issue by yann-combarnous** [antfu/vite-plugin-pwa#190]
We are using Cypress for testing, and building our app for faster testing.

Vite is great in development mode, but for testing the entire app, using Vite dev server and loading all of our files on each test is too slow, as Cypress clears the cache on each step. 

So we use app builds to test, but we have no option to disable service worker generation in this plugin. Just removing plugin will not work due to the virtual package added in our code for React inclusion.

See https://www.npmjs.com/package/vite-plugin-istanbul for example options to enable / disable in production using env variables.

**Comment by userquin** [comment]
I'll check this, in the mean time you can use dynamic import and check for `window.Cypress`, for example:

```ts
if (typeof window !== 'undefined' && typeof window.Cypress === 'undefined') {
  import('./pwa.[j|t]s') // <== pwa.[j|t]s will import the virtual module and call registerSW
}
```

For `ReloadPrompt` use similar logic to load the component.

**Comment by userquin** [comment]
@yann-combarnous I'll included a new `disable` option on `VitePWAOptions` and so you can configure it using yours env variables. This option will disable the generation and sw registration, the virtual module will be still there and so you don't need to change the codebase (the plugin will generate the dev module of the corresponding framework you're using).

**Comment by JessicaSachs** [comment]
Hey @yann-combarnous are you using Cypress Component Testing or Cypress E2E?

**Comment by yann-combarnous** [comment]
> Hey @yann-combarnous are you using Cypress Component Testing or Cypress E2E?

Both, while cypress component testing is fast, cypress e2e loads 1000s of files for each test, if I use Vite dev server. So building bundle and doing ‘vite preview’ is faster for Cypress e2e.

**Comment by JessicaSachs** [comment]
Yeah. Component is just a Vite plugin. So for E2E, I generally `vite build` to dist the Vite app and then host it statically like I would in prod. Disting the app removes the per-module waterfall requests. Like with an express static server.

In addition to this, if you're running `vite dev` and hitting that as your app, keeping your `optimizeDeps` up to date is absolutely critical for the best performance. If you're not doing this, try out Antfu's [vite-plugin-optimize-persist](https://github.com/antfu/vite-plugin-optimize-persist#install).

Is that essentially what you've tried doing?

**Comment by userquin** [comment]
@yann-combarnous can you test with the new release `0.11.12`?

**Comment by yann-combarnous** [comment]
> @yann-combarnous can you test with the new release `0.11.12`?

LGTM, just tried with `disable: true` and without the option, works as expected. Thx!

**Comment by yann-combarnous** [comment]
> Yeah. Component is just a Vite plugin so it's more 🏎. So for E2E, I generally `vite build` to dist the Vite app and then host it statically like I would in prod. Disting the app removes the per-module waterfall requests. When I say host it, I mean with something like an express static server.
> 
> In addition to this, if you're running `vite dev` and hitting that as your app, keeping your `optimizeDeps` up to date is absolutely critical for the best performance. If you're not doing this, try out Antfu's [vite-plugin-optimize-persist](https://github.com/antfu/vite-plugin-optimize-persist#install).
> 
> Is that essentially what you've tried doing?

Yep, and now with this new option in vite-plugin-pwa, I can get rid of managing the service worker lifecycle in Cypress. Thx.
