### ISSUE TITLE
Provide function to filter what gets injected

### ISSUE THREAD

**Issue by Snugug** [antfu/vite-plugin-pwa#192]
The `injectManifest` functionality is great for building your own custom service worker, but it appears as if the only option I have when using it is inject every file that Vite generated, or use something else. Precaching (which is what this is usually used for) should IMO be used sparingly on key important assets, not on everything. As such, I'd love a config option to pass a function, that effectively acts as a filter on the array of items being sent to Workbox to inject. I'm also happy to contribute this functionality myself if you're up for that.

Thanks!

**Comment by userquin** [comment]
@Snugug why not just use the `injectManifestOption` plugin option? You can filter using the `globPatterns` and `globIgnores` options. See for example the sveltekit example https://github.com/antfu/vite-plugin-pwa/blob/main/examples/sveltekit-pwa/pwa-configuration.js#L50

**Comment by Snugug** [comment]
Thanks! I'll look at that tomorrow!

Maybe this winds up being a documentation issue instead of a feature request, as this config is buried under static asset handling instead of configuration of injectManifest where I expected it to be.

**Comment by userquin** [comment]
@Snugug check also some hints I add on your issue 151 on chromeos

**Comment by userquin** [comment]
@Snugug about the docs, just read https://vite-plugin-pwa.netlify.app/workbox/#how-is-workbox-build-related-to-vite-plugin-pwa

You can see the options provided to `workbox` here https://vite-plugin-pwa.netlify.app/workbox/#how-is-workbox-build-related-to-vite-plugin-pwa and here https://github.com/antfu/vite-plugin-pwa/blob/main/src/types.ts#L87 (both options are workbox types):
- for `generateSW` strategy, we provide `workbox` pwa plugin option to `workbox::generateSW` method (with some defaults, check https://github.com/antfu/vite-plugin-pwa/blob/main/src/options.ts#L69)
- for `injectManifest` strategy, we provide `injectManifest` pwa plugin option to `workbox::injectManifest` method (with some defaults, check https://github.com/antfu/vite-plugin-pwa/blob/main/src/options.ts#L79)
