### ISSUE TITLE
Generated service worker is created after Rollup writeBundle hook?

### ISSUE THREAD

**Issue by IAmRGroot** [antfu/vite-plugin-pwa#194]
I have a situation where I need to copy the contents of the build (dist) folder to another folder at the end of the build. I'm currently adding the vite-plugin-pwa but I'm having the following problem.

I'm using https://github.com/vladshcherbin/rollup-plugin-copy to copy the files.

In this example (https://github.com/IAmRGroot/vite-pwa-copy-replication) I copy the src/dist folder to src/out with the following result:

![image](https://user-images.githubusercontent.com/8398505/147348662-533bd9e6-c2a8-4515-b276-1ee33ec3e79c.png)

I would expect the contents of the folders to be the same but VitePWA generates it's sw.js and workbox.js after the copy plugin is done, and thus are those files not copied.

Is there any configuration that allows my use case?

**Comment by userquin** [comment]
@IAmRGroot  just move the copy plugin before the pwa plugin

**Comment by userquin** [comment]
@IAmRGroot sorry, misundertood the question, try this:
```ts
      {
         ...copy({
            targets: [
                {
                    src: 'src/dist/*',
                    dest: 'src/out',
                },
            ],
            overwrite: true,
            hook: 'writeBundle',
            preserveTimestamps: true,
        }),
       enforce: 'post'
     }
```

**Comment by IAmRGroot** [comment]
In my original project I actually already tried adding the enforce: 'post'. Still the same result sadly

**Comment by userquin** [comment]
@IAmRGroot  I'll check the `copy` plugin to see what is doing... try also adding to the `copy` plugin `apply: 'build'`, see vitejs docs...

**Comment by userquin** [comment]
@IAmRGroot change also the `hook` entry to `hook: 'buildEnd'`.

**Comment by userquin** [comment]
@IAmRGroot if not working just create your own script, you don't need to copy dist folder using a plugin, for example, you can just drop a `copy.ts/copy.js` module on your root and then using `fast-glob` you can traverse the `dist` folder and copy the content to the `out` directory, then on your build script: `vite build && node copy.js` or `vite build && esno copy.ts` (using `ts` you need to install `esno` as `dev dependency`)

**Comment by IAmRGroot** [comment]
Thanks for the quick replies! 

I figured I could just run a custom js script, but thought if there is a copy plugin why not use it.

Changing the hook to buildEnd and the apply: build seem to do it, but just not on subsequent runs....

![image](https://user-images.githubusercontent.com/8398505/147352404-47dc0ad2-74db-41c3-82f7-31d9b70ec7fb.png)

The first run succeeds with all the file there, but the second run ends with an empty out folder

**Comment by userquin** [comment]
@IAmRGroot the problem here is that the rollup copy plugin is not compatible with your vite configuration, so you need to modify your build process.

Anyway, why the output error is copying the files to the src directory? both directories, `dist` and `out`, should be on `root` folder` not inside `src` folder.

**Comment by IAmRGroot** [comment]
That has no particular reason, it was just a quick (and maybe dirty) setup for this problem.

I will just solve it with a custom script. Thanks for pointing out esno, I will use it!
