### ISSUE TITLE
Not allowed to use URLs as source for manifest icons

### ISSUE THREAD

**Issue by qalaya** [antfu/vite-plugin-pwa#196]
Is there any specific reason to not allow the usage of URLs on manifest icons?
I'm trying to build an app like: 

```
pwa({
      manifest: {
        name: process.env.APP_NAME,
        short_name: process.env.SHORT_NAME,
        description: process.env.DESCRIPTION,
        theme_color: process.env.THEME_COLOR,
        background_color: process.env.THEME_COLOR,
        icons: [
          {
            src: process.env.ICON512,
            sizes: "512x512",
            type: "image/png",
            purpose: "any maskable"
          },
          {
            src: process.env.ICON192,
            sizes: "192x192",
            type: "image/png"
          },
          {
            src: process.env.ICON512,
            sizes: "512x512",
            type: "image/png"
          }
        ]
      },
    }),
```
But i'm facing this error at build time:

```
error during build:
7:57:51 PM: TypeError: Cannot read properties of undefined (reading 'startsWith')
7:57:51 PM:     at /opt/build/repo/node_modules/vite-plugin-pwa/dist/index.js:224:16
7:57:51 PM:     at Array.map (<anonymous>)
7:57:51 PM:     at configureStaticAssets (/opt/build/repo/node_modules/vite-plugin-pwa/dist/index.js:223:60)
7:57:51 PM:     at resolveOptions (/opt/build/repo/node_modules/vite-plugin-pwa/dist/index.js:368:9)
7:57:51 PM:     at Object.configResolved (/opt/build/repo/node_modules/vite-plugin-pwa/dist/index.js:542:25)
7:57:51 PM:     at /opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:68353:127
7:57:51 PM:     at Array.map (<anonymous>)
7:57:51 PM:     at resolveConfig (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:68353:35)
7:57:51 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
7:57:51 PM:     at async doBuild (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42986:20)
```
I know that URLs are not THE best practice for PWA icons but it usually works. At some moments it is really helpful to have this option.
Am I missing something?

**Comment by userquin** [comment]
@qalaya I think you cannot use external resources, I'm looking on the specs and it seems you can only serve them from the same codebase:
- https://www.w3.org/TR/appmanifest/#icons-member
- on green **NOTE** you have this link: [process image resources](https://www.w3.org/TR/appmanifest/#dfn-process-image-resources)
- on point 4.1 you have this link: [process an image resource from JSON](https://www.w3.org/TR/image-resource/#dfn-process-an-image-resource-from-json)
- on point 3 you have this: Let src be the result of parsing input["src"] with base as the base URL.

**Comment by userquin** [comment]
closing this, if you want to play with a custom sw manually to check if it is working with external resources, provide a working repro and I'll reopen this issue

**Comment by qalaya** [comment]
Yes, URLs work as source for pwa icons. I have successfully used this for a while. But if it is not open for discussion here, ok. I'll try something.

**Comment by userquin** [comment]
@qalaya just provide a repro on gh or startblitz or something we can begin testing, I only close the issue, keep in mind we need to add `fetch` for node, detect `http/https` then fetch the icon, or I'm missing something (maybe only check for `http/https on icons and do not exclude them from the logic on build)?.
