### ISSUE TITLE
[vite-plugin-pwa] 'statSync' is not exported by __vite-browser-external, imported by node_modules\.pnpm\import-meta-resolve@1.1.1\node_modules\import-meta-resolve\lib\resolve.js

### ISSUE THREAD

**Issue by frck006** [antfu/vite-plugin-pwa#197]
Hi,

Do you know why I have this error when I build "pnpm build" ?
It works when I use "pnpm dev"
I update all packages.

![image](https://user-images.githubusercontent.com/10244725/148026417-d9108352-a3a9-4105-a946-25f3b8944484.png)

```shell
[vite-plugin-pwa] 'statSync' is not exported by __vite-browser-external, imported by node_modules\.pnpm\import-meta-resolve@1.1.1\node_modules\import-meta-resolve\lib\resolve.js
file: C:/app/web-app/nvite/node_modules/.pnpm/import-meta-resolve@1.1.1/node_modules/import-meta-resolve/lib/resolve.js:22:15
20:
21: import {URL, fileURLToPath, pathToFileURL} from 'url'
22: import {Stats, statSync, realpathSync} from 'fs'
                   ^
23: import path from 'path'
24: import builtins from 'builtins'

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
C:\app\web-app\nvite\node_modules\.pnpm\rollup@2.62.0\node_modules\rollup\dist\shared\rollup.js:158
        base = Object.assign(new Error(base.message), base);
                             ^

Error: 'statSync' is not exported by __vite-browser-external, imported by node_modules\.pnpm\import-meta-resolve@1.1.1\node_modules\import-meta-resolve\lib\resolve.js
    at error (C:\app\web-app\nvite\node_modules\.pnpm\rollup@2.62.0\node_modules\rollup\dist\shared\rollup.js:158:30)
    at Module.error (C:\app\web-app\nvite\node_modules\.pnpm\rollup@2.62.0\node_modules\rollup\dist\shared\rollup.js:12420:16)
```

**Comment by userquin** [comment]
@frck006 can you provide what version of `vite-ssg` and `node` are you using? Anyway, this should be on `vite-ssg` since this is not a problem with pwa plugin.

**Comment by frck006** [comment]
You should have right.
I reinstall all packages to see what package/version could produce this problèm.

And now the problem is with vite-ssg
- "vite-ssg": "0.17.5",
- "vite": "2.7.10",
- node => v16.13.1
![image](https://user-images.githubusercontent.com/10244725/148070305-9364beb9-e943-47c9-80f0-bd880f171057.png)

**Comment by userquin** [comment]
@frck006 try adding `format: 'cjs'` on `ssgOptions`  on your Vite config file.

**Comment by frck006** [comment]
@userquin , not the same error:
![image](https://user-images.githubusercontent.com/10244725/148078451-d0c2c0b7-60be-4e1e-b596-234287e361a5.png)

**Comment by userquin** [comment]
closing this since it is not related to this repo

**Comment by userquin** [comment]
@frck006 it is not the same error, please check: https://github.com/antfu/vite-ssg/issues/154

**Comment by frck006** [comment]
It was necessary to change format: 'cjs' ? because the default is "esm"

**Comment by userquin** [comment]
just try removing the `format`.
