### ISSUE TITLE
"The start_url did response, but not via a service worker"

### ISSUE THREAD

**Issue by scambier** [antfu/vite-plugin-pwa#20]
Hello,

I installed your plugin over a VueJS 3 / Vite 2 app, configured it as best as I can, and Lighthouse returns this error:
![image](https://user-images.githubusercontent.com/3216752/106606352-527c2480-6562-11eb-96ef-956714f5c6c7.png)

How can I fix this issue?

My vite.config.ts:

```ts
const config: UserConfig = {
  plugins: [
    vue(),
    VitePWA({
      manifest: {
        icons: [
          {
            src: 'img/icons/graph-144.png',
            sizes: '144x144',
            type: 'image/png',
            purpose: 'maskable'
          }
        ],
        theme_color: '#34b4e4'
      }
    })
  ],
  alias: {
    '@': resolve(__dirname, 'src')
  }
}
```

**Comment by antfu** [comment]
Should be fixed in v0.4.2.

**Comment by scambier** [comment]
@antfu thanks, but the issue is still present

**Comment by antfu** [comment]
Did you try to unregister your sw and refresh again? If that doesn't work, can you provide a minimal repro so I can give it a look?

**Comment by RazerMoon** [comment]
I'm also having this issue.

![image](https://user-images.githubusercontent.com/33849459/106833277-260ff780-668b-11eb-9907-354894589a3e.png)

[Repo](https://github.com/RazerMoon/Vue-PWA)

[Website](https://vue-test-bice.vercel.app/)

https://github.com/RazerMoon/Vue-PWA/blob/35edfcbc99bd90b875c4ed9ccb14e669b36e1531/package.json#L36

https://github.com/RazerMoon/Vue-PWA/blob/35edfcbc99bd90b875c4ed9ccb14e669b36e1531/yarn.lock#L5635-L5643

**Comment by hannoeru** [comment]
I think that is a Lighthouse's bug, it has been fixed and will be ship with Chrome 89.
https://github.com/GoogleChrome/lighthouse/issues/10237
Chrome release schedule:
https://chromiumdash.appspot.com/schedule

**Comment by RazerMoon** [comment]
Just installed the Chrome beta, can confirm it is indeed a Lighthouse bug

![image](https://user-images.githubusercontent.com/33849459/107097850-cf7af880-6805-11eb-9d89-792325753592.png)

**Comment by stefba** [comment]
This bug effectively breaks the normal PWA "Add to home screen" behavoir of my app. (The little Chrome icon is displayed on top of the app.) I am already on Chrome Mobile 89 on Android.

> I think that is a Lighthouse's bug, it has been fixed and will be ship with Chrome 89.
