### ISSUE TITLE
Missing a 'vanilla-js' example

### ISSUE THREAD

**Issue by jellehak** [antfu/vite-plugin-pwa#207]
Couldn't find any example for a native approach is this intentional ? Frameworks are nice but the bare minimum should be a native example.

**Comment by userquin** [comment]
@jellehak what do you mean with native?

**Comment by mkhennoussi** [comment]
I think he means a working example with the basic "vanilla-js" template from `create vite` for instance. Without using frameworks.
Just tried to add this plugin to the simplest web app. Found a lot of issues to get it working properly.

**Comment by userquin** [comment]
@mkhennoussi @jellehak  https://github.com/userquin/vite-plugin-pwa-vanillajs

**Comment by jellehak** [comment]
@mkhennoussi Yes indeed, perfectly described. Would be nice, seems very weird to have the basics "vanilla-js" missing.

**Comment by userquin** [comment]
closing this since you have an example, maybe in a future I can move my repo here
