### ISSUE TITLE
Error: Failed to resolve import "virtual:pwa-register/react"

### ISSUE THREAD

**Issue by jeremytenjo** [antfu/vite-plugin-pwa#210]
Getting `Failed to resolve import "virtual:pwa-register/react"` error when importing from `virtual:pwa-register/react`

**Reproduce**

```sh
git clone https://github.com/jeremytenjo/starter-webapp.git && cd starter-webapp && git checkout vite-plugin-pwa && npm i && npm run app:dev
```

**File producing error**

`ReloadPrompt.tsx`

```js
import { useRegisterSW } from 'virtual:pwa-register/react'
```

`tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": true,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "./",
    "paths": {
      "*": ["devtools/ts/declaredModules/*"]
    },
    "types": ["vite-plugin-pwa/client", "cypress", "vite/client"]
  },
  "include": ["./src", "./functions/scripts", "devtools/ts/declaredModules/*"],
}
```

`package.json` 

```json 

   "vite": "^2.7.12",
   "vite-plugin-pwa": "^0.11.12",
   "workbox-window": "^6.4.2"
```

Thank you!

**Comment by userquin** [comment]
remove `"virtual:pwa-register": ["node_modules/vite-plugin-pwa"]` and `"files": ["node_modules/vite-plugin-pwa/client.d.ts"]

you have an exmaple for react here: https://github.com/antfu/vite-plugin-pwa/blob/main/examples/react-router/tsconfig.json

**Comment by jeremytenjo** [comment]
Thanks @userquin but I even get the error in that example 
![image](https://user-images.githubusercontent.com/25231946/150201240-07f5f50f-67dd-454b-a87d-54603fa41ef8.png)

**Comment by userquin** [comment]
@jeremytenjo try this https://github.com/antfu/vite-plugin-pwa/blob/main/examples/react-router/src/vite-env.d.ts

**Comment by jeremytenjo** [comment]
No luck unfortunately. This is the repo https://github.com/jeremytenjo/starter-webapp/tree/virtual-pwa-register/react

**Comment by userquin** [comment]
move the dts inside the src folder

**Comment by jeremytenjo** [comment]
No Luck

**Comment by jeremytenjo** [comment]
Curious why we have to import `useRegisterSW` from `virtual:pwa-register/react` instead of `vite-plugin-pwa/client` ?

**Comment by jeremytenjo** [comment]
The reason I was getting the error was because only loaded the plugin in `production` mode
