### ISSUE TITLE
updateServiceWorker(true) when the app is open in different tabs

### ISSUE THREAD

**Issue by carlos-montiers** [antfu/vite-plugin-pwa#212]
Hello, I'm using react with strategies: 'injectManifest', registerType 'prompt' and the service worker prompt-sw.ts and periodic updates (1 minute for development):

```
const intervalMS = 60 * 1000; // 1 minute
  const {
    offlineReady: [offlineReady, setOfflineReady],
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    immediate: true,
    onRegistered(r: ServiceWorkerRegistration | undefined) {
      if (r) {
        console.log("SW Registered: " + r);
        // Configure periodic service worker updates
        setInterval(async () => {
          console.log("Updating sw");
          await r.update();
          console.log("SW Updated");
        }, intervalMS);
      }
    },
    onRegisterError(error) {
      console.log("SW registration error", error);
    },
  });
```

If I open the app in two tabs of the browser, and publish an update, after 1 minute I see the notification in the both tabs (with the button to reload). This button call to `updateServiceWorker(true)`

In the first tab if I press the reload button the tab content is refreshed, but after, in the second tab if I press the button it do nothing.

Please, some help to fix this ?

Carlos

**Comment by userquin** [comment]
The sw is system Wide, once reloaded, all the clients will be reloaded (any client controlled by the current sw): any tab but also any browser instance.

The problem here is to detect that event on other clients to hide the prompt.

**Comment by carlos-montiers** [comment]
> The sw is system Wide, once reloaded, all the clients will be reloaded (any client controlled by the current sw): any tab but also any browser instance.
> 
> The problem here is to detect that event on other clients to hide the prompt.

Oh, thanks. This workaround works for me:
```
const reload = async () => {
    await updateServiceWorker(true);
    window.location.reload();
  };

Thus, if the updateServiceWorker don't refresh the next line will do.

```
