### ISSUE TITLE
Incorrect type for icons property in manifest

### ISSUE THREAD

**Issue by www-chique** [antfu/vite-plugin-pwa#213]
The type definitions for "icons" in the manifest might be incorrect.
I am receiving the following type warning:
![image](https://user-images.githubusercontent.com/29447216/150319812-6125523e-4772-4ee4-8798-97adea934c43.png)

The correct usage for the "icons" can be found at [Google's Web.dev](https://web.dev/add-manifest/#create), or at [MDN ](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons) (and as seen in my screenshot).

I am a newbie at this, but this might be coming from the type definitions file (/dist/index.d.ts), the type of icons are mentioned as `icons: Record<string, any>[];`

**Comment by userquin** [comment]
Add the type entry with `image/png`, check any vite config on the examples directory

**Comment by www-chique** [comment]
I apologize.
Even with the "type" it looks the same. What am I doing wrong?

![image](https://user-images.githubusercontent.com/29447216/150771963-6d2585f4-3780-49cb-9d8e-c75ca37c544f.png)
