### ISSUE TITLE
Incorrect type for icons property in manifest

### ISSUE THREAD

**Issue by www-chique** [antfu/vite-plugin-pwa#216]
Previously, I have opened an issue at #213, but even after following the solutions, the error did not resolve.

The type definitions for "icons" in the manifest might be incorrect.
I am receiving the following type warning:
image
![image](https://user-images.githubusercontent.com/29447216/150772335-dee79285-c98f-40a5-b2d6-06ea4f18610f.png)

I am a newbie at this, but this might be coming from the type definitions file (/dist/index.d.ts), the type of icons are mentioned as icons: Record<string, any>[];

**Comment by userquin** [comment]
Icons option is for manifest root not for shortcuts, why do you need icons on shortcut entries?

**Comment by userquin** [comment]
https://github.com/antfu/vite-plugin-pwa/blob/main/src/types.ts#L213

**Comment by userquin** [comment]
https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts

**Comment by userquin** [comment]
It seems we need to review the mapping

**Comment by www-chique** [comment]
> Icons option is for manifest root not for shortcuts, why do you need icons on shortcut entries?

I saw you already posted the MDN links regarding why we need icons on shortcut entries.
Thanks.

**Comment by johannb75** [comment]
Having the same, issue, any update on this?
