### ISSUE TITLE
How to remove PWA ?

### ISSUE THREAD

**Issue by DaPotatoMan** [antfu/vite-plugin-pwa#217]
Hello,
I am using Vercel to deploy my app. I previously added this plugin but I can't remove it since the changes do not apply on the client-side. What I mean is, when I remove this plugin the client-side website doesn't update at all.

Please let me know how can I resolve this issue.
Thanks!

**Comment by userquin** [comment]
Once the service worker is registered on client side the user should remove it or you can include a script in your `index.html`, then once removed your new version will not register and use the service worker.

You can check the service worker is not registered on your app openningyour app in private window.

For more info, check https://medium.com/@nekrtemplar/self-destroying-serviceworker-73d62921d717

```ts
navigator.serviceWorker.getRegistrations().then(function(registrations) { 
  for(let registration of registrations) { 
    registration.unregister(); 
  } 
});
```

**Comment by DaPotatoMan** [comment]
@userquin Thanks! It worked.
