### ISSUE TITLE
Question: Nested paths breaks lighthouse PWA test

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-pwa#23]
I have found some problems when using nested routes with the plugin: lighthouse cannot resolve `start_url` when in nested path route, for example just request `https://vitesse.netlify.app/hi/a` in private mode on chrome, open dev tools and run lighthouse with PWA check checked:

![imagen](https://user-images.githubusercontent.com/6311119/107119965-152dd480-688b-11eb-84d9-5c9a132c9c84.png)

The problem in question can be solved just adding the `scope` to the `manifest.webmanifest` file and also initializing it with the `basePath`.

By default it is initialized as `./`, and I don't know if this value is ok to be used as `scope` when registering the service worker. I register it using `router.isReady` callback instead on index page and change the default pattern to be `/`, and so the header, the `manifest.webmanifest` and the registration matches:

![imagen](https://user-images.githubusercontent.com/6311119/107124207-b3796480-68a2-11eb-957a-07b363bd7c70.png)

This is because it seems that the nested parent path acts as a new scope, that is distinct from the missing `scope`.

Another think that I don't know if it is required is to add a header like that to the html (I just add it as a http header from the server side):

```
service-worker-allowed: `${basePath}`
```

Here is a working [manifest.webmanifest](https://cancer.malvarez.info/manifest.webmanifest).

You can see a working sample here: https://cancer.malvarez.info/conozca-su-riesgo, then click on + icon and run the test (it is with vite 1 + vitesse 1, I'm migrating it to vite 2 + vitesse 2).

**Comment by userquin** [comment]
You can see this articale: https://dev.to/njromano/how-to-scope-your-pwa-service-workers-1n6m

**Comment by antfu** [comment]
Can you verify if v0.4.5 fixes your problem? Thanks.

**Comment by userquin** [comment]
If I remove `start_url`  and `scope` from `vite.config.ts`, the generated `manifest.webmanifest` file has no the `scope`...

![imagen](https://user-images.githubusercontent.com/6311119/107126358-b3339600-68af-11eb-9185-144ab0b9de51.png)

with generated file:

![imagen](https://user-images.githubusercontent.com/6311119/107126325-83848e00-68af-11eb-8830-f564c546f7e7.png)

```shell
F:\work\projects\quini\vite-vitesse-2\dssa-cancer-mama-ui-v2>pnpm upgrade vite-plugin-pwa
 WARN  @intlify/vite-plugin-vue-i18n: @rollup/pluginutils@4.1.0 requires a peer of rollup@^1.20.0||^2.0.0 but none was installed.
 WARN  vite-plugin-pages@0.1.9 requires a peer of vite@^2.0.0-beta.61 but version 2.0.0-beta.46 was installed.
Packages: +1 -1
+-
Progress: resolved 701, reused 700, downloaded 1, added 1, done
 WARN  Failed to find "/fsevents/2.1.3" in lockfile during hoisting. Next aliases will not be hoisted: fsevents

devDependencies:
- vite-plugin-pwa 0.4.4
+ vite-plugin-pwa 0.4.5
```

**Comment by userquin** [comment]
@antfu I have not marked this as a bug, in fact I can it make work just configuring it on the configuration file: there is no need to change the code... just was an enhacement, add some hints on the README.md file and done.

**Comment by antfu** [comment]
The scope would be set to `base` by default from v0.4.6. I think it's good to make things just works if possible, thanks for the notice and suggestions

**Comment by userquin** [comment]
@antfu do you deploy the demo to netifly when versioning? demo on netifly still with missing scope on manifest file

I have tested that `v0.4.6` generates the scope correctly on pages (inlined) and `registerWS.js` (not inlined) and `manifest.webmanifest`.

**Comment by antfu** [comment]
What do you mean demo? Vitesse? That's a separate repo and the deps need to update manually (where I often do it once a while)

**Comment by userquin** [comment]
yes

**Comment by userquin** [comment]
when you redeploy it, just test the dynamic page...

**Comment by userquin** [comment]
@antfu I think it will need the header to make it work.

**Comment by userquin** [comment]
@antfu After some review (vitesse demo) it seems that PWA with dynamic pages are incompatible: a PWA must have an URL for each page, so if we map a page to be dynamic then we got that the service worker cannot resolve it, it is dynamic, and then on ligthhouse we got:

![imagen](https://user-images.githubusercontent.com/6311119/107501331-8aedb500-6b97-11eb-8ad6-24e2c0422ce2.png)

You can see that there is a `Check List` that ligthhouse doesn't check, it must be done manually:
 
![imagen](https://user-images.githubusercontent.com/6311119/107501454-b2dd1880-6b97-11eb-8d55-1b6d53a557ae.png)

**Comment by hannoeru** [comment]
Dynamic route should fixed in v0.4.2, and `start_url` is a lighthouse issue #20

**Comment by userquin** [comment]
@hannoeru can you test vitesse root page demo on incognito mode with Chrome Beta?

I'm testing my app with chrome 88 and I have not this issue in any page.

**Comment by userquin** [comment]
I think this is not a lighthouse bug, it is something related to the configuration:

![imagen](https://user-images.githubusercontent.com/6311119/107513392-6d751700-6ba8-11eb-9286-5a112b793afc.png)

**Comment by userquin** [comment]
while the root page of vitesse demo (there is no dynamic page):

![imagen](https://user-images.githubusercontent.com/6311119/107513551-ac0ad180-6ba8-11eb-8b27-3f3eaaa8079b.png)

**Comment by userquin** [comment]
I don't understand what's happening. I create a simple `test-app.js` (code below) configuring `node` with `node-static` to serve `dist` folder and just works, so I don't know why is failing on netlify.

Just running `node test-app-js`:

![imagen](https://user-images.githubusercontent.com/6311119/107523815-6bfe1b80-6bb5-11eb-9bc4-20b8ac1dbb11.png)


```javascript
/* eslint-disable */
'use strict'

const http = require('http')
const https = require('https')
const fs = require("fs");
const path = require('path')
const nStatic = require('node-static')

const fileServer  = new nStatic.Server('./dist')

const hostname = '192.168.1.37'
const port = 443

const httpsRedirect = async(req, res) => {
  res.writeHead(301, { "Location": `https://${hostname}:${port}${req.url}` });
  res.end()
}

const secureServer = https.createServer({
  ca: fs.readFileSync('192.168.1.37_allowed_cas.crt'),
  key: fs.readFileSync('192.168.1.37.key'),
  cert: fs.readFileSync('192.168.1.37.crt'),
}, (req, res) => {
  fileServer.serve(req, res)
})

secureServer.listen(443, () => {
  console.log(`El servidor se está ejecutando en https://${hostname}:${port}/`)
})

const redirectServer = http.createServer(httpsRedirect)

redirectServer.listen(80, () => {
  console.log(`El servidor se está ejecutando en http://${hostname}:${80}/`)
})
```

**Comment by userquin** [comment]
Something is wrong @antfu , go to vitesse demo page, then open manifest from devtools, it is base64 encoded.

You must configure netlify to server `manifest.webmanifest` files with `application/manifest+json` content type, it is being served with `application/octet-stream` content type.

![imagen](https://user-images.githubusercontent.com/6311119/107525914-9a7cf600-6bb7-11eb-9369-b72ec2f1d063.png)

**Comment by userquin** [comment]
Add this to `netlify.toml`:

```toml
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
```

**Comment by hannoeru** [comment]
That didn't fixed the `start_url` issue, PR preview:
https://deploy-preview-54--vitesse.netlify.app/

**Comment by userquin** [comment]
WTF ;) I'm missing something...

**Comment by userquin** [comment]
Who is setting `x-robots-tag: noindex`?

**Comment by userquin** [comment]
This prevent to service worker to download the PWA.

Open preview url, open devtools, go to application, remove storage including indexeddb and service workers.

If you press F5, then only workbox and sw scripts downloaded, the rest of the app is not downloaded...

So when testing, just didn0t work, all files are missing from the cache.

**Comment by userquin** [comment]
If you open the same app on dev, you will see that PWA is downloaded:

Fron localhost via node-static:

![imagen](https://user-images.githubusercontent.com/6311119/107537772-8b03aa00-6bc3-11eb-99ec-bb7dba3b64ee.png)

The same from your preview url:

![imagen](https://user-images.githubusercontent.com/6311119/107537819-97880280-6bc3-11eb-8250-eb8957af5791.png)

**Comment by userquin** [comment]
@hannoeru

**Comment by userquin** [comment]
forget previous comments, it seem it is another ghost..

**Comment by userquin** [comment]
can update `netlify.toml` to include expiration and immutable entries to the `manifest.webmanifest` entry? It is served with `cache-control: public, max-age=0, must-revalidate` and `age: 2035`.

**Comment by userquin** [comment]
also forgot last comment, tested on local and works as expected with those headers
