### ISSUE TITLE
pushManager.subscribe  does not ask me whether to display a notification

### ISSUE THREAD

**Issue by zzh948498** [antfu/vite-plugin-pwa#231]
https://vite-plugin-pwa.netlify.app/workbox/inject-manifest.html#server-push-notifications

I want to subscribe the user，but the `self.registration.pushManager.subscribe` will not popup tooltip

![image](https://user-images.githubusercontent.com/35091020/155067166-6fbe65ae-15da-4df5-ae89-d88999655dc3.png)

I'm not familiar with service workers. Thanks in advance for your help.

My code ：https://github.com/zzh948498/vue-template

**Comment by userquin** [comment]
the docs are outdated, the server push notifications have changed, check this: https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications

you can also take a look at this repro from workbox core team member: https://github.com/jeffposnick/yt-playlist-notifier
