### ISSUE TITLE
Prompt to refresh new content, and want to add custom prompt information function.

### ISSUE THREAD

**Issue by qcyblm** [antfu/vite-plugin-pwa#237]
Better support for multilingual management of site projects

**Comment by userquin** [comment]
@qcyblm what do you mean about i18n? this plugin is ui agnostic, you should resolve it with your ui/app framework.

For example, if you're using `vitesse` template (vue 3), it is using `vue-i18n`, so changing the `registerType` to `prompt` you can add the entries into the `locales/*.yml` files and using the i18n entries on the  `ReloadPrompt` component you should add (`vitesse` template is using `autoUpdate` and so the `ReloadPrompt` component is missing).

If it is about i18n on manifest, check this issue: https://github.com/antfu/vite-plugin-pwa/issues/132

**Comment by qcyblm** [comment]
@userquin 
Look at the figure, is there a corresponding parameter to modify the button label and prompt information?
![image](https://user-images.githubusercontent.com/64412486/156180098-4ff2bc78-c265-46cf-80fa-bcaaf2556166.png)

**Comment by userquin** [comment]
@qcyblm this is an screenshot, you can take a look at this component: https://github.com/antfu/vite-plugin-pwa/blob/main/examples/vue-router/src/ReloadPrompt.vue#L40

If you're using vue 3 with vue-i18n, just replace text with `$t('xxxx')` or using `const { t } = useI18n()`. If you're using another framework, just check the `ReloadPrompt` component on the corresponding framework examples folder and update it with the i18n library you0re using.
