### ISSUE TITLE
Jest unit test cannot find module 'virtual:pwa-register/vue'

### ISSUE THREAD

**Issue by palmer-rm** [antfu/vite-plugin-pwa#238]
Have integrated a reload prompt as per docs: https://vite-plugin-pwa.netlify.app/frameworks/vue.html#prompt-for-update

```
<script setup lang="ts">
import { useRegisterSW } from 'virtual:pwa-register/vue';
const { offlineReady, needRefresh, updateServiceWorker } = useRegisterSW();
</script>

<template>
  <ButtonField
    v-if="offlineReady || needRefresh"
    text="New content available. Click to refresh"
    @click="updateServiceWorker()"
  />
</template>
```

Works fine, however any unit tests for the component (using vue-test-utils) fail due to:

`Cannot find module 'virtual:pwa-register/vue' from...`

Not getting any IDE errors and the module _is_ imported okay and works fine.

**Comment by userquin** [comment]
@palmer-rm `jest` is not aware about virtual modules, check `vitest` instead.

**Comment by palmer-rm** [comment]
Thanks for the suggestion userquin, but not an option I'm afraid.

Managed to mock the module by doing:

```
jest.mock('virtual:pwa-register/vue', () => ({
  default: ()=> jest.fn()
}), { virtual: true });
wrapper = mount(App, options);
```

which works fine.

**Comment by doutatsu** [comment]
Nice and simple solution @palmer-rm, thanks!

**Comment by doutatsu** [comment]
Can you share a snippet of your code? Trying to mock it the way you did, but failing so far

**Comment by userquin** [comment]
@palmer-rm if you share the snippet we can include on the docs on FAQ section

**Comment by doutatsu** [comment]
I've made some progress with this, as it was the order of dependencies that messed up the mock... But with:
```js
jest.mock('virtual:pwa-register/vue', () => ({
  useRegisterSW: () => jest.fn(),
}), { virtual: true });
```

I am now getting this error: `TypeError: (0 , _vue.useRegisterSW) is not a function`.

Here's my call:
```js
<script setup>
  import { useRegisterSW } from 'virtual:pwa-register/vue';

  const intervalMS = 3600000; // 1 hour in milliseconds

  // eslint-disable-next-line no-unused-vars
  const { needRefresh, updateServiceWorker } = useRegisterSW({
    immediate: true,
    onRegistered(r) {
      // eslint-disable-next-line no-unused-expressions
      r && setInterval(() => { r.update(); }, intervalMS);
    },
  });

  // eslint-disable-next-line no-unused-vars
  const close = async () => {
    needRefresh.value = false;
  };
</script>
```

**Comment by doutatsu** [comment]
Looking further into it - `useRegisterSW` is indeed `undefined`... only when invoked in the `setup`, but if imported normally inside the `script`, there are no issues. I have no idea why it behaves like this

**Comment by ltaylor2607** [comment]
@doutatsu Not sure if you've managed to fix this yet, but I got it working by doing the following:
```
jest.mock('virtual:pwa-register/vue', () => ({
  default: ()=> jest.fn(),
  useRegisterSW: jest.fn(() => ({
    offlineReady: { value: false },
    needRefresh: { value: false },
    updateServiceWorker: jest.fn(),
  })),
}), { virtual: true });
```

The values returned inside useRegisterSW were the ones I was using, this may be different depending on which properties you use.
