### ISSUE TITLE
Allow manually registering

### ISSUE THREAD

**Issue by cypressious** [antfu/vite-plugin-pwa#24]
By default, the following script is added to the index.html

```html
<script>if('serviceWorker' in navigator) {window.addEventListener('load', () => {navigator.serviceWorker.register('/service-worker.js', { scope: '/' })})}</script>
```

If I specify `inlineRegister: false`, I'll get

```html
<script src="/registerSW.js"></script>
```

I don't see a way how I can control the registration of the service worker myself.

Please add an option to leave out the registration code.

**Comment by josepot** [comment]
> I don't see a way how I can control the registration of the service worker myself.

I guess that in the `registerSW.js` file you could have your own logic, e.g:

```js
if ('serviceWorker' in navigator) {
  window.addEventListener("load", registerServiceWorker)
}

function registerServiceWorker() {
  nvaigator.register(`${import.meta.env.BASE_URL}/sw.js`)
    .then(registration => {
      // Whatever you want to do
    })
}
```

What I don't know yet is how to get vite to compile that ^^ file... :thinking: (I'm a noob, today is my first day using vite and I'm also trying to figure these things out :sweat_smile: )

**Comment by antfu** [comment]
In v0.4.8, with `{ inlineRegister: false }`, you can put your custom `registerSW.js` under your public folder.

**Comment by cypressious** [comment]
I appreciate the quick fix, but I believe it's not enough in my scenario.

In my registration code, I need to import other parts of my application, register push notifications and so on. It would be best, to be able to not generate anything in the plugin and let me handle everything myself.

**Comment by josepot** [comment]
I agree with @cypressious 100%. In my case, I need to access different parts of my app in order to determine whether it's safe to skip the waiting phase of the newly installed SW... So, I much rather having the registration logic to happen from the main script of my app.

**Comment by antfu** [comment]
`{ injectRegister: null }` will do now in v0.5.0
