### ISSUE TITLE
path does not match       

### ISSUE THREAD

**Issue by kangdy** [antfu/vite-plugin-pwa#241]
How can I solve this problem, the cache path is inconsistent with the request path, causing the cache to fail

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/20158466/157613065-a4ca8891-f26b-43aa-912c-6ed9e9b8a20b.png">

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/20158466/157613242-453173c5-16df-4233-87f0-8749b3f4ac60.png">

**Comment by kangdy** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/20158466/157620862-9309b5d6-8c2b-4980-9cce-b29c89d244fd.png">

**Comment by userquin** [comment]
@kangdy what're your `vite.base` and pwa plugin `scope` and `base` options?

**Comment by kangdy** [comment]
> 

<img width="264" alt="image" src="https://user-images.githubusercontent.com/20158466/157656961-c116a127-91c4-4858-975c-93c3f44878cb.png">
vite.base: '//awp-assets.sankuai.com/key/slug/'

**Comment by kangdy** [comment]
> @kangdy what're your `vite.base` and pwa plugin `scope` and `base` options?



> @kangdy what're your `vite.base` and pwa plugin `scope` and `base` options?

My project static resources are deployed in another domain name, such as:
Static assets: assets.sankuai.com. Project access address http://wanxiang.data.st.sankuai.com/vinci/#/ or http://wanxiang.data.st.sankuai.com/udf/#/. Nginx will forward static resources, thank you.

**Comment by userquin** [comment]
@kangdy try adding on plugin `base: 'http://wanxiang.data.st.sankuai.com/vinci/#/` and `scope: '/vinci/#/'`, you also need to switch to `https`, the pwa will not work using `http`

**Comment by kangdy** [comment]
> 

Configured as you suggested, but still no success
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/20158466/157670167-28845e65-10aa-4066-bdd2-5bdc4d1a8439.png">
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/20158466/157670267-d76108cd-ba74-4161-bcee-7e14c981941f.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/20158466/157670295-1311cdcc-29bc-478c-bb17-4380daa88df5.png">

**Comment by userquin** [comment]
@kangdy https://vite-plugin-pwa.netlify.app/deployment/nginx.html

**Comment by userquin** [comment]
@kangdy feel free to open a new issue if the problem persists
