### ISSUE TITLE
The plugin is considering sitemap.xml & /dashboard as the main website

### ISSUE THREAD

**Issue by deounix** [antfu/vite-plugin-pwa#245]
When activating the PWA on my website it always redirects the domain.com/sitemap.xml & domain.com/dashboard to the 404 page

I did the same configuration as you do in the react-router example.

When I do (unregister for the workbox) the URL works. then when I'm visiting my main URL (domain.com) then it always redirects me to the 404 page

Note: I already did an alias in Nginx so it isn't related to the web server am 100% sure. everything works without the PWA what am doing wrong?

**Comment by deounix** [comment]
Is there any way in the configuration to exclude URLs from caching?
eg:

routes: ["/sitemap.xml", "/dashboard"] # these routes don't belong to u so don't listen or handle them 🤔

**Comment by userquin** [comment]
@deounix check this https://github.com/antfu/vite-plugin-pwa/issues/218#issuecomment-1024580718

**Comment by deounix** [comment]
@userquin Finally, it works now. Thank you.
