### ISSUE TITLE
How to progressively upload all app modules with dynamic modules, thanks to service workers ?

### ISSUE THREAD

**Issue by Aarbel** [antfu/vite-plugin-pwa#250]
Hi all,

I use dynamically imported modules in my app.

Just after the first connexion, when the network is not used, i want my users to upload all the modules that they will need in my app to optimise loading time of later navigations. 

Is there a way to do that with services workers and this lib ?

Thanks a lot !

**Comment by userquin** [comment]
@Aarbel the pwa sw will download all assets from your app on background, the dynamic imports will be resolved from the sw precache once the sw is installed (downloaded assets and included on the `Cache Storage`):

![imagen](https://user-images.githubusercontent.com/6311119/159898937-f824ad5d-bee0-4693-8587-79c9c444a068.png)

You can go to the docs and check the network tab on dev tools, you will see sw downloading all the assets on the app:

https://streamable.com/kfirb5
