### ISSUE TITLE
Offline support not working - "Web app manifest or service worker do not meet the installability requirements"

### ISSUE THREAD

**Issue by CaptainYouz** [antfu/vite-plugin-pwa#252]
Hi!
I recently started a pwa project using vite, vue and vite-plugin-pwa. I noticed then that my PWA didn't get offline support, so i started investigating. I didn't find anything strange, and the manifest, icons, html meta etc looked fine, but in lighthouse, under the installable section, i got this error `Web app manifest or service worker do not meet the installability requirements`

So, I created a minimum blank Vite project, and just added Vue and vite-plugin-pwa.

1- Reading the description of the plugin, i had assume first that, just by adding the plugin, we should get offline support by default. For me, i didn't. But reading the doc, i [saw this section](https://vite-plugin-pwa.netlify.app/guide/generate.html) and then added the manifest description, icons etc. Still, it didn't worked, and i keep having the same lighthouse error. (i also had this error under PWA Optimized: `Does not register a service worket that controls page and start_url`, so i added `start_url: '/'` to my manifest, and also tried with `start_url: '.'`, but even with both, it didn't work)

2- To compare with an existant project that use this plugin, i git cloned [vitesse repo](https://github.com/antfu/vitesse) from @antfu, pnpm installed everything, build the project and preview it. Everything worked as expected, service worker was recognized and installed, lighthouse was happy. (and no `start_url` in the manifest)

3- SO, i decided to take the exact same manifest config, public assets (favico & co), and index.html that the vitesse repo, and put it on my repo with the same version of vue, vite and plugin packages. The only change was on the index.html, since i don't use typescript i had to change `src="/src/main.ts"` to `src="/src/main.js"`. 
But, even with that, it is not working and i keep having the same error. I looked up on the vitesse repo, i didn't find anything different, any hidden config or else. I tried also to add the `start_url` param in the manifest, but still didn't work.

Here is the link to the repo: https://github.com/CaptainYouz/blank-test-default-offline-pwa
You can find in the first commit the step one (initial blank app with no config) and in the third commit the step 3 (copy of vitesse config)

Here is the screenshot of lighthouse error i keep having
<img width="1277" alt="Screenshot 2022-04-01 at 09 44 19" src="https://user-images.githubusercontent.com/2973285/161227437-3a2b3c31-0ec2-442a-9692-5c15e10044bb.png">

**Comment by userquin** [comment]
@CaptainYouz you should import the `virtual` module and call `registerSW` on the main entry:
```ts
// main.js
import { registerSW } from 'virtual:pwa-register'

registerSW({ immediate: true })
```

**Comment by CaptainYouz** [comment]
thanks 👍🏼 
by adding this and `pnpm i -D workbox-window` everything worked as expected.
Is it planned to be added to the doc?

**Comment by userquin** [comment]
uhhm, what's the error? maybe we can add it to the FAQ entry, PR welcome
