### ISSUE TITLE
Cannot make the plugin work in conjunction with vite-plugin-ssr

### ISSUE THREAD

**Issue by robotpapier** [antfu/vite-plugin-pwa#254]
Hi,
could someone succeded in making both work?
I had to manually add the link in the html head to the manifest but the service worker is not present even tought sw.js is preset.

**Comment by userquin** [comment]
@robotpapier can you provide a minimal repro?

**Comment by robotpapier** [comment]
Hi,
ok I forgot add registerSW.js generated by the plugin so it can register the SW.
now it is working!

`
const documentHtml = escapeInject`<!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <link rel="icon" href="${logoUrl}" />
        <link rel="manifest" href="/manifest.webmanifest">
        <script src="registerSW.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="${desc}" />
        <title>${title}</title>
      </head>
      <body>
        <div id="app">${stream}</div>
      </body>
    </html>`

    return {
      documentHtml,
      pageContext: {
        // We can add some `pageContext` here, which is useful if we want to do page redirection https://vite-plugin-ssr.com/page-redirection
      },
    }`

So in SSR mode with vite-plugin-ssr, we have to manually add manifest.webmanifest and registerSW.js in  _default.page.server.ts
