### ISSUE TITLE
Update for React 18

### ISSUE THREAD

**Issue by uipoet** [antfu/vite-plugin-pwa#257]
React 18 no longer provides exports with the `.js` extension.

Temporary workaround until `vite-plugin-pwa` is fixed:

```typescript
export default defineConfig({
  resolve: {
    alias: {
      "react/jsx-dev-runtime.js": resolve(
        __dirname,
        "node_modules/react/jsx-dev-runtime.js"
      ),
      "react/jsx-runtime.js": resolve(
        __dirname,
        "node_modules/react/jsx-runtime.js"
      ),
    },
  },
});
```

**Comment by userquin** [comment]
@uipoet what's the error? I'm testing with react 18 on `react-router` and it seems to work

**Comment by uipoet** [comment]
You opt-in to React 18 by rendering with `createRoot`, imported from `react-dom/client`.

There were several releases to various dependencies since I opened this issue. I'll update and try rerunning without the above workaround to see if the issue persists.

**Comment by uipoet** [comment]
Confirmed the workaround is no longer needed. Apologies if this was an upstream issue and not a bug with `vite-plugin-pwa` itself.
