### ISSUE TITLE
[Q]: How can I "activate" PWA in Dev Server 🤨

### ISSUE THREAD

**Issue by domsen123** [antfu/vite-plugin-pwa#26]
Hi,

is it possible to generate the manifest and sw.js during dev?

Cheerz

**Comment by antfu** [comment]
Can you explain a bit about the reason why you want to do this?

**Comment by domsen123** [comment]
for testing :)

right now I have some struggle with the caching... 
I am using firebase as hosting... if I deploy a new build to firebase hosting, some pages are not updating... 

So I was wondering, If I can activate the PWA in my local dev env to check everything and I dont have to build/deploy all the time to staging env.

furthermore: how I can extend the sw.js? I need to add some logic...

I dont get it

**Comment by userquin** [comment]
Just build the project and then install `node-static` and include the script at bottom of https://github.com/antfu/vite-plugin-pwa/issues/23#issuecomment-776749841

You will need to create an SSL certificate...

**Comment by userquin** [comment]
you see this entry, to test build over http:
https://stackoverflow.com/a/53388534/385997

**Comment by antfu** [comment]
`dev` and `build` are different processes in Vite (the implements are different, so there are many misalignments). I think debugging PWA in dev mode will make it even harder to debug. I'd suggest using build outputs to serve locally as @userquin pointed out.
