### ISSUE TITLE
Manifest / Service Worker in subdirectory

### ISSUE THREAD

**Issue by seriousManual** [antfu/vite-plugin-pwa#263]
I have a project with the following structure:

```
root
    subProject1
        index.html
        src
            index.tx
    subProject2
        index.html
        src
            index.ts
    subProject3
        index.html
        src
            index.ts
 ```

Vite is configured so that it uses each index.html file as input files:
```js
export default defineConfig({
    root: './frontend',
    build: {
        rollupOptions: {
            input: {
                sub1: resolve(__dirname, 'frontend/subProject1/index.thml'),
                sub2: resolve(__dirname, 'frontend/subProject2/index.thml'),
                sub3: resolve(__dirname, 'frontend/subProject3/index.thml')
            }
        }
    }
})
```

This works fine, vite is generating individual bundles (and common chunks) ...
Now I'm trying to use `vite-plugin-pwa` to generate a service worker / manifest *only* for subProject1.

But the plugin always puts the manifest and serviceworker in the root ('/frontend'), also it is incorporating any asset that has been generated, not just that of subProject1.

I tried using the `scope` and `base` config options, but those did not lead to the desired outcome.

Maybe anybody has seen this issue already?

**Comment by userquin** [comment]
@seriousManual can you provide a minimal repro?

**Comment by seriousManual** [comment]
Absolutely!

Here is the setup, stripped down to the absolute minimum:
https://github.com/seriousManual/vite-pwa-muilti-app

In the vite config, a couple of "sub apps" are registered:
https://github.com/seriousManual/vite-pwa-muilti-app/blob/master/vite.config.js#L18

These are setup in the frontend folder:
https://github.com/seriousManual/vite-pwa-muilti-app/tree/master/frontend

When I'm running a build now, the generated service worker sits in the root of the build directory, which is somewhat expected:
https://github.com/seriousManual/vite-pwa-muilti-app/tree/master/build/frontend

But what I'm trying to achieve is a serviceworker setup that only relates to one of the sub apps (e.g. also sits in the respective directory). Currently the generated service worker refers to all assets from all sub apps, which is not the desired outcome.

**Comment by userquin** [comment]
@seriousManual be patient, I'm too busy at work...

**Comment by userquin** [comment]
@seriousManual I have it working, but you need to keep in mind that all pwa stuff (all sw precache entries: pwa icons and sw) must be served from `/sub1/` path, it acts as the scope for the sw.

You can check it here https://github.com/userquin/vite-pwa-muilti-app:
- check scripts folder, contains the pwa configuration and the script to run after build
- the build script also copy the pwa icons and moves the `manifest.webanifiest` file from `build/frontend` folder to `build/frontend/sub1` folder
- deleted `package-lock.json` file to fix `ejs` vulnerability (`npm install` fix it)
- added `https-localhost` and a few dev dependencies to allow run the TypeScript module to rebuild the pwa
- added `https` script to build the app and serve it under https, just open https://localhost/sub1/ once you run `npm run https`: `https-localhost` will ask you to create a TLS certificate and install it on your local

Some screen shots.

![imagen](https://user-images.githubusercontent.com/6311119/164323534-e75aaae6-755e-4ee9-adbc-df9037554fb0.png)

![imagen](https://user-images.githubusercontent.com/6311119/164323664-0f9ecf19-21a1-430c-b843-f2d1190853f1.png)

![imagen](https://user-images.githubusercontent.com/6311119/164323751-80cc6f21-3883-4515-9635-9f57b659e29c.png)

**Comment by seriousManual** [comment]
Hey @userquin ,
thanks a lot for looking into this, amazing work!

It seems like these are a lot of hoops to jump through 🤔

One issue I have:
in the other sub apps (sub2 and sub3) the webmanifest from sub1 is now referenced:
![image](https://user-images.githubusercontent.com/1330022/164404740-f89a6211-a28f-4c05-ae8c-3c5eb904278a.png)

**Comment by userquin** [comment]
I need to review the code, since on offline will not work, the sub1 asset is one level up and will not be included on the sw precache.

**Comment by seriousManual** [comment]
Hi Joaquín,
please do not sink too much time and effort into this! 
It looks like the plugin is not meant to be used in this way, it seems a lot of additional work is neccessary and I don't want to burden you with this edge case.

**Comment by seriousManual** [comment]
Thanks für your work!
