### ISSUE TITLE
The start_url did respond, but not via a service worker.

### ISSUE THREAD

**Issue by diogofalken** [antfu/vite-plugin-pwa#27]
I am using vite PWA plugin and I got it working but it's giving me an error in lighthouse related to `start_url`.

![image](https://user-images.githubusercontent.com/39312512/108603052-7aaab680-739d-11eb-9f05-290341a9476c.png)

I left workbox configs untouched in `vite.config.js`, so I wonder what could it be.

The repo where it is being developed is [repo](https://github.com/diogofalken/linktree) and [live version](https://links.diogomcosta.com/).

Thanks in advance.

**Comment by hannoeru** [comment]
Duplicated of #20

**Comment by diogofalken** [comment]
> Duplicated of #20

Thank you and sorry for the duplicated issue
