### ISSUE TITLE
Unable to parse HTML; URI malformed with Python injection

### ISSUE THREAD

**Issue by Fleeck** [antfu/vite-plugin-pwa#271]
Hi, we generate manifest based on user id in runtime. But the plugin won't run the build, giving me the error above. Any solution to this?

Code in `index.html`
` <link
      rel="manifest"
      href="{% url 'wb_manifest_json' token_id=token_id %}"
      crossorigin="use-credentials"
    />`

**Comment by userquin** [comment]
@Fleeck can you provide the full error?

**Comment by Fleeck** [comment]
Sure @userquin 
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/12518334/164432493-900552ac-a13d-41d3-8e8a-fe5f155f2ae8.png">

**Comment by userquin** [comment]
from the stacktrace it seems the problem is on vite, not in the plugin, maybe you may ask on vite discord server

**Comment by Fleeck** [comment]
You are correct. If I comment out the plugin it throws via `[vite:build-html]`
