### ISSUE TITLE
Ignore manifest creation

### ISSUE THREAD

**Issue by Fleeck** [antfu/vite-plugin-pwa#275]
Hi, I generate `manifest.json` dynamically hence I don't need it in the build. Is there an option to ignore it? Thanks.

A snippet of manifest generation for understanding:
```
// fetch data, then fetch manifest
const link = document.createElement('link')
link.rel = 'manifest'
link.href = `${import.meta.env.VITE_API_URL}/wb/manifest/json/${store.state.guideToken}/`
document.querySelector('head').appendChild(link)
```

**Comment by userquin** [comment]
@Fleeck just configure `manifest: false`

**Comment by Fleeck** [comment]
Thanks, it works!
