### ISSUE TITLE
install prompt

### ISSUE THREAD

**Issue by hamedg68** [antfu/vite-plugin-pwa#279]
hi. how can i customize install prompt?

**Comment by userquin** [comment]
You can check the examples entry on docs and the examples folder here

**Comment by hamedg68** [comment]
shoud I use window.addEventListener('beforeinstallprompt', (e) => {    }) for having install propmt modal?

**Comment by hamedg68** [comment]
> shoud I use window.addEventListener('beforeinstallprompt', (e) => { }) for having install propmt modal?

**Comment by hamedg68** [comment]
> 



> > shoud I use window.addEventListener('beforeinstallprompt', (e) => { }) for having install propmt modal?

**Comment by userquin** [comment]
@hamedg68 I don't use it, but you can, beware, not all browsers support it: https://web.dev/learn/pwa/installation-prompt (check the caution here https://web.dev/learn/pwa/installation-prompt/#the-beforeinstallprompt-event)
