### ISSUE TITLE
does not work with imported wasm

### ISSUE THREAD

**Issue by nstringham** [antfu/vite-plugin-pwa#308]
when I import a wasm file it does not get added to the service worker

here is a minimum to reproduce example: https://github.com/nstringham/vite-pwa-wasm-min-to-reproduce

**Comment by userquin** [comment]
@nstringham add `workbox` entry on `pwa plugin options` with this option `globPatterns: ['**/*.{js,html,wasm}']`:
```
VitePWA({
  injectRegister: 'inline',
  workbox: {
    globPatterns: ['**/*.{js,html,wasm}']
  }
})

**Comment by nstringham** [comment]
thanks that worked
