### ISSUE TITLE
Automatically add manifest icons to build dir

### ISSUE THREAD

**Issue by leobel96** [antfu/vite-plugin-pwa#31]
Hi, I don't know if it's a bug or a feature request but it would be fantastic if the images listed in the `icons[]` array of the manifest would be automatically added to the build dir (`dist/assets` by default).

**Comment by userquin** [comment]
@leobel96 can you take a look at #53?. Is what you want (the plugin, when PR #62 merged, will include the icons on the service worker precache)? If not, then this plugin cannot build what you don't want to build on your project. If you want the manifest icons go to assets directory, move them to the assets directory on your project.

**Comment by leobel96** [comment]
@userquin Yeah it works. Thanks!

**Comment by userquin** [comment]
@leobel96 so, this issue is related to move icons to assets directory on build or just include them on service worker  precache ?

**Comment by leobel96** [comment]
It's related to the precache
