### ISSUE TITLE
Exclude paths from pwa

### ISSUE THREAD

**Issue by proohit** [antfu/vite-plugin-pwa#310]
First of all thanks for this wonderful library!

Is it possible to exclude specific paths from pwa? 

Suppose we have a backend serving our pwa but also some other web app (I.e. api docs). The pwa is served at root and web app at /api/docs. Now for the pwa, it is always configured at root, including sub paths. When accessing /api/docs, it gets first handled by pwa. It is working without pwa. Is it possible to exclude some paths? 

Thanks in advance

**Comment by userquin** [comment]
@proohit https://github.com/antfu/vite-plugin-pwa/issues/218#issuecomment-1024580718

read the issue for context
