### ISSUE TITLE
Have to add "web app capable" tags manually

### ISSUE THREAD

**Issue by tobiasfeil** [antfu/vite-plugin-pwa#312]
I've just tried setting up a plain project: 
```bash
$ npm --version
8.12.2
$ npm create vite@latest
(choose vanilla-ts, name "test")
cd test
npm i
npm i vite-plugin-pwa -D
```
after which I followed the steps described [here](https://vite-plugin-pwa.netlify.app/guide/#setup) and [here](https://vite-plugin-pwa.netlify.app/guide/generate.html#generate-service-worker)

Now if I start the app locally, serve it over the network, open it on my phone in Chrome, add it to my homescreen and then open the app I added to the home screen, it just opens the page in chrome (meaning e. g. that the address bar is visible). It doesn't treat it like a pwa where the address bar is not visible when you open it from your home screen.

It is only after I add 
```
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
```
to the app's `index.html` that it properly works like a pwa and I don't see the address bar.

Is this intended?

**Comment by userquin** [comment]
@tobiasfeil are you serving your app on local using https? can you check if the docs of this repo is showing the install button on the address bar (without the entries you added to the entry point)?

The install button is the first on the right side in the address bar:
![imagen](https://user-images.githubusercontent.com/6311119/175547600-8c5190a1-b90a-4050-9de5-dca596fccde9.png)

**Comment by userquin** [comment]
on Android 
![Screenshot_20220624-154340_Chrome](https://user-images.githubusercontent.com/6311119/175548671-cd6d602b-0518-4731-822d-affe7823aeb6.jpg)

**Comment by userquin** [comment]
@tobiasfeil if only works adding those entries, I can add them to the docs to support macos/ios.

**Comment by tobiasfeil** [comment]
@userquin thank you so much for the quick answer. I've tried all your suggestions, dug through the examples and done much trial and error for about 3 hours now and I've found the answer: **It doesn't work when I run it with `npm run dev`, only if I build first and then serve e. g. with the `serve` command.** I think it would be helpful to include this somewhere in the docs since it cost me quite some time.

For further information, the `scripts` section in my `package.json` looks like this:
```json
"scripts": {
    "build": "vite build",
    "dev": "vite",
    "preview": "vite preview",
    "start": "npm run build && npm run serve",
    "serve": "serve dist"
  }
``` 

With `npm run dev`, it doesn't get served like a proper pwa (can't install on desktop and still shows the address bar on mobile), while it works with `npm run start`.

**Comment by userquin** [comment]
@tobiasfeil you shouldn't use that meta tags, check the warning here: https://web.dev/learn/pwa/web-app-manifest/#designing-your-pwa-experience

You can use the `devOptions` with the latest version `0.12.0`, a minimal version installing the pwa on dev (only the entry point will be registered in the sw precache manifest), but the `manifest` will not be generated, we've a PR ready for next patch release. The `devOptions` is for debugging the custom sw using `injectManifest` on complex scenarios and so the pwa capabilities can be tested.

On development it makes no sense to add a sw that will cache everything...

**Comment by tobiasfeil** [comment]
Alright, thank you very much!
