### ISSUE TITLE
Images from assets is not loading in production env

### ISSUE THREAD

**Issue by Juliapp** [antfu/vite-plugin-pwa#313]
I'm having some issues to make the assets (.svg, .png, .jpeg) work. In local environment it doesn't seems to have any problem but in the vercel machine everything breaks down

Even tho the request returns 200
![image](https://user-images.githubusercontent.com/34479004/175758498-d9d2a99d-1549-428f-81d6-469bd7fb03c7.png)
![image](https://user-images.githubusercontent.com/34479004/175758372-dcd3fc4a-5c6d-4fcc-ab75-420011833ad7.png)

I already tried to follow the docs, so my config file is currently this: 
```
plugins: [
  react(),
  VitePWA({
    mode: "development",
    includeAssets: ["favicon.svg", "favicon.ico", "assets/*"],
    manifest: {
      name: "App name",
      short_name: "App short name",
      description: "App description",
    },
    workbox: {
      globPatterns: ["**/*.{js,css,html,ico,png,svg,webmanifest}"],
    },
  }),
],
```

> Win 10
> Yarn v1.22.15
> NodeJS v16.14.2
> Vite 2.9.7
> vite-plugin-pwa 0.12.0
> typescript 4.6.3

PS.: I'm changing the project to be a pwa from a regular one

**Comment by userquin** [comment]
@Juliapp can you provide a screenshot of the dist folder once you run the build script (remove the assets folder from `includeAssets` array)?

**Comment by Juliapp** [comment]
> @Juliapp can you provide a screenshot of the dist folder once you run the build script (remove the assets folder from `includeAssets` array)?

after removing include assets 
![image](https://user-images.githubusercontent.com/34479004/175772777-ac8f029d-44f4-4c6b-a0b5-a35d9f919099.png)

**Comment by Juliapp** [comment]
As the description I reported before:
![image](https://user-images.githubusercontent.com/34479004/175773094-e1ecc197-8228-4c0c-bc85-3f1ca1692a45.png)

after remove include assets array:
![image](https://user-images.githubusercontent.com/34479004/175772936-664a87a7-dd72-43b7-b989-aee7adecd3b4.png)

**Comment by userquin** [comment]
@Juliapp it seems your assets folder is not inside `src`, `Vite` expects to be there; or maybe you're not using the resources inside the assets folder, and so `Vite` will not use them.

If the assets folder is under src, just try to move the resources inside it to the `public` folder (should be under project root), `Vite` will just copy all entries inside `public` folder to the `dist` folder (no matter if being used or not in the code).

**Comment by Juliapp** [comment]
It works. Somehow vercel was already linking the images even without the public so I wasn't imagining  
Thank you so much

**Comment by userquin** [comment]
@Juliapp so, this issue can be closed?
