### ISSUE TITLE
Svelte Service worker never registers.

### ISSUE THREAD

**Issue by MikeGulik** [antfu/vite-plugin-pwa#317]
Trying to follow the docs included, workbox instructions, workbox cli, and a handful of online blogs; it seems that the default service worker never installs.  

[Workbox CLI](https://developer.chrome.com/docs/workbox/modules/workbox-cli/)
[Blog1](https://blog.unixfy.net/offline-first-pwa-with-svelte-vite/)
[Blog2](https://blog.unixfy.net/offline-first-pwa-with-svelte-vite/)

vite config
![](https://user-images.githubusercontent.com/100597264/176694824-badcc877-bfd2-40bb-a0a5-06daede02c56.png)

logs 
![here we can see the logs placed](https://user-images.githubusercontent.com/100597264/176693873-52ca6c5d-0e90-4a72-b979-c6b2b02a160c.png)

service worker is in dist
![](https://user-images.githubusercontent.com/100597264/176694949-dc4270c8-dc92-4739-a52f-fd3547879cc2.png)

logs being hit, zero service worker installed
![](https://user-images.githubusercontent.com/100597264/176694398-f5bad118-54e9-4b4c-8690-d81f2316ef75.png)

This was done in a blank svelte app using vite.
[Here is the github repo to the project](https://github.com/MikeGulik/vite-test)

**Comment by userquin** [comment]
@MikeGulik the `vite-plugin-pwa` is not configured in your Vite config file

**Comment by userquin** [comment]
update the repo

**Comment by userquin** [comment]
You don't need to use the virtual module, just configure `registerType: 'autoUpdate'` and `injectRegister: 'inline'` and you're done, check my fork of your repo here https://github.com/userquin/vite-pwa-plugin-317:
```ts
  injectRegister: 'inline',
  registerType: 'autoUpdate',
  mode: 'development',
  includeAssets: ['favicon.svg'],
  workbox: {
    clientsClaim: true, // <== YOU WILL CAN REMOVE THIS OPTION ON 0.12.2 (rn 0.12.1)
    skipWaiting: true, // <== YOU WILL CAN REMOVE THIS OPTION ON 0.12.2 (rn 0.12.1)
  },
```

If you want to use the virtual, just remove previous injectRegister: 'inline'` option and configure this on the main module or `App.svelte`:
```ts
import { registerSW } from "virtual:pwa-register";

registerSW();
```

![imagen](https://user-images.githubusercontent.com/6311119/176706507-aacd6ce8-9bcb-4f74-8ace-847d090c8918.png)

**Comment by userquin** [comment]
upps, wrong button

**Comment by MikeGulik** [comment]
@userquin How is this working for you, and not for me? 

I pulled your changes, remove node-modules, built and ran using pnpm. No service worker. Removed inline, uncommented registerSW and import, still no service worker showing up.

**Comment by userquin** [comment]
@MikeGulik I don't know, can you test it on private window? Check in the source code the entry point has a script registering the sw.

**Comment by userquin** [comment]
@MikeGulik are you testing on dev? I've it working running `pnpm run build && pnpm run preview`, I don't test the dev.

**Comment by MikeGulik** [comment]
@userquin I was running it in dev. This worked. I am so happy. Thank you so, so much.

**Comment by userquin** [comment]
@MikeGulik I'm checking it rn...

**Comment by userquin** [comment]
@MikeGulik the `enabled` option is always false, you just copy it from the examples??, set it to `enabled: true`, also update to `0.12.2`  and use the virtual module, I'm fixing it, but I don't know when it will be released...

![imagen](https://user-images.githubusercontent.com/6311119/176735455-d3fd93e4-fc10-47f4-897c-66b031c00b46.png)

**Comment by userquin** [comment]
@MikeGulik check last commit on my fork

**Comment by MikeGulik** [comment]
@userquin Yeup, copied it from the examples. Totally forgot about that option. However, this did the trick thank you
