### ISSUE TITLE
Safari compatibility

### ISSUE THREAD

**Issue by francmarin98** [antfu/vite-plugin-pwa#330]
Friends how are you, you know I have a query. How compatible is this plugin with Safari?

Is it possible to use push notifications and faceID or fingerprint in Safari through this plugin?

**Comment by userquin** [comment]
@francmarin98 push notification not yet, fingerprint I don't know, just check this entry: https://web.dev/learn/pwa/capabilities/

**Comment by userquin** [comment]
@francmarin98 about the compatibility, it should be 99% compatible. It depends also on the PWA capabilities you're including: Safari have some weird errors when used on some environments, but should work (of course, if a feature is not supported we cannot do anything here).

You can check this repo for some cool features (Jeff: workbox): https://github.com/jeffposnick/yt-playlist-notifier
