### ISSUE TITLE
Vite 3.0.0

### ISSUE THREAD

**Issue by matrunchyk** [antfu/vite-plugin-pwa#336]
Hi, I'm just wondering about vite@3.0.0 support, after upgrade I cannot use this plugin anymore:

![image](https://user-images.githubusercontent.com/2089828/178845038-662f3332-8f78-46fc-8d46-1b237b5098d8.png)

**Comment by userquin** [comment]
@matrunchyk we're working on it... just released today, do you have a repo where we can test?

**Comment by matrunchyk** [comment]
Great news. Unfortunately, I don't have a public repo...

Thank you for your hard work! <3

**Comment by userquin** [comment]
@matrunchyk the error when installing deps or running dev? can you put here the raw log?

**Comment by matrunchyk** [comment]
When installing, will attach the log in a few moments

**Comment by matrunchyk** [comment]
I very apologise @userquin, now it installs correctly with no issues, vite starts successfully. I will check how it works after deploy.

Thanks again!

**Comment by userquin** [comment]
@matrunchyk I've read the logs and it seemed like a dependency installation problem...

**Comment by matrunchyk** [comment]
Yeah I think it was because of another package which still not on vite@3 (like `vite-plugin-eslint` and `vite-plugin-html-config`)
