### ISSUE TITLE
Unable to find config options

### ISSUE THREAD

**Issue by SteveALee** [antfu/vite-plugin-pwa#338]
Sorry If I missed it but I cannot fond the reference for the various config options that can be passed to the plugin factory function. A few are distributed around the docs and examples, some code snippets in the docs include others. Some look like they are vite config options that might be passed through.

I'd expect to see then listed or linked to here:

https://vite-plugin-pwa.netlify.app/guide/#configuring-vite-plugin-pwa

**Comment by userquin** [comment]
@SteveALee the types are in the README file: https://github.com/antfu/vite-plugin-pwa#-full-config.

I will add a link to the types to the docs: https://github.com/antfu/vite-plugin-pwa/blob/main/src/types.ts

**Comment by userquin** [comment]
@SteveALee I'm adding a `PWA Build` application, check this PR https://github.com/antfu/vite-plugin-pwa/pull/331.

You can also check the preview in previous PR, the app is WIP, the generate button does nothing...

**Comment by SteveALee** [comment]
For now  I found the the list of names and default values here - https://github.com/antfu/vite-plugin-pwa/blob/main/src/options.ts#L40-L59

**Comment by SteveALee** [comment]
@userquin Oops, seems I needed to refresh the page before adding my comment - thanks

**Comment by SteveALee** [comment]
Adding a link is good idea for folks like me reading the docs on their phone not using an IDE with intellisense. :)

PS Using the vite vanilla template plus this plugin is super simple way to create a PWA - thank you and team.

**Comment by userquin** [comment]
@SteveALee are you asking for client (virtual modules) or plugin types? anyway, in the README page (at bottom) you have both links. 

I'll add both links to the docs.

**Comment by SteveALee** [comment]
@userquin 

I'm after all the options and values for the object passed to the plugin factory function `VitePWA` used in vite.congif.js

```javascript
import { VitePWA } from 'vite-plugin-pwa'
export default defineConfig({
  plugins: [
    VitePWA({ 
      registerType: 'autoUpdate',
      devOptions: {
        enabled: true
      }
    })
  ]
})
```

Nice little builder.
I used the vanilla vite template - no framework - and I notice neither docs or builder really address that choice.

**Comment by userquin** [comment]
@SteveALee check this repo: https://github.com/userquin/vite-plugin-pwa-vanillajs

**Comment by userquin** [comment]
@SteveALee added on FAQ, on the guide index and also in the frameworks index: check https://github.com/antfu/vite-plugin-pwa/pull/339

**Comment by SteveALee** [comment]
@userquin Looks good. Thank you!
