### ISSUE TITLE
How to pre-cache files on cdn

### ISSUE THREAD

**Issue by kangdy** [antfu/vite-plugin-pwa#343]

**Comment by userquin** [comment]
@kangdy beware using opaque responses, read this entry https://developer.chrome.com/docs/workbox/caching-resources-during-runtime/

You can use plugins instead building your own custom sw https://developer.chrome.com/docs/workbox/using-plugins/

**Comment by eagleoflqj** [comment]
In case anyone wants an answer for when your local files are the same with those on CDN, use `manifestTransforms` to rewrite local path to CDN URL instead of runtime caching.
e.g. https://github.com/LibreService/my_opencc/blob/d9e799a47640b2e06d8f866dc2f498d12fcaffce/vite.config.ts#L19
