### ISSUE TITLE
navigateFallbackDenylist is not respected in dev mode

### ISSUE THREAD

**Issue by brandonculverwork** [antfu/vite-plugin-pwa#346]
### Describe the bug

The navigateFallbackDenylist is not respected in dev mode. Dev injects the manifest file overriding anything set in the vite config by the user.

```
        workbox: {
          navigateFallbackDenylist: [/^\/someroute/],  <-- Does not work in dev mode
        },
```

### Reproduction

Look at service worker generated in dev mode

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 25.39 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 101.0
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@brandonculverwork we'll change that behavior in next release: https://github.com/antfu/vite-plugin-pwa/pull/335
