### ISSUE TITLE
Add github pages guide in docs

### ISSUE THREAD

**Issue by K1ssSh0t** [antfu/vite-plugin-pwa#348]
Could you add guide to deploy to github pages? 

I have tried [this](https://github.com/gitname/react-gh-pages) guide for github pages  but the end result is a blank page.

**Comment by userquin** [comment]
@K1ssSh0t can you provide the link to the deployed app?

**Comment by K1ssSh0t** [comment]
> @K1ssSh0t can you provide the link to the deployed app? 

https://k1sssh0t.github.io/prubea-pwa/

**Comment by userquin** [comment]
have you configured  `base: '/prubea-pwa/'` in vite config file? it seems the ghpages is not finding your app, just check the logs in dev tools (404 after a few minutes)
