### ISSUE TITLE
Create Vite 3 branch

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-pwa#357]
Things start moving fast, we need to update the plugin to Vite 3. We should create a vite3 branch once we merge all pending PR (excluding SvelteKit one).

VitePress integration PR can be merged once the docs ready: there is a small problem with TS with latest VitePress 1.0.0.alpha8 version (the plugins entry has changed again).

We can create the vite3 branch and then update it once we release/publish 0.12.4 version with all PR merged.

In a few days we'll have also Vite 3.1 with the object hooks and sequential support (Rollup 2.78): this is required to integrate the plugin with latest SvelteKit once moved to Vite 3.1 (kit): rigth now the only way is using scripts after kit build.

/cc @antfu

**Comment by userquin** [comment]
We need to discuss if we'll mantain Vite 2 (only bugs and security fixes) and Vite 3 versions (and the next incoming Vite 3.1).

**Comment by antfu** [comment]
What changes would be needed for Vite 3? I suppose it works today already? For 3.1 we will need a major bump with 3.1 only support.

**Comment by userquin** [comment]
> What changes would be needed for Vite 3? I suppose it works today already? For 3.1 we will need a major bump with 3.1 only support.

Some types in Vite 3 have changed, for example, plugins entry on UserConfig

**Comment by michealroberts** [comment]
Just wondering what the status is of this, is vite-plugin-pwa now Vite 3 compliant?

**Comment by michealroberts** [comment]
Just to give some feedback from my end => upgraded to version 0.12.7 has fixed an error I was seeing and can confirm that this plugin works nicely with Vite 3 👍

**Comment by userquin** [comment]
@michealroberts we are working in a new version of pwa plugin, there is a new PR to support new Vite 3.1.0. Once published a new version 0.13.0 (minor: breaking changes, will work only with Vite 3.1.0+), we'll include some integrations for SvelteKit and VitePress (initial, then Astro).

You can check a preview here https://github.com/userquin/pwa-sveltekit-vite (with local copy of #370), I need to merge a PR from Ben (kit team) in that repo and update kit to latest version: the `configureOptions` function will be provided by the kit integration and so you will just use this plugin with the pwa options.
