### ISSUE TITLE
Some lines of code make the build have an export default

### ISSUE THREAD

**Issue by Evertt** [antfu/vite-plugin-pwa#358]
### Describe the bug

I'm writing a TypeScript file that is agnostic about whether it's run inside a service worker or inside a browser. The goal is that is for some reason the service worker fails to load, the browser can then just import the file instead.

Now this *almost* works. Except that when I add some lines of code, and it seems pretty arbitrary which lines of code will do it, the final build of the service worker will have an `export default N()` at the end. And of course a service worker is not allowed to have an export.

For example, if my agnostic file contains these lines of code:

```ts
const channel = new BroadcastChannel('memCache-commands')
// I'll add a line of code here in the next bit...

async function handleMessage(event: ExtendableMessageEvent | EMEvent): Promise<MemCacheMessage | void | ""> {
 // ...
}
```

Then the final build is fine. It starts with:
```js
var commonjsGlobal=typeof globalThis!="undefined"?globalThis:typeof window!="undefined"?window:typeof global!="undefined"?global:typeof self!="undefined"?self:{}
```

And it doesn't end with an `export default`. But if I change those few lines of code and add one more line, like so:

```ts
const channel = new BroadcastChannel('memCache-commands')
channel.addEventListener("message", handleMessage)

async function handleMessage(event: ExtendableMessageEvent | EMEvent): Promise<MemCacheMessage | void | ""> {
 // ...
}
```

Then suddenly the final build of the service worker starts like this:

```js
var O=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports);var N=O((exports,module)=>{var commonjsGlobal=typeof globalThis!="undefined"?globalThis:typeof window!="undefined"?window:typeof global!="undefined"?global:typeof self!="undefined"?self:{}
```

And ends with:

```js
export default N();
```

This is not the only scenario where this happens. I've tried many variations to make this file environment agnostic and every time at the last few steps, it seems to break the final build. `npm run dev` still works fine btw, but that's because then it's building it as a module type instead of a classic type.

### Reproduction

Is my description above enough?

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 114.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 89.1.22.71
    Chrome: 104.0.5112.79
    Safari: 15.5
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

## edit

I'm actually not sure if this is an issue of this plugin, or of rollup...

**Comment by userquin** [comment]
@Evertt provide a minimal repro.

**Comment by userquin** [comment]
@Evertt the repro is using Vite 3

**Comment by Evertt** [comment]
@userquin as am I in my own project

**Comment by userquin** [comment]
@Evertt can you try removing the commonjs plugin in your pwa options? 

Copy/Paste this list: https://github.com/antfu/vite-plugin-pwa/blob/368542e6c1069f07f4d45969a948919765297258/src/constants.ts#L13 removing the commonjs, you should configure like this:
```ts
vitePlugins: [
  'alias',
  // 'commonjs', // <== just try removing this one
  'vite:resolve',
  'vite:esbuild',
  'replace',
  'vite:define',
  'rollup-plugin-dynamic-import-variables',
  'vite:esbuild-transpile',
  'vite:json',
  'vite:terser',
]
```

**Comment by userquin** [comment]
@Evertt the sw is built using a Rollup, you can check it here: https://github.com/antfu/vite-plugin-pwa/blob/main/src/modules.ts#L109

I don't know why sometimes is generating export default in your project.

**Comment by Evertt** [comment]
@userquin the vitePlugins thing didn't fix it, but it did give me the idea to replace some of the packages I'm using with other packages that are more esm-friendly. And that seems to have done the trick.

Thanks for thinking along with me. 🙏

**Comment by kgroat** [comment]
I know this issue is already closed, but for anyone else with the same issue, I was able to resolve this by adding the following to the `VitePWA` config:
```ts
VitePWA({
  // the rest of your config up here...

  injectManifest: {
    rollupFormat: 'iife'
  }
})
```

**Comment by kgroat** [comment]
For what it's worth, I also made a [minimal reproduction case](https://github.com/kgroat/Minimal-SW-ES-Repro).

**Comment by userquin** [comment]
Can you try adding it to vite optmizeDeps.include?
