### ISSUE TITLE
`registerSW.js` 404s in dev mode with `injectManifest` strategy

### ISSUE THREAD

**Issue by lhjt** [antfu/vite-plugin-pwa#359]
### What am I trying to do

I am trying to get the service worker to register in dev mode with `strategies = injectManifest` and `devOptions.enabled = true`

### What do I expect to happen

I expect the service worker to load correctly in dev mode.

### What happens instead

The service worker registration does not take place as `registerSW.js` cannot be found:

![image](https://user-images.githubusercontent.com/48422312/185787399-a8cc6869-2b82-45bd-9a01-7f334abf86b9.png)

Running `pnpm build` and then serving the production bundle works without issues, and the service worker successfully registers.

### Reproduction

https://github.com/lhjt/issue-repro

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.69 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome Canary: 107.0.5252.0
    Firefox Developer Edition: 103.0
    Safari: 16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@lhjt we need to update the `inline` and `registerSW.js` generation to include `type: module`, it is missing, only works using the pwa plugin virtual modules.

PR welcome ;)

**Comment by lhjt** [comment]
Thanks for the quick turnaround!

I see the issue; I haven't worked on vite plugins before, so I wouldn't even know how to approach this yet, but if I do get some time to look into it and get a functioning solution, I'll be sure to open a PR 😄

**Comment by userquin** [comment]
We need to change the html.ts module to add the type from devOptions on the sw registration and also the dev.ts plugin module to do the same on web socket ping/pong when register type is inline.

**Comment by lhjt** [comment]
Does this also mean that trying to use this in dev will result in `self.__WB_MANIFEST` not being injected? I am trying to use the virtual module method instead, but the worker cannot precache because the `self.__WB_MANIFEST` array passed into the `precacheAndRoute()` method is empty.

**Comment by userquin** [comment]
@lhjt The dev options is only for testing the sw and the webmanifest not for testing the app with the sw.

The current implementation on dev for the injection point is wrong: see https://github.com/antfu/vite-plugin-pwa/pull/335: this PR will change the behavior to only intercept the webamnifest.
