### ISSUE TITLE
Example / feature of optionally making parts of code offline

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [antfu/vite-plugin-pwa#360]
### Clear and concise description of the problem

I am currently using webpack and not vite. I want to switch to vite / this plugin, but I think vite might be missing something that webpack has which I need.

I am making a website which has multiple games. I want the main website code to be available offline. I want to user to be able to select specific games to download for offline use. I will be using dynamic imports with `import.meta.glob` so there will probably be 1+ files for each game.

### Suggested solution

Add a feature of being able to specify specific imports to individually make available offline. 
This is what it would look like for me:
- index.html (automatic)
- game (on demand)
- game (on demand)
- game (on demand)

I don't know if this is out of the scope of this plugin.

### Alternative

This is what I currently do with webpack:
- Use a plugin which saves [stats](https://webpack.js.org/api/stats/#root) to save a file `stats.json`. This file has info about which games depend on which files
- I have a custom service worker which doesn't use workbox. The service worker makes the main functionality offline
- The UI communicates to the service worker to make specific games available offline or remove a downloaded game.

### Additional context

My project which I am planning on switching to Vite: https://github.com/ChocolateLoverRaj/Banana-Games
Website (with ui for downloading games): https://chocolateloverraj.github.io/Banana-Games/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
@ChocolateLoverRaj the pwa is for the whole site, offline support cannot be selective.

If the user is offline, how do you install the game the user select?

You can try to add a custom sw and add your current logic to it: you can use service worker logic or workbox plugins, check for example this repo (with custom sw events and push notifications): https://github.com/jeffposnick/yt-playlist-notifier

**Comment by ChocolateLoverRaj** [comment]
Okay I will make a custom sw.
