### ISSUE TITLE
Vite 3.0.9 + SSR + Vue 3 ESM Bundler

### ISSUE THREAD

**Issue by pjninnim** [antfu/vite-plugin-pwa#363]
### Describe the bug

vue aliased as {'vue': 'vue/dist/vue.esm-bundler.js'}
try to build produces the following error

[vite-plugin-pwa:build] Could not load vue/dist/vue.esm-bundler.js/server-renderer (imported by src/App.vue): ENOENT: no such file or directory, open 'C:\Dev\myproject\vue\dist\vue.esm-bundler.js\server-renderer'

This issue is not present when using Vite 2

### Reproduction

Try to build when using SSR and the vue.esm-bundler

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 Intel(R) Core(TM) i9-9920X CPU @ 3.50GHz
    Memory: 5.32 GB / 31.69 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pjninnim** [comment]
I managed to resolve this problem by setting 'legacy.buildSsrCjsExternalHeuristics' to 'true' which will tell Vite to generate a CJS bundle for SSR.

**Comment by userquin** [comment]
@pjninnim the error is not in the pwa plugin, pwa plugin will just throw the error in the `buildEnd` hook if there is an error on the build (the error is not in the pwa plugin). 

The error can be confusing, it seems the error comes from the pwa plugin build, but there is no another way to do it.

**Comment by pjninnim** [comment]
@userquin thank you for the explanation. It would be nice if Vite build process would reference the whole error in stack form, then it would be easy to find the source of the issue.
