### ISSUE TITLE
Failing to load module for ssr (@vite-plugin-pwa\pwa-entry-point-loaded)

### ISSUE THREAD

**Issue by ElBouhaliMohamed** [antfu/vite-plugin-pwa#364]
### Describe the bug

If i want to enable my sw in development using devOptions.enabled i get the following error. I am using vite-ssr with vite 3.

![image](https://user-images.githubusercontent.com/28925237/186535851-d3c7c8e9-23e4-4585-8e92-dc67f53cd87e.png)

### Config

`    VitePWA({
      mode: 'development',
      base: '/',
      srcDir: 'src',
      filename: 'sw.ts',
      strategies: 'injectManifest',
      registerType: 'autoUpdate',
      devOptions: {
        enabled: true,
        type: 'classic'
      },
      manifest: {
... }})`

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 16.32 GB / 31.93 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)    
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

**Comment by userquin** [comment]
@ElBouhaliMohamed provide a mininal repro

**Comment by userquin** [comment]
@ElBouhaliMohamed can you try with latest relea a e 0.12.4?

**Comment by ElBouhaliMohamed** [comment]
Seems like its fixed, thank you!
