### ISSUE TITLE
Service worker is not found on dev mode (npm start)

### ISSUE THREAD

**Issue by amreladawy** [antfu/vite-plugin-pwa#374]
### Describe the bug

I am using devOptions to enable service worker in dev mode. When I start the app using `npm start`, service worker file is not found
```
VitePWA({
        injectRegister: null,
        strategies:'injectManifest',
        filename:'service-worker.ts',
        srcDir: 'src',
        devOptions: {
          enabled: true,
          type: "module",
        },
      })
```

### Reproduction

``` VitePWA({         injectRegister: null,         strategies:'injectManifest',         filename:'service-worker.ts',         srcDir: 'src',         devOptions: {           enabled: true,           type: "module",         },       }) ```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 38.31 GB / 63.71 GB
  Binaries:
    Node: 16.16.0  
    npm: 8.17.0  
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.33)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@amreladawy please provide full info or repro: using prompt behavior requires importing virtual module (default `registerType` is `prompt`).

Try removing `injectRegister: null` entry.

**Comment by userquin** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by amreladawy** [comment]
Hi @userquin 
I am using a create react app. I have a custom service worker file and I will register my service worker file myself. That is why I set the `injectRegister` to `null`. 
When I run `npm start` the service worker ts file is not found 404. 
When I build, the service worker file is compiled and saved to build folder. 

Please let me know if any more info is needed.

**Comment by userquin** [comment]
@amreladawy if you register your custom sw, this plugin cannot register it for you, your are preventing that, try removing your registration and let the plugin do its work (removing also `injectRegister: null` from the pwa configuration).

You can also check using react virtual module if you need to interact with the ui: https://vite-plugin-pwa.netlify.app/frameworks/react.html

**Comment by amreladawy** [comment]
Hi @userquin ,thanks for coming back on this. I have tried removing `injectRegister: null` and still have the same issue. 

What I am trying to do is to use vite pwa plugin with the simple create react app. The service worker is compiled successfully when building the app, but it is missing when using `npm start` http://localhost:3000/service-worker.js gives 404

Here is the code used to register the worker, it is exactly the code generated by create-react-app 

```

function checkValidServiceWorker(swUrl: string, config?: Config) {
  // Check if the service worker can be found. If it can't reload the page.
  fetch(swUrl, {
    headers: { 'Service-Worker': 'script' },
  })
    .then((response) => {
      // Ensure service worker exists, and that we really are getting a JS file.
      const contentType = response.headers.get('content-type');
      if (
        response.status === 404 ||
        (contentType != null && contentType.indexOf('javascript') === -1)
      ) {
        // No service worker found. Probably a different app. Reload the page.
        navigator.serviceWorker.ready.then((registration) => {
          registration.unregister().then(() => {
            window.location.reload();
          });
        });
      } else {
        // Service worker found. Proceed as normal.
        registerValidSW(swUrl, config);
      }
    })
    .catch(() => {
      console.log('No internet connection found. App is running in offline mode.');
    });
}

function registerValidSW(swUrl: string, config?: Config) {
  navigator.serviceWorker
    .register(swUrl)
    .then((registration) => {
      registration.onupdatefound = () => {
        const installingWorker = registration.installing;
        if (installingWorker == null) {
          return;
        }
        installingWorker.onstatechange = () => {
          if (installingWorker.state === 'installed') {
            if (navigator.serviceWorker.controller) {
              // At this point, the updated precached content has been fetched,
              // but the previous service worker will still serve the older
              // content until all client tabs are closed.
              console.log(
                'New content is available and will be used when all ' +
                  'tabs for this page are closed. See https://cra.link/PWA.'
              );

              // Execute callback
              if (config && config.onUpdate) {
                config.onUpdate(registration);
              }
            } else {
              // At this point, everything has been precached.
              // It's the perfect time to display a
              // "Content is cached for offline use." message.
              console.log('Content is cached for offline use.');

              // Execute callback
              if (config && config.onSuccess) {
                config.onSuccess(registration);
              }
            }
          }
        };
      };
    })
    .catch((error) => {
      console.error('Error during service worker registration:', error);
    });
}

```
here is the vite plugin configs

```
VitePWA({
        strategies:'injectManifest',
        filename:'service-worker.ts',
        srcDir: 'src',
        devOptions: {
          enabled: true,
          type: "module",
        },
      })
```

**Comment by userquin** [comment]
@amreladawy add `registerType: 'autoUpdate'` (`prompt` is the default behavior) and remove the service worker if installed (just test it on private window), switching between `prompt` and `autoUpdate` can be a pain, it seems you don't have logic for `prompt` behavior

**Comment by userquin** [comment]
@amreladawy also check this issue, similar to your approach but using the callbacks from the virtual: https://github.com/antfu/vite-plugin-pwa/issues/366

**Comment by amreladawy** [comment]
Thanks for reopening it. I have tried registerType: 'autoUpdate'
but still the same error
![image](https://user-images.githubusercontent.com/1336308/190865511-3366dc1a-eb7a-489c-bcc2-6860b17b4a94.png)

I dont have logic for prompt. the service worker is registered right away.

**Comment by userquin** [comment]
@amreladawy the error comes from your ts module not from the plugin: the problem here is that in dev we do not expose the sw filename (it has an alias), I'll check if we can expose some info in the registration callbacks, in the meantime just omit the call to your modules on dev (use [import.meta.env.DEV](https://vitejs.dev/guide/env-and-mode.html#env-variables)) and test sw is working ()you should be able to debug it).

Here: https://github.com/antfu/vite-plugin-pwa/blob/main/src/client/type.d.ts#L5
```ts
onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void
```

I'll try to add this type in a new option callback (or maybe just the `scriptURL` as `swScriptURL`):
```ts
export interface RegisterSWData {
  scriptURL: string
  scope: string
  type: 'classic' | 'module'
}

export interface RegisterSWOptions {
  immediate?: boolean
  onNeedRefresh?: () => void
  onOfflineReady?: () => void
  onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void
  onRegisteredWithInfo?: (swOptions: RegisterSWData, registration: ServiceWorkerRegistration | undefined) => void   
  onRegisterError?: (error: any) => void
}
```

**Comment by userquin** [comment]
@amreladawy you can also use `import.meta.env.DEV` and use this url [dev-sw.js?dev-sw](https://github.com/antfu/vite-plugin-pwa/blob/main/src/constants.ts#L26) (append your scope before it)instead your sw filename

**Comment by userquin** [comment]
@amreladawy a simplest approach, just use the scope from the registation: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/scope

I'll try to dicument it, previous scope should be your sw filename when buiding and the dev name on dev with devOptions enabled.

**Comment by amreladawy** [comment]
Hi @userquin Thanks for the help on that. It worked finally.  Here is the plugin configuration
```
VitePWA({
      injectRegister: null,
      strategies: 'injectManifest',
      filename: 'service-worker.ts',
      srcDir: 'src',
      devOptions: {
        enabled: true,
        type: "module",
      },
      injectManifest: {
        maximumFileSizeToCacheInBytes: 20 * 1024 * 1024,
      }
    })
```

Also, I had to check if this a dev mode or prod then register the correct URL
```
  const swUrl = import.meta.env.MODE === 'prod' ? `/service-worker.js` : '/dev-sw.js?dev-sw';

```

Note, `import.meta.env.PROD` always gives false, so I used the ` import.meta.env.MODE`

I still have some issue with non-prechaced index.html.  https://github.com/antfu/vite-plugin-pwa/issues/120 but still wotking on it.
