### ISSUE TITLE
unable to send vite-pwa-plugin:dev-ready message to register service worker in dev mode!

### ISSUE THREAD

**Issue by alchemist-s** [antfu/vite-plugin-pwa#379]
### Describe the bug

Hello!

Trying to work out a minimal PWA (Vue 3) in dev mode with this plugin and getting the following errors on my console:

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/9383990/191984681-850a25c6-43e0-474d-b354-824a69ee091e.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/9383990/191984745-e0f328dc-61d7-4c81-819d-e81415912f68.png">

I've also noticed that no service workers were generated. I'm using "vite-plugin-pwa": "^0.13.1" and "vite": "^3.1.0".

Also a production build fails with the following error:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/9383990/191988218-52df07c3-a7e4-499f-86f1-b7adbe3c8c84.png">

### Reproduction

https://github.com/alchemist-s/vite-pwa-repro

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 114.02 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    npm: 8.5.4 - /usr/local/bin/npm
    Watchman: 2022.02.14.00 - /usr/local/bin/watchman
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@alchemist-s rename `vite.config.ts` to `vite.config.mts`:

![imagen](https://user-images.githubusercontent.com/6311119/192074504-6e01ff1c-29be-4f4b-afdb-53b099b71b60.png)

![imagen](https://user-images.githubusercontent.com/6311119/192074466-a35e2ad4-90b5-4a12-afaf-e1055016826b.png)

**Comment by userquin** [comment]
upps, maybe node version? I need to install a Node 14 version, can you try with a Node 16?

**Comment by alchemist-s** [comment]
@userquin I did try with node 16 and got the same error. Let me try out your suggestion and I'll get back to you. Thanks for the quick turnaround!

**Comment by userquin** [comment]
@alchemist-s in my local working with Node 16.17.0 with ts and mts

**Comment by userquin** [comment]
@alchemist-s try removing the node_modules and reinstalling deps, it seems vite not being updated: we need Vite 3.1.0 that comes with the new sequential object hook, just check the last error!

**Comment by userquin** [comment]
also Rollup `2.79.0+`, it seems something preventing the update

**Comment by userquin** [comment]
@alchemist-s try switching to pnpm instead using npm...

**Comment by alchemist-s** [comment]
@userquin Okay so I had a global version of vite installed which was at 2.8.6...my bad. Its working perfect with Vite 3.1.0. 

Sorry about that.
