### ISSUE TITLE
Cannot find module 'virtual:pwa-register' in vscode

### ISSUE THREAD

**Issue by qgates** [antfu/vite-plugin-pwa#40]
Hi, vscode is showing error ts2307 on the line `import { registerSW } from 'virtual:pwa-register'` which is near the top of my `app.ts` file. Everything compiles and works, but vscode is complaining. I'm wondering whether it's a problem or something I missed?

**Comment by userquin** [comment]
@qgates see https://github.com/antfu/vite-plugin-pwa/issues/38

**Comment by qgates** [comment]
@userquin thanks, I tried adding `"node_modules/vite-plugin-pwa/client.d.ts"` to `include` array in tsconfig, but it hasn't helped?

**Comment by qgates** [comment]
Made some progress. Removing `node_modules` from the exclude path in `tsconfig` the above seems to work. So it seems tsconfig `exclude` overrides `include`.

As an aside, I'm not sure if this is a smart approach. Removing `node_modules` exclusion means that tsc (when used) will attempt to compile everything in there, and likely spit out a number of errors not related to the project?

Changing the include to `"node_modules/**/*.d.ts"` also works and will probably pick up typings from any installed packages, probably useful.

**Comment by userquin** [comment]
@qgates see this https://stackoverflow.com/questions/46754794/typescript-tsconfig-json-include-exclude-not-working

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by qgates** [comment]
@antfu thank you, see below for a summary, let me know if you need anything else.

See the below (not working) `tsconfig.json`

If I remove `node_modules` from `exclude` in tsconfig.json, the problem goes away, but only if `"node_modules/vite-plugin-pwa/client.d.ts"` is present in `include`. But this raises a few questions:

1. In the case where `node_modules` **isn't** excluded, shouldn't `"include:" [ "./**/*", ...]` pick up any `.d.ts` typings files under the entire node_modules branch? It doesn't seem to, at least in the IDE (vscode in my case). I guess that the reason for this is that just because tsc compiles a file, that doesn't mean it's 'discovered' for module resolution. _(Edit: reading [this tsdoc article](https://www.typescriptlang.org/docs/handbook/module-resolution.html) has made things a little clearer)_
2. Previously using webpack, it has been a general best practice to exclude node_modules, because otherwise tsc would scan node_modules and potentially spit out a bunch of errors unrelated to the project. Not to mention this would slow down the build. I get that with vite this is unnecessary as tsc isn't used. However, it's been my experience that IDE's don't always pick up tsc errors, so we may want to introduce a `tsc --noEmit` build step just to ensure code is error free. What's the best practise to include typings buried under `node_modules` if I want to exclude that folder from the tsc compilation?

I've found these workarounds. Remove `include` references to `client.d.ts` and then:

3. Under compilerOptions add `baseUrl`, then `"paths": { "virtual:pwa-register": ["node_modules/vite-plugin-pwa"] }`
4. Add a `files` section:
```json
"files": [
    "node_modules/vite-plugin-pwa/client.d.ts"
],
```
5. (theoretical) add a DefinitelyTyped `@types/vite-plugin-pwa` (and others!)

Apology in advance for any lack of understanding - TS module resolution has always confused me one heck of a lot more than my C++ coding days 🙄 

![image](https://user-images.githubusercontent.com/4213509/113494750-44f00600-94e3-11eb-873b-874a13620eac.png)

(not working tsconfig.json)
```json
{
   "compilerOptions": {
      "target": "es6",
      "strict": true,
      "module": "es2015",
      "moduleResolution": "node",
      "experimentalDecorators": true,
      "sourceMap": true,
      "skipLibCheck": true,
      "types": ["vite/client"]
   },
   "include": [
      "./**/*",
      "node_modules/vite-plugin-pwa/client.d.ts"
   ],
   "exclude": [
      "node_modules",
      "dist"
   ]
}
```

**Comment by qgates** [comment]
> @qgates see this https://stackoverflow.com/questions/46754794/typescript-tsconfig-json-include-exclude-not-working

Thanks @userquin, that helped clarify things

**Comment by userquin** [comment]
@qgates 
The pwa plugin is a dev dependency, the plugin itself is not compiled, it is already compiled (the dependency has not any ts file, it is build here as an esm module + 2 d.ts files), just like a c++ include or an import on java of an external dependency lib.
You only need to tell compiler where to find it, in this case node resolution (once installed, for example, like a maven or gradle dependency in java or a makefile in c).
The d.ts files are just hints for resolving the imported modules "symbols" on  your source code. If you omit d.ts files from ts config file, the ide Will no resolve it.
Pwa plugin will just create sw.js, and Will emit its corresponding assets and then compiled. For virtual modules it is similar, but vites takes care of its compilation (esbuild).

**Comment by userquin** [comment]
@qgates

try adding entry on `types` on `tsconfig.json` file: `"vite-pluginb-pwa/client"`

![imagen](https://user-images.githubusercontent.com/6311119/113500765-feb99780-9520-11eb-9648-e89e21848937.png)

**Comment by userquin** [comment]
@qgates can you try with new `0.6.5` version?

**Comment by qgates** [comment]
> @qgates
> 
> try adding entry on `types` on `tsconfig.json` file: `"vite-pluginb-pwa/client"`

@userquin that works, thanks

0.6.5 doesn't change anything specific to this issue, although it does stop vscode complaining about `Ref` if I open vite-plugin-pwa/client.d.ts (since I'm using vue2 in this project).

So it appears the `types` approach works in addition to options 3, 4 in my post above. Your approach is the cleanest so that's probably the way to go. Many thanks.

I created PR #42 to help others avoid this issue.

**Comment by csorz** [comment]
如下代码对我有效，希望能帮到你
``` js
if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {
  (async () => {
    const { registerSW } = await import('virtual:pwa-register')
    registerSW({ })
  })()
}
```

**Comment by csorz** [comment]
如下代码对我有效，希望能帮到你

```
if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {
  (async () => {
    const { registerSW } = await import('virtual:pwa-register')
    registerSW({ })
  })()
}
```

**Comment by Laaouatni** [comment]
```
Cannot find type definition file for 'vite-plugin-pwa/client'.
  The file is in the program because:
    Entry point of type library 'vite-plugin-pwa/client' specified in compilerOptions
```

> @qgates
> 
> try adding entry on `types` on `tsconfig.json` file: `"vite-pluginb-pwa/client"`
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/113500765-feb99780-9520-11eb-9648-e89e21848937.png)

![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/87947051/88f5bf92-7950-44e6-80eb-7361474a385c)
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/87947051/484955db-f4ef-428a-80ee-39d0a771ac2b)

**Comment by userquin** [comment]
the screenshot is your project or the sveltekit example in this repo? anyway, you should import type in app.d.ts https://github.com/vite-pwa/sveltekit/blob/main/examples/sveltekit-ts/src/app.d.ts

**Comment by Laaouatni** [comment]
> The screenshot is your project or the sveltekit example in this repo? anyway, you should import type in app.d.ts https://github.com/vite-pwa/sveltekit/blob/main/examples/sveltekit-ts/src/app.d.ts
> 
> You should use `@vite-pwa/sveltekit` instead this plugin: https://vite-pwa-org.netlify.app/frameworks/sveltekit.html
> 
> I need to add TypeScript configuration entry in the docs.

----

yes, it was in my project, not in the example

----

at the end, 
it seems is a harmless error, 
everything works fine even in build, 
so I just used `/* @ts-ignore */`

it seems to me the most reasonable solution here, 
since everything works fine and I can write the least code for making a pwa, 
so I can focus on other things.

-----

is this a good approach too? or can cause bugs in future?
