### ISSUE TITLE
Plugin doesn't work on React vite template?

### ISSUE THREAD

**Issue by krypticallusion** [antfu/vite-plugin-pwa#41]
```
import { registerSW } from 'virtual:pwa-register'
 
registerSW({
  onOfflineReady() {
    // show a ready to work offline to user
  },
})
```

Upon build

```
$ tsc && vite build
node_modules/vite-plugin-pwa/client.d.ts:12:28 - error TS2307: Cannot find module 'vue' or its corresponding type declarations.

import type { Ref } from 'vue'
```

Do I have to install vue for this plugin to work?

EDIT: 

I had to include `node_modules/vite-plugin-pwa/client.d.ts` in `tsconfig.json` for VScode to even pick up that such a module exists.

**Comment by userquin** [comment]
@krypticallusion can you provide a minimal repro so we can test? thanks

**Comment by userquin** [comment]
@krypticallusion,  can you can try to add the entry on the `tsconfig.json` file (if you have exclude `node_modules` maybe will not work)?

**Comment by userquin** [comment]
@krypticallusion can you add types with this?:
```json
"types": [
   "vite-plugin-pwa/client"
]
```

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/113500755-e184c900-9520-11eb-9dbd-b4175a88ea08.png)

**Comment by krypticallusion** [comment]
https://github.com/krypticallusion/test. This is a fine test repo? 

I've tried your above suggestions but they seem to be in vain.

Thanks!

**Comment by userquin** [comment]
@krypticallusion add `include` instead `types` (similar to exclude in previous picture):
```json
"include": ["vite-plugin-pwa/client"]
```
I'll try with you repro...

**Comment by krypticallusion** [comment]
0.6.5 seems to resolve the issue. Thanks!
