### ISSUE TITLE
Browser is not detecting Service Worker

### ISSUE THREAD

**Issue by jahidanowar** [antfu/vite-plugin-pwa#47]
I have configured the manifest option as per the docs but still, the service worker is not detected by the browser. 

My Dependencies
```
"dependencies": {
    "vue": "^3.0.5",
    "vue-router": "^4.0.6",
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.2.1",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.2.5",
    "postcss": "^8.2.10",
    "tailwindcss": "^2.1.1",
    "vite": "^2.1.5",
    "vite-plugin-pwa": "^0.7.0"
  }
```
Here is my repo [https://github.com/jahidanowar/qrcodescanner](https://github.com/jahidanowar/qrcodescanner)

**Comment by userquin** [comment]
the service worker is only generated when building, not for dev: see https://github.com/antfu/vite-plugin-pwa/issues/26

**Comment by userquin** [comment]
You can install this dependency as a dev dependency: `npm i --save-dev localhost-https`.

Then add this script to your `package.json`:
```json
  "scripts": {
    "preview-https": "serve dist",
  }
```
To test service worker just run this:
`npm run build && npm run preview-https`

First time you run it, will ask you about installing a certificate (that will be generated for you), confirm installation on OS (keychain on macosx and certificate manager on windows) and open https://localhost on chrome, for example.

**Comment by jahidanowar** [comment]
It's not working on production as well.

**Comment by userquin** [comment]
what's the url?

**Comment by jahidanowar** [comment]
Here is the deployed version (It is deployed on vercel): [https://www.qrcodescanner.net/](https://www.qrcodescanner.net/)
This is my repo: [https://github.com/jahidanowar/qrcodescanner](https://github.com/jahidanowar/qrcodescanner)

**Comment by userquin** [comment]
I'll take a look

**Comment by userquin** [comment]
Just cloned and works:

![imagen](https://user-images.githubusercontent.com/6311119/114570625-44d7cf00-9c76-11eb-9020-726002d434fb.png)

**Comment by jahidanowar** [comment]
I forgot to call `registerSW()` on main.js. Now it's working fine. Thanks for the quick response.
