### ISSUE TITLE
Make dist folder configurable

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-pwa#5]
You have static `dist/sw.js` and `dist/manifest.webmanifest` and cannot be changed.

It fails if I use `outDir: 'web-resources'` on `vite.config.ts` file.

**Comment by antfu** [comment]
Sure, would you mind create a PR? Thanks!

**Comment by userquin** [comment]
done

**Comment by userquin** [comment]
@antfu

**Comment by userquin** [comment]
@antfu tested on my project and working
