### ISSUE TITLE
Bug: Netlify redirects do not work anymore

### ISSUE THREAD

**Issue by liyasthomas** [antfu/vite-plugin-pwa#52]
**Description**
I've a simple Vite project at https://github.com/liyasthomas/liyasthomas.com hosted on Netlify with some redirects on sub pages. I installed `vite-plugin-pwa` and now its redirects are not working anymore. PWA plugin's readme doesn't have anything regarding how installing `vite-plugin-pwa` affects routing.

**Steps to reproduce**
1. Spin up a Vite + Vue 3 project
2. Host on netlify with a redirect on Netlify:

	`netlify.toml`
   ```
	  [[redirects]]
	    from = "/abc"
	    to = "https://abc.com"
	    status = 301
	    force = true
   ```
3. Install `vite-plugin-pwa`
4. Redirects are broken

**Comment by userquin** [comment]
@liyasthomas what do you expect to happen? I just fork your repo, and is working, at least in local. All your links are external to the app, so maybe there is a problem with your `netlify.toml`: all links to twiter and github are excluded from the pwa. The pwa plugin cannot track external resources, see your `sw.js` on production: to test locally, just run `npm i -D https-localhost` and add this script to your `package.json`: `"preview": "npm run build && serve dist"`, and then `npm run preview` (see [Testing service worker](https://github.com/antfu/vite-plugin-pwa#testing-service-worker))

**Comment by liyasthomas** [comment]
Thanks for the quick response. I figured it out.

**Comment by dheimoz** [comment]
Hi @liyasthomas I wonder if you can share how you can sort it the issue. It will benefit the community.

Thanks.
