### ISSUE TITLE
include custom files/dirs in sw cache?

### ISSUE THREAD

**Issue by rehhouari** [antfu/vite-plugin-pwa#53]
Hello,
I have a directory `/public/images` which contain icons. the icons are referenced in `index.html` and the pwa webmanifest as `/images/icon-x.png`.
The images directory is moved to the dist folder on build, as expect. but it is not included in the cache, which is kinda expected as well.
Can I include it manually? The images disappear right after reload when the app goes offline.

Note: I've tried using the `assetsInclude` config of Vite, as the PWA `manifest` config don't automatically change URLs to generated ones, meaning in webmanifest `/images/icon-x.png` don't turn into /images/icon-x-123ea.png` on build.

demo link if needed: https://vite-alpine-pwa.vercel.app/

**Comment by stefanholzapfel** [comment]
I tried the include property of injectManifest options:
```
      VitePWA({
          registerType: 'prompt',
          injectRegister: null,
          srcDir: '',
          filename: 'sw.ts',
          strategies: 'injectManifest',
          injectManifest: {
              include: [
                  path.resolve(__dirname, 'public'),
              ]
          },
          manifest: false
      })
```

but the I get a build error stating:

```
error during build:
ValidationError: "include" is not allowed
```

**Comment by userquin** [comment]
@stefanholzapfel , @rehhouari you can use this as a workaround:
```typescript
VitePWA({
  ...
  workbox: {
    additionalManifestEntries: buildAdditionalManifestEntries()
  }
}),
```

using this function (put your icons on `nonAssetsToBeIncluded` and add your logic for resolving non assets resources: I use this logic to also add other static resources like favicon, svg and fonts files):
```typescript
import path from 'path'
import crypto from 'crypto'
import { readFileSync } from 'fs'
...
const nonAssetsToBeIncluded = [
  'public/favicon.ico',
  ..., 
  'public/icon-a.png', 
  'public/icon-b.png',
  ...,
  'public/icon-n.png',
  ...,
  'public/fonts/roboto.ttf'.
  ...
];
const buildAdditionalManifestEntries = (): [] => {
  const additionalManifestEntries = []
  let url
  let hash
  for (let i = 0; i < nonAssetsToBeIncluded.length; i++) {
    url = nonAssetsToBeIncluded[i]
    // console.log(url)
    const content = readFileSync(path.resolve(url))
    const cHash = crypto.createHash('MD5')
    cHash.update(content)
    hash = cHash.digest('hex')
    if (url.startsWith('public/'))
      url = url.substring(7) // since public is mapped to / we need to remove from the path

    additionalManifestEntries.push({
      url,
      revision: `${hash}`,
    })
  }
  return additionalManifestEntries as []
}

```

**Comment by userquin** [comment]
@stefanholzapfel since your are injecting the manifest, you need to add `additionalManifestEntries` on `injectManifest` option instead on `workbox` option:
```typescript
VitePWA({
  ...
  injectManifest: {
    additionalManifestEntries: buildAdditionalManifestEntries()
  }
}),
```

The PR #62 is almost finished, just need a review and so you will have it in a few days ready to be used.

**Comment by stefanholzapfel** [comment]
@userquin Sorry that doesn't work for me. Files from public folder that are added to the nonAssetsToBeIncluded array are still fetched from the web and not the service worker...

**Comment by userquin** [comment]
> @userquin Sorry that doesn't work for me. Files from public folder that are added to the nonAssetsToBeIncluded array are still fetched from the web and not the service worker...

Can you test with 0.8.1 version?

**Comment by stefanholzapfel** [comment]
@userquin Yeah that seems to work, thank you!!
