### ISSUE TITLE
How disable `injectManifest` ?

### ISSUE THREAD

**Issue by cawa-93** [antfu/vite-plugin-pwa#55]
I Try use this plugin in Electron app. 

Technically, this is a web page with a strict Content-Security-Policy.
During development, the page runs at `http://localhost:3000`, and in the production environment as `file:///C:/path-to/app/resources/index.html`

Precache, I think, is not very important for my, because all assets are located locally anyway. But using the schema `file:` imposes certain problems for the service worker.

Therefore, I am only interested in the service worker as a tool for caching network requests. And I want to completely disable `injectManifest`.

I tryed
```js
    VitePWA({
      injectRegister:'script',
      manifest: false,
      injectManifest: false,
})
```
But in `sw.js` still has 
```js
  workbox.precacheAndRoute([{
    "url": "index.8daf1fe7.css",
    "revision": "bb76d49a4d80950ac285a814832c9c8a"
  }, {
    "url": "index.f66a5a19.js",
    "revision": "a8e69220ac0a4822a5e98ec359765139"
  }, {
    "url": "index.html",
    "revision": "7c2b1f2f6f2698a7dd5ba69c1e4ca1c3"
  }, {
    "url": "registerSW.js",
    "revision": "e21bbf02f2e95e944e8acae5f65ca7f7"
  }, {
    "url": "vendor.f57ce527.js",
    "revision": "cbcca323ae9391f4ef2f13c0065e7abd"
  }, {
    "url": "Watch.8c7a9f24.js",
    "revision": "b7aceb22f06e7a44553c43001c7c1f60"
  }], {});
  ```

**Comment by userquin** [comment]
@cawa-93 try this: 
```javascript
VitePWA({ injectRegister: null })
```

**Comment by cawa-93** [comment]
@userquin It not help. Generated `sw.js`:

```js
  workbox.precacheAndRoute([{
    "url": "index.8daf1fe7.css",
    "revision": "bb76d49a4d80950ac285a814832c9c8a"
  }, {
    "url": "index.f66a5a19.js",
    "revision": "a8e69220ac0a4822a5e98ec359765139"
  }, {
    "url": "index.html",
    "revision": "dd0936008c2fede9714e474109432223"
  }, {
    "url": "vendor.f57ce527.js",
    "revision": "cbcca323ae9391f4ef2f13c0065e7abd"
  }, {
    "url": "Watch.8c7a9f24.js",
    "revision": "b7aceb22f06e7a44553c43001c7c1f60"
  }], {});
  workbox.cleanupOutdatedCaches();
  workbox.registerRoute(new workbox.NavigationRoute(workbox.createHandlerBoundToURL("index.html")));
  workbox.registerRoute(/^https:\/\/smotret-anime\.online\/api\/.*/, new workbox.CacheFirst({
    "cacheName": "sm-api-calls",
    plugins: [new workbox.ExpirationPlugin({
      maxAgeSeconds: 3600,
      purgeOnQuotaError: true
    })]
  }), 'GET');
```

Expected:
```js
  workbox.registerRoute(/^https:\/\/smotret-anime\.online\/api\/.*/, new workbox.CacheFirst({
    "cacheName": "sm-api-calls",
    plugins: [new workbox.ExpirationPlugin({
      maxAgeSeconds: 3600,
      purgeOnQuotaError: true
    })]
  }), 'GET');
```

**Comment by userquin** [comment]
@cawa-93 what do you want to do, generating a custom `sw` or just exclude registering on `index.html`?. For the former see [Advanced (injectManifest)](https://github.com/antfu/vite-plugin-pwa#advanced-injectmanifest), and for last one check if using `injectRegister: null` just do not register the `sw.js` on generated `index.html`.

If you don't need to register the `sw.js`, what this plugin generates does not matter. In other case, we cannot build a `custom` service worker, and so we cannot remove the `workbox.precacheAndRoute` entries (default behavior). If you want to build a `custom` service worker, just build it using `workbox`. You can see a `typescript sample` [here](https://github.com/antfu/vite-plugin-pwa/blob/master/examples/vue-basic-inject-manifest/src/sw.ts).

**Comment by userquin** [comment]
@cawa-93 I'll try to see if there is an option on `workbox` to disable `workbox.precacheAndRoute`, and so you can override default configuration of `workbox` in `VitePWA`. Keep in mind there is a lot of configuration options, and it is hard to remember all.

**Comment by userquin** [comment]
@cawa-93 this plugin just call `generateWS` from `workbox-util` providing a merged configuration from defaults ([see this](https://github.com/antfu/vite-plugin-pwa/blob/master/src/options.ts#L75)) and provided on configuration plugin. You can see the options [here](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW). Just use `workbox` entry on `VitePWA` to configure your service worker build.

**Comment by cawa-93** [comment]
@userquin 
```js
VitePWA({
  workbox: {
    globPatterns: [],
    // ...
  }
})
```
Do what i expected. Thanks.

**Comment by userquin** [comment]
@cawa-93 thx, @antfu I'll use your hint to fix another pending task here about including manifest icons on the precache and routing output.
