### ISSUE TITLE
Is it possible somehow register a serviceWorker in `development`?

### ISSUE THREAD

**Issue by cawa-93** [antfu/vite-plugin-pwa#56]
I understand that in most cases it's superfluous but I have a slightly non-standard case)

My application is mostly placed on the third party's api. This API works slowly, and has a limit for requests. On `development` (when you often load and reload page many times), the page I create a lot of requests to this api, it slows down my work and exhausts all the limits.

I see a service worker as a good solution to this problem.
In `production` are all great. Network requests to the third party API use the `CacheFirst` strategy. This is accelerating the work of the application and reduces the load on the remote server.

I have no need to take over about actual of data and I would like to apply the same caching strategy for `development` too.

**Comment by userquin** [comment]
@cawa-93 Why are you trying to cache ui with remote data instead adding a proxy/middleware (abstraction layer) serving for example mock json files simulating remote api service calls?.

I use this approach for html ppl that does not have access to backend, including CRUD operations (just a mock server with express accessing local json files). 

You can use a proxy and provide a url to fetch data and using process.env with `.local` variants changing it on development on some `profile`.

For example, using SERVICE_API_CALL on process.env files, just change it to use localhost on some profile, then on development use this profile, addind a server to your environment, then add mapping on the node/express server to mock via json files (you must create them) and you are done.

Once tested you can do a real test using another profile, where SERVICE_API_CALL just point to the real service api.

**Comment by cawa-93** [comment]
@userquin  Because
- I'm working on a serverless desktop application.
- I do not cache static files ui at all.

The service worker performs this task: he works as a proxy to the third-party API and caches successful requests. And **only** requests to third party APIs are cached, nothing more. Actually, this is all that in my case requires a service worker. I don't think it makes sense to run a local proxy server that will do exactly the same thing as a service worker.

**Comment by timothymctim** [comment]
Despite being recommended against, you can achieve this by registering the service worker yourself.
For example add the following snipped to you code (e.g., `main.ts` or `src/App.vue`)
```typescript
import { Workbox } from "workbox-window";


const serviceWorkerPath = '/sw.js';

if ('serviceWorker' in navigator) {
  const wb = new Workbox(serviceWorkerPath);
  wb.register()
    .then(() => {
      // registered
    })
    .catch((error) => {
      // error :-(
    });
}
```

If you need more functionally of the module (e.g., `registerSW`), you can try to copy bits from https://github.com/antfu/vite-plugin-pwa/blob/master/src/client/build/register.ts#L12.

**Comment by userquin** [comment]
@cawa-93 so you only need the service worker to intercept api calls, no? I'll try (ASAP) to make a special service worker here for that purpose that will work also in development.

Maybe we should open a discussion...

 If you have some sugestions don't hesitate to contact me here or on Discord (Joaquín#7667).

**Comment by userquin** [comment]
I have a new branch on local to allow test service worker on development only for third party libraries (in general if `runtimeCaching` is configured on `workbox` entry) and only for `generateWS` strategy. In development only the `runtimeCaching` is generated (also registered) excluding manifest file and all routes and assets from the generated service worker.
I have it working on `vue-router` example, I have added a few buttons to change the source of an image on `App.vue` using `https://http.cat/`

You can see in action here: https://github.com/userquin/vite-plugin-pwa/tree/feat/third-party-cache-api-sw.

To run the demom from the root folder: `pnpm run example:router:dev` => don't forget to run `pnpm install && pnpm run build` before.
You can also start the build demo `pnpm run example:router:start`

**Comment by userquin** [comment]
Unfortunately we have made the decision not to include this behavior, since it's just another big maintaining surface.

I'll keep the branch on my fork a few days if you want to clone/download it.

**Comment by userquin** [comment]
@cawa-93 development support added on `0.11.13` version
