### ISSUE TITLE
Aws build error

### ISSUE THREAD

**Issue by mesutgok** [antfu/vite-plugin-pwa#61]
Hi,

Prevented us from tracking other errors in AWS code builds
How do I fix it?

![image](https://user-images.githubusercontent.com/629582/117782822-ad50a680-b24a-11eb-9111-c7b8de1fa2a9.png)

**Comment by userquin** [comment]
@mesutgok see https://github.com/antfu/vite-plugin-pwa/issues/68#issuecomment-859784272

**Comment by userquin** [comment]
@mesutgok can you test again with 0.8.0 version?

**Comment by mesutgok** [comment]
@userquin  yeap i did. working
