### ISSUE TITLE
Catch failed service worker registration

### ISSUE THREAD

**Issue by timothymctim** [antfu/vite-plugin-pwa#63]
Is it possible to catch the error when the registration of a service worker fails? I would like to add a custom callback when this happens.

Reading the code (https://github.com/antfu/vite-plugin-pwa/blob/master/src/client/build/register.ts#L79), I do not see a way to catch any errors thrown during registration. Is there some other way I can check if the registration succeeded, or can(/should) I register the service worker myself?

**Comment by timothymctim** [comment]
Note that it’s perfectly possible to simply register the service worker yourself if you don’t have any special needs. I register my `injectManifest` service worker as follows
```typescript
import { Workbox } from "workbox-window";


const serviceWorkerPath = '/sw.js';

if ('serviceWorker' in navigator) {
  const wb = new Workbox(serviceWorkerPath);
  wb.register()
    .then(() => {
      // registered
    })
    .catch((error) => {
      // error :-(
    });
} 
```

While it’s now solved for me, I understand that for others that use `registerSW` it might still be desirable to add custom callbacks when registration failed.

**Comment by userquin** [comment]
@timothymctim you will have problems with this aproach since you are removing all logic to updates sw caches, don't do this, see #33. At some point in future your pwa will stop working with 404 when navigating pages.

I'll try to fix as ASAP...

**Comment by timothymctim** [comment]
Thank you for your quick feedback. Also, no need to rush to implement this, thanks :-)

I’m not sure if #33 would really affect me as I basically only use this plugin to transpile my Typescript service worker to a Javascript version and replace `self.__WB_MANIFEST` with the proper files. Maybe this plugin is a bit of an overkill, but I couldn’t find any simpler solution.

**Comment by userquin** [comment]
@timothymctim do you need the behavior or we can close this issue?

**Comment by timothymctim** [comment]
I’ve worked around this issue, so I don’t need this specifically, thanks. Whether this feature should be added for other users or not, I’ll leave you to decide.
