### ISSUE TITLE
run "vite" get a error "Error: The following dependencies are imported but could not be resolved:"

### ISSUE THREAD

**Issue by baboon-king** [antfu/vite-plugin-pwa#64]
# ENV
- node
v15.14.0
- npm
7.10.0
- "vite": "^2.0.1",
- "vite-plugin-pwa": "^0.7.2",

# devDependencies
```json
  "devDependencies": {
    "@commitlint/cli": "^12.1.1",
    "@commitlint/config-conventional": "^12.1.1",
    "@types/node": "^15.0.1",
    "@typescript-eslint/eslint-plugin": "^4.22.0",
    "@typescript-eslint/parser": "^4.22.0",
    "@vitejs/plugin-vue": "^1.1.4",
    "@vue/compiler-sfc": "^3.0.5",
    "commitizen": "^4.2.3",
    "cz-conventional-changelog": "^3.2.0",
    "cz-customizable": "^6.3.0",
    "eslint": "^7.25.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-vue": "^7.9.0",
    "https-localhost": "^4.6.4",
    "husky": "^6.0.0",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "stylus": "^0.54.8",
    "typescript": "^4.1.3",
    "vite": "^2.0.1",
    "vite-plugin-pwa": "^0.7.2",
    "vite-plugin-style-import": "^0.9.2"
  },
```
   
# full error message
```shell
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  virtual:pwa-register (imported by /Users/baboon/github/picx/src/common/utils/registerSW.ts)

Are they installed?
    at optimizeDeps (/Users/baboon/github/picx/node_modules/vite/dist/node/chunks/dep-e9a16784.js:64742:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async runOptimize (/Users/baboon/github/picx/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68555:48)
    at async Server.httpServer.listen (/Users/baboon/github/picx/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68569:17)
```

**Comment by userquin** [comment]
@baboon-king can you share `vite.config.ts` and `registerWS.ts` files?

**Comment by baboon-king** [comment]
> @baboon-king can you share `vite.config.ts` and `registerWS.ts` files?

- registerSW.ts
```typescript
import { registerSW } from 'virtual:pwa-register'
registerSW()
```

- vite.config.ts
```typescript
import type { UserConfig, ConfigEnv } from 'vite'
import { loadEnv } from 'vite'
import { resolve } from 'path'
import createVitePlugins from './src/plugins'
import wrapperEnv from './src/common/utils/env'

function pathResolve(dir: string) {
  return resolve(__dirname, '.', dir)
}

// https://vitejs.dev/config/
export default ({ command, mode }: ConfigEnv): UserConfig => {
  const root = process.cwd()
  const env = loadEnv(mode, root)
  const isBuild = command === 'build'

  // loadEnv 中返回的是 string 类型的（即使是 boolean），下面的方法可以返回正确的类型
  const viteEnv = wrapperEnv(env)
  const { VITE_PORT, VITE_PUBLIC_PATH, VITE_OPEN_BROWSER, VITE_CORS } = viteEnv

  return {
    plugins: createVitePlugins(viteEnv, isBuild),
    resolve: {
      alias: {
        '@': pathResolve('src') // 设置 @ 指向 src
      }
    },
    base: VITE_PUBLIC_PATH, // 设置打包路径
    server: {
      port: VITE_PORT,
      open: VITE_OPEN_BROWSER,
      cors: VITE_CORS
    }
  }
}
```
# more 
https://github.com/vitejs/vite/issues/3465

**Comment by userquin** [comment]
@baboon-king I suggest you move the logic inside the router, and register the service worker on `isReady` callback, since you are using `registerType: 'autoUpdate'`. You have an example here: [Vitesse template](https://github.com/antfu/vitesse/blob/master/src/modules/pwa.ts).

About the error, just import it with with a normal import and just call `registerSW` inside the production if statement on your `index.ts` (I have found your repo). Beware if using SSR/SSG, this will not work (see #37).

**Comment by baboon-king** [comment]
@userquin 
Well, thank you very much.

**Comment by jasdeepkhalsa** [comment]
I'm using the Vite TypeScript template and solved this by changing:

```html
<script type="module" src="src/main.ts"></script>
```

To:

```html
<script src="src/main.ts"></script>
```

Hope this helps someone!

**Comment by amanzrx4** [comment]
> I'm using the Vite TypeScript template and solved this by changing:
> 
> ```
> <script type="module" src="src/main.ts"></script>
> ```
> 
> To:
> 
> ```
> <script type="module" src="/src/main.ts"></script>
> ```
> 
> Notice I added a forward slash to the path.
> 
> The reason for this is the way rollup, which is the module bundler for Vite, looks for files. Described here: https://stackoverflow.com/questions/67696920/vite-rollup-failed-to-resolve-build-error
> 
> Hope this helps someone!

worked for me, thanks

**Comment by ljxok2001** [comment]
> I'm using the Vite TypeScript template and solved this by changing:
> 
> ```
> <script type="module" src="src/main.ts"></script>
> ```
> 
> To:
> 
> ```
> <script type="module" src="/src/main.ts"></script>
> ```
> 
> Notice I added a forward slash to the path.
> 
> The reason for this is the way rollup, which is the module bundler for Vite, looks for files. Described here: https://stackoverflow.com/questions/67696920/vite-rollup-failed-to-resolve-build-error
> 
> Hope this helps someone!

This worked for me too, thanks.

**Comment by mqliutie** [comment]
> I'm using the Vite TypeScript template and solved this by changing:
> 
> ```
> <script type="module" src="src/main.ts"></script>
> ```
> 
> To:
> 
> ```
> <script type="module" src="/src/main.ts"></script>
> ```
> 
> Notice I added a forward slash to the path.
> 
> The reason for this is the way rollup, which is the module bundler for Vite, looks for files. Described here: https://stackoverflow.com/questions/67696920/vite-rollup-failed-to-resolve-build-error
> 
> Hope this helps someone!

niubility

**Comment by HyNuwa** [comment]
> @baboon-king I suggest you move the logic inside the router, and register the service worker on `isReady` callback, since you are using `registerType: 'autoUpdate'`. You have an example here: [Vitesse template](https://github.com/antfu/vitesse/blob/master/src/modules/pwa.ts).
> 
> About the error, just import it with with a normal import and just call `registerSW` inside the production if statement on your `index.ts` (I have found your repo). Beware if using SSR/SSG, this will not work (see #37).
> 
> On #37 you have an example similar what you want.

tried others solutions, didn't work, noob question: what do you mean by "normal import"?
