### ISSUE TITLE
Create a svelte-kit example

### ISSUE THREAD

**Issue by FunMiles** [antfu/vite-plugin-pwa#65]
I know svelte-kit is in beta, but this vite-plugin-pwa seems a good fit with svelte-kit. 
I gave it a try but so far am not succeeding. The `npm run build` seems to perform correctly but the generated code makes use of `navigator` and the result fails. It could be due to the SSR that svelte-kit does.

**Comment by userquin** [comment]
see #37

**Comment by userquin** [comment]
I'll update `README.md` to include usage on `SSR/SSG` environments...

**Comment by FunMiles** [comment]
@userquin That was quick :) I turned off the SSR site-wide in svelte-kit's configuration and now it works. I will try the solution you pointed to. Thank you.
Once I've succeeded, I can contribute an example in a PR.

**Comment by FunMiles** [comment]
PS: To avoid having to create a async for the import, I did this as an alternative to your solution:
```js
<script lang="ts">
	import Header from '$lib/Header/index.svelte';
	import '../app.css';
	import { registerSW } from 'virtual:pwa-register';

	const updateSW = (typeof window !== 'undefined') && registerSW({
	  onNeedRefresh() {
	    // show a prompt to user
	  },
	  onOfflineReady() {
	    // show a ready to work offline to user
	  },
	})
</script>
```

**Comment by userquin** [comment]
@FunMiles the only diference between using import or async import is just the bundle size: the former will be included on your bundle latter will not (but will require another server request), just test both.

**Comment by FunMiles** [comment]
The sw.js is running but gets an error: `Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]`. I am presuming that it is because the plugin does not add the svelte-kit-generated index.html to the list of things to cache.  Can I do that via the `workbox` options in the configuration file?

**Comment by userquin** [comment]
use `globPatterns` parameter of `workbox` plugin option.

**Comment by userquin** [comment]
@FunMiles we have a pending PR for `Static assets handling`: see [this line](https://github.com/antfu/vite-plugin-pwa/pull/62/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R151), at the end of the section you can find the reference for `globPatterns` parameter.

**Comment by FunMiles** [comment]
I added `globPatterns: [ '**/*.{js,css,html}', '*.html' ]` without success. Looking at what `npm run build` created, there is no `index.html`. 
Trying to load `http://localhost:3000/index.html` returns a 404. It makes me think svelte-kit does not generate it. It may be serving a on-the-fly generated html file.... Which may not be surprising. From the svelte-kit documentation, I am understanding it creates a file with the SSR version and then `hydrates` it.

**Comment by userquin** [comment]
Anyway, it is curious that svelte-kit do not generates `index.html` entry ;).

**Comment by userquin** [comment]
see if you can force to generate it...

**Comment by FunMiles** [comment]
I put the `ssr: false` flag back into the config, but it still did not generate an index.html. In fact there is no `html` file whatsoever....

**Comment by userquin** [comment]
Sveltekit has its own service worker module [$service-worker](`https://kit.svelte.dev/docs#modules-$service-worker`) :)

**Comment by FunMiles** [comment]
That's not exactly correct. It has a `service-worker` helper mechanism, but, you still have to write the service-worker code yourself. And then everything else for the PWA to work. I was hoping to use vite-plugin-pwa to do all with workbox.
I guess I'll explore creating a service-worker.js that calls workbox, passing it the list of file that svelte-kit passes.

**Comment by userquin** [comment]
try to import the serviceworker and then use instead `additionalManifestEntries`, you will need to calculate its MD5 hash: see [this file](https://github.com/antfu/vite-plugin-pwa/pull/62/files#diff-001347cc727cf0cda0ccc53a07a92207e342ab83fe88aaa789b752a9e9ea5832)

**Comment by userquin** [comment]
can you share a minimal project? I have never use sveltekit, svelte a few years ago... I can take a look to include it here

**Comment by FunMiles** [comment]
I can share a minimal project. Do you want the one I was making trying to integrate vite-plugin-pwa or one with trying to handwrite a svelte-kit service worker?

**Comment by userquin** [comment]
latter, I want to play with sveltekit and figure out how to integrate here with some store to use it like `vue` virtual module.

I think we have to solve 2 problems, former generating the sw and latter add some utilities, see `vue-router` sample: see [this](https://github.com/antfu/vite-plugin-pwa/blob/master/examples/vue-router/src/ReloadPrompt.vue).

Or you can make a PR integrating it on `examples` directory, at least to have the skeleton, when finished just request a review...

**Comment by userquin** [comment]
I just use the `vitejs` starter for `svelte-ts` and `index.html` is generated:
```shell
pnpm init @vitejs/app -- --template svelte-ts
Need to install the following packages:
  @vitejs/create-app
Ok to proceed? (y) y
√ Project name: · vite-svelte-project

Scaffolding project in F:\work\projects\quini\GitHub\vite-svelte-project...

Done. Now run:

  cd vite-svelte-project
  npm install
  npm run dev


F:\work\projects\quini\GitHub>cd vite-svelte-project
F:\work\projects\quini\GitHub\vite-svelte-project>pnpm run build

> vite-svelte-project@0.0.0 build F:\work\projects\quini\GitHub\vite-svelte-project
> vite build

vite v2.3.3 building for production...
✓ 8 modules transformed.
dist/assets/svelte.d72399d3.png   5.06kb
dist/index.html                   0.49kb
dist/assets/index.64a40f2d.css    0.88kb / brotli: 0.37kb
dist/assets/index.952af12d.js     2.38kb / brotli: 0.93kb
dist/assets/vendor.ac1b4535.js    3.55kb / brotli: 1.43kb
```

**Comment by userquin** [comment]
@FunMiles have you a discord user?

**Comment by FunMiles** [comment]
I use discord for svelte/svelte-kit and other things. Not an expert at it. Will try to find you.

**Comment by FunMiles** [comment]
Svelte-kit has its own service worker mechanism and this github is a basic app that works as a PWA:
https://github.com/FunMiles/SveltekitPWA
