### ISSUE TITLE
in sw.js precacheAndRoute does not inlcude vendor.js

### ISSUE THREAD

**Issue by gaoxiaoliangz** [antfu/vite-plugin-pwa#66]
Every other files generated by vite are included by sw.js, but not vendor.js. Interestingly vendor.css is included. Is it a feature or a bug?

**Comment by userquin** [comment]
@gaoxiaoliangz Can you share a minimal reproduction? Thanks.

**Comment by userquin** [comment]
@gaoxiaoliangz this plugin will include in the sw *precache* all resources emitted by Vite in the bundle (for example, `static assets` will not be included in the bundle, and so missing on sw *precache*: see all related issues about including images on Vite's `public` directory, there is a PR in progress to solve this).

**Comment by gaoxiaoliangz** [comment]
I cannot reproduce this in a mini repo, vendor.js is included. But in the actual build, I found that vendor.js is marked yellow since it's too large. Is it related in the sw precache strategy?
![image](https://user-images.githubusercontent.com/10410606/119212815-6a65bd00-baed-11eb-97b9-2c36bf102451.png)

**Comment by userquin** [comment]
@gaoxiaoliangz could you try to build the bubdle with VitePWA commented from vite.config file and see the result for that asset? Without a reproduction I can't do anything...

**Comment by userquin** [comment]
@gaoxiaoliangz try with latest version `0.8.1`

**Comment by userquin** [comment]
@gaoxiaoliangz we close the issue, if after updating the plugin you still have this problem, create a New one.
