### ISSUE TITLE
Caching JSON data returned by Axios

### ISSUE THREAD

**Issue by haliuhei** [antfu/vite-plugin-pwa#67]
Test found that XHR will not cache, how to configure

**Comment by userquin** [comment]
@haliuhei I think you cannot intercept syncronous request, last time I read about it doesn't work, I'll check the service worker docs, but you need to use `fetch` api to make it working with servive worker.

**Comment by userquin** [comment]
Found issues: will not work, at least on chromium based browsers, there is a deadlock/livelock intercepting synchronous request.

https://bugs.chromium.org/p/chromium/issues/detail?id=602051
https://chromium-review.googlesource.com/c/chromium/src/+/1376738
