### ISSUE TITLE
Question about preloading excluded assets

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-pwa#7]
I have a small app using `vitesse` template (that uses this plugin) and I have a problem with some SVG images that are not included on assets directory (are too big to be inlined, and then vite just set its href to undefined, so I moved them to public directory), but then, this plugin excludes these images from PWA, or at least once installed (PWA on client), these SVG are not downloaded (and when testing offline, just alt attribute are displayed instead SVG).

I'm looking to use prefetching these SVG once the page is requested, but the problem pages are served from external server (webflux kotlin server with freemarker template) and the rest of pages are excluded (I have 4 pages, one containing a subgroup of these SVG and another containing other subgroup of these SVG). Maybe preloading all pages via html link will work (I've not test yet)?

I use server push on server side once each page is requested using `vite manifest.json file`, so when requesting a page all resources are just cached.

Is there a way to include some prefetch via these plugin to hook into the workbox or I just need to use [Cache Storage API](https://developers.google.com/web/tools/workbox/guides/common-recipes#access_caches_from_your_web_apps_code)?

Another question is about user feedback: 
How to integrate with these plugin?

Any suggestions are welcome.

Thx in advance.

**Comment by userquin** [comment]
@antfu I can link to my pre environment, just give me an email address, I don't want to make it public...

and sorry to bother you... it is my first PWA

**Comment by antfu** [comment]
If it's a GitHub repo, `antfu` will do. Or `anthoyfu117@hotmail.com` for email.

TBH, as I am not familiar with the other tech you are using, I am afraid if I can do any help there. Sorry, I can't really promise anything.

**Comment by userquin** [comment]
@antfu email sent to anthoyfu117@hotmail.com

**Comment by userquin** [comment]
@antfu address not found

**Comment by userquin** [comment]
missing one n from the name?

**Comment by userquin** [comment]
sent to hi@antfu.me

**Comment by userquin** [comment]
Thx @antfu, I close this, I need to investigate and I feed back you when I have tried to fix inclusion of external resources bundle.

I'll try to do something similar to `rollap-plugin-gzip`  that allows to compress resources outside bundle: [Configuration](https://github.com/kryops/rollup-plugin-gzip#configuration) see **additionalFiles** entry.

**Comment by antfu** [comment]
That would be great, thanks!
