### ISSUE TITLE
[vite] Internal server error: Failed to resolve import "react-router-dom" from "src/App.tsx". Does the file exist?

### ISSUE THREAD

**Issue by liuchao99** [antfu/vite-plugin-pwa#70]
我确定包的存在,但是 yanr dev 时总会报错,即使更换vite的版本也是会报错的
![image](https://user-images.githubusercontent.com/56290517/120275545-0fe61100-c2e4-11eb-9bda-d3988cb6e1d1.png)

**Comment by Nahuelgrc** [comment]
I had the same issue and I could solve it

Basically I made a mistake and installed react-router using `npm install react-router`.

I uninstalled it and installed it back using `npm install react-router-dom@6`.

**Comment by bijoaja** [comment]
> 

how to uninstalled ?
