### ISSUE TITLE
browser always read all files from SerivceWorker

### ISSUE THREAD

**Issue by rainmanhhh** [antfu/vite-plugin-pwa#72]
I've rebuild the app and upload it to nginx, then run `nginx -s reload`
but browser read all files from ServiceWorker

**Comment by userquin** [comment]
@rainmanhhh what is the versión of the plugin? Do you migrate from older version?

**Comment by rainmanhhh** [comment]
> @rainmanhhh what is the version of the plugin? Do you migrate from older version?
> your app change some resource? If there are any resource changed works as expected.

just upgrade to latest version yesterday.
I modified some code and rebuild the app yesterday then upload it to server, but page is still the old version(in browser, android webview, and wechat miniprogram webview). then I tried refresh the browser manually, run `nginx -s reload` but still the same result(browser devtool shows index.html and all other resources are load from ServiceWorker).
then I tried to change the registerType from `autoUpdate` to `prompt` and rebuild the app. nothing changed.
then I rollback registerType to `autoUpdate` and rebuild the app. nothing changed.
but after about 20 mins, I check the page again and new files loaded.

**Comment by rainmanhhh** [comment]
btw, I have two apps in the same domain(but different folders)
similar to this [using-multiple-javascript-service-workers-at-the-same-domain-but-different-folde](https://stackoverflow.com/questions/42474908/using-multiple-javascript-service-workers-at-the-same-domain-but-different-folde)
maybe I need add some config to vue-plugin-pwa?

**Comment by userquin** [comment]
@rainmanhhh you need to change the scope option and/or the basePath for both using its name inside the root, for example, if /app1/ and /app2/ are the relative paths inside the root, then just configure basePath with /app1/ and /app2/ respectively.

**Comment by userquin** [comment]
@rainmanhhh if you have shared resources between both apps you cannot make work. The scope will act as a context.

**Comment by rainmanhhh** [comment]
so the developer should know final deploy absolute path, similar to 'browser history router' config? (I'm using 'hash router' in case of relative deploy path)

**Comment by userquin** [comment]
@rainmanhhh yes, this is a good example, the router

**Comment by rainmanhhh** [comment]
just checked the generated sw.js and I found it uses relative paths to access resources
Is it possible, in theory, to make the plugin auto detect 'base' by reading browser location.path? (since in hash router mode, location.path is always the index.html root)

**Comment by userquin** [comment]
This is done by `workbox` and the service worker should work. See https://github.com/antfu/vite-plugin-pwa/issues/23.

I close this issue, check if working, if not working add a repo where we can work to see the changes we need to add and I Will reopen this issue.
