### ISSUE TITLE
Cannot access static resource

### ISSUE THREAD

**Issue by ansidev** [antfu/vite-plugin-pwa#73]
Reproduce URL: https://vitesse.netlify.app/robots.txt

Expected: Raw content. A static resource can be plain text (like the above link or RSS URL), image, etc.
Actual: Vite page with `404 Not found` message.

**Comment by antfu** [comment]
Transferred to vite-plugin-pwa. The problem is the request been hijacked by service worker.

**Comment by userquin** [comment]
@antfu added PR to `vitesse` to solve missing sw manifest assets to work offline: https://github.com/antfu/vitesse/pull/139
