### ISSUE TITLE
Minified output

### ISSUE THREAD

**Issue by azamat-sharapov** [antfu/vite-plugin-pwa#8]
Service worker and Workbox javascript files are not minified. Is there any option I should add or is it missing this feature?

**Comment by antfu** [comment]
That's a good point, would you mind to create a PR for it? We use https://www.npmjs.com/package/rollup-plugin-workbox underhood and I guess there should be an option for that (we can make it default to minified and configurable for users to opt-out). Thanks

**Comment by azamat-sharapov** [comment]
It turns out `generateSW()` already minifies output, if `mode` options is set to `"production"`. The problem is when building, `tsup` [replaces `process.env` variables](https://github.com/egoist/tsup/blob/0b80615d053148ab907f41c402d09ec1eafc5e94/src/index.ts#L121), so `mode` option [always set to `"development"`](https://github.com/antfu/vite-plugin-pwa/blob/master/src/index.ts#L18). Quick fix for this is to pass `mode: process.env.NODE_ENV` via `workbox` option to `VitePWA`. Ideally though, `tsup` should not touch `process.env.NODE_ENV` piece.
