### ISSUE TITLE
Anyone with success implementing this in Vue2?

### ISSUE THREAD

**Issue by hubert17** [antfu/vite-plugin-pwa#81]
I fortunately was able to create a production build of my supposed to be NO cli-node-webpack Vue project using Vite courtesy of this guy: https://www.mathew-paul.nz/posts/how-to-use-vue2-with-vite/

The simple Vue/Vuetify app can be serve with or without build process.  
https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack 

I would like to turn this into PWA and I wonder if anyone here has success using vite-plugin-pwa with Vue 2. 

Thanks.

**Comment by userquin** [comment]
@hubert17 I haven't tested on vue2, but should work, I'll give a try on, I'll push changes to my fork once tested:

https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack

**Comment by hubert17** [comment]
@userquin You are awesome man. I'll keep watching the fork. :) 
https://github.com/userquin/GabsVuetifyNoCLINodeWebpack

**Comment by hubert17** [comment]
I don't match about Vue 3. I am stuck in here 
`import { useRegisterSW } from 'virtual:pwa-register/vue'` 

Says.. Failed to resolve import "vue" from "..\..\..\..\..\..\@vite-plugin-pwa\virtual:pwa-register\vue". Does the file exist? 

Here's my wild adventure: 
https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack/blob/pwa-vue/src/components/ReloadPrompt.js

**Comment by userquin** [comment]
> 
> 
> I don't match about Vue 3. I am stuck in here
> `import { useRegisterSW } from 'virtual:pwa-register/vue'`
> 
> Says.. Failed to resolve import "vue" from "............@vite-plugin-pwa\virtual:pwa-register\vue". Does the file exist?
> 
> Here's my wild adventure:
> https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack/blob/pwa-vue/src/components/ReloadPrompt.js

You haven't installed any dependency... I will simplify a little the app to only show the app, without any page...

Just compare with your branch: missing `vue`, `vuex`, `vue-router`, `vuetify` and `sass` stuff  from `dev dependencies`:

```json
// package.json
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "vite-plugin-vue2": "^1.6.2",
    "vue": "^2.6.14",
    "vue-router": "^3.5.1",
    "vuetify": "^2.5.4",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.2.3",
    "deepmerge": "^4.2.2",
    "sass": "^1.35.1",
    "sass-loader": "^12.1.0",
    "vite": "^2.3.7",
    "vite-plugin-pwa": "^0.8.1"
  }
}
```

About using `virtual:pwa-register/vue` right now it is not possible since its target is only for `vue3`, maybe we can take a look to use `vue-demi` allowing to be used also on `vue2`.

**Comment by userquin** [comment]
I will provide a mixin for `vue2` and maybe added to the docs...

**Comment by userquin** [comment]
seem to work, just adjusting some images to work offline...

**Comment by userquin** [comment]
Sorry for `template` before `script` in all `vue` files, this year I only work with `script setup with typescript` and is `more usable ;). 
I cannot use the oldest style.

If you test both `registerType` options, when switching between them, go to `chrome dev tools > Application > Storage` and clean data for `http://localhost:5000`. Once data cleared, go to `Application > Service workers` and check the actual is deleted (must appear with a gray dot and `is redundant` state).

Once you run first time, you need stop the server, do some change in same place, then `npm run build && npm run serve`.

For `registerType: autoUpdate`, second time you star the server, you will see the reload automatically, for `registerType: 'prompt'` the `reload prompt` will appear, you can navigate to see the change are not applied, and once click on refresh you will see the changes. 

You can also work with `autoUpdate` and `ReloadpPrompt` component, to show the `ready to work toast`. In that case you need to comment out the `router::isReady` callback on `src/router.js`, include the `ReloadPrompt` component on `src/App.vue` and configure `registerType: 'autoUpdate'` on `vite.config.js`.

You can also set offline the browser and check that works.

I have pushed the changes, working with `autoUpdate`, if you want make it working with `prompt`:
1) Uncomment from `src/App.vue` (also the `import` and the `components`):
```html
<!-- Include this component if you want to use `autoUpdate`: also add `onReady` callback on `src/router.js` -->
<reload-prompt />
```
2) Go to `src/router.js` and comment router callback: 
```js
/* 
comment these callback if you want to use `prompt`
*/
/*
router.onReady(async() => {
  const { registerSW } = await import("virtual:pwa-register")
  registerSW({ immediate: true })
})
*/
```
3) Go to `vite.config.js` and change `registerType` entry to `prompt` or just comment out/delete the option:
```js
    VitePWA({
      // for prompt comment out this option or just remove it, since it is the default behavior */
      registerType: 'prompt',
    ...
    ... 
```

You have a mixin for `virtual:pwa-register/vue` on `src/mixins/useRegisterSW.js`, you can see `src/components/ReloadPrompt.vue` how it is used:
```js
export default {
  name: "useRegisterSW",
  data: () => ({
    updateSW: undefined,
    offlineReady: false,
    needRefresh: false,
  }),
  async mounted() {
    const { registerSW } = await import("virtual:pwa-register")
    this.updateSW =  registerSW({
      immediate: true,
      onOfflineReady() {
        this.offlineReady = true;
        this.onOfflineReadyFn();
      } ,
      onNeedRefresh() {
        this.needRefresh = true;
        this.onNeedRefreshFn()
      },
    })
  },
  methods: {
    async closePrompt() {
      this.offlineReady = false;
      this.needRefresh = false;
    },
    onOfflineReadyFn() {
      console.log('onOfflineReady');
    },
    onNeedRefreshFn() {
      console.log('onNeedRefresh');
    },
    updateServiceWorker() {
      this.updateSW && this.updateSW(true)
    }
  }
}
```

![imagen](https://user-images.githubusercontent.com/6311119/122617065-e0792780-d08b-11eb-81cc-28c0873b5b0a.png)

**Comment by userquin** [comment]
I'll keep open this issue until tmr... so please, close it yourself if the sample on my fork works for you,

**Comment by hubert17** [comment]
Success! Thanks @userquin 
![image](https://user-images.githubusercontent.com/7923889/122624649-d844da80-d0d3-11eb-8ca2-7903857c249c.png) 
![image](https://user-images.githubusercontent.com/7923889/122624893-dc252c80-d0d4-11eb-9657-2f37e65ad571.png)

It's working even using CDN hosted packages. 
I have only installed devdependency packages.
It took me sometime to figure out how this done until I read this..
![image](https://user-images.githubusercontent.com/7923889/122625030-a3d21e00-d0d5-11eb-8dfb-bf676f576dd2.png)


I'm looking at this issue thu. Hope you can advise me on this.
![image](https://user-images.githubusercontent.com/7923889/122624758-48536080-d0d4-11eb-84e2-b965eb0d948a.png)

**Comment by hubert17** [comment]
It's here: 
https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack/tree/pwa-vue

**Comment by userquin** [comment]
I'll give a try, seems something missing...

**Comment by userquin** [comment]
Move the logic from the mixin to the `ReloadPrompt` component, it seems the mixin cannot be used in the way you create you components.

Also comment out the `onReady` callback on `src/router.js`.

And finally add this style to the class `.pwa-toast`: `background-color: white;` on `ReloadPrompt` component.

![imagen](https://user-images.githubusercontent.com/6311119/122626094-c732a400-d0a8-11eb-8e97-df254b34e0c4.png)

![imagen](https://user-images.githubusercontent.com/6311119/122626114-e03b5500-d0a8-11eb-946a-3ed7909cb66e.png)

**Comment by userquin** [comment]
```js
// import useRegisterSW from "../mixins/useRegisterSW";
import { css } from 'https://cdn.jsdelivr.net/npm/goober@2.0.33/dist/goober.modern.js';

const styles = css /*css*/ `
    .pwa-toast {
    position: fixed;
    right: 0;
    bottom: 0;
    margin: 16px;
    padding: 12px;
    border: 1px solid #8885;
    border-radius: 4px;
    z-index: 1;
    text-align: left;
    box-shadow: 3px 4px 5px 0px #8885;
    background-color: white; 
    }
    .pwa-toast .message {
    margin-bottom: 8px;
    }
    .pwa-toast button {
    border: 1px solid #8885;
    outline: none;
    margin-right: 5px;
    border-radius: 2px;
    padding: 3px 10px;
    }

`

export default {
    name: "ReloadPrompt",

    data() {
        return {
            updateSW: undefined,
            offlineReady: false,
            needRefresh: false,
        }
    },
    async mounted() {
        const { registerSW } = await import("virtual:pwa-register")
        const vm = this;
        this.updateSW =  registerSW({
            immediate: true,
            onOfflineReady() {
                vm.offlineReady = true;
                vm.onOfflineReadyFn();
            } ,
            onNeedRefresh() {
                vm.needRefresh = true;
                vm.onNeedRefreshFn()
            },
        })
    },
    methods: {
        async closePrompt() {
            this.offlineReady = false;
            this.needRefresh = false;
        },
        onOfflineReadyFn() {
            console.log('onOfflineReady');
        },
        onNeedRefreshFn() {
            console.log('onNeedRefresh');
        },
        updateServiceWorker() {
            this.updateSW && this.updateSW(true)
        }
    },

    template: /*html*/ `

<div class=${styles}>
    <div
      v-if="offlineReady || needRefresh"
      class="pwa-toast"
      role="alert"
  >
    <div class="message">
      <span v-if="offlineReady">
        App ready to work offline
      </span>
      <span v-else>
        New content available, click on reload button to update.
      </span>
    </div>
    <button v-if="needRefresh" @click="updateServiceWorker">
      Reload
    </button>
    <button @click="closePrompt">
      Close
    </button>
  </div>
</div>


    `,
  };
```

**Comment by userquin** [comment]
WTF: Do not change anything, just remove the empty `data` method on your `ReloadPrompt` component!!!!

**Comment by userquin** [comment]
```js
export default {
    name: "ReloadPrompt",
    mixins: [useRegisterSW],

/* WHAT ARE YOU DOING HERE?
    data() {

    },
*/
    template: /*html*/ `
```

**Comment by userquin** [comment]
close the issue when tested please.

**Comment by hubert17** [comment]
**Working great now in Vue2!** 
https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack/tree/pwa-vue

_...at least when hosted in root. However in Github Pages, I ended up with problem on base/paths._ 
But that would be for another issue. Thank you again @userquin . Closing this now.
