### ISSUE TITLE
Problem with path in non-root hosting like Github Pages

### ISSUE THREAD

**Issue by hubert17** [antfu/vite-plugin-pwa#82]
When hosted in non-root path, the Manifest and other vite-plugin-pwa are not loaded as it is pointing to a wrong location. 
![image](https://user-images.githubusercontent.com/7923889/122655298-d9354500-d183-11eb-8139-999e3aa2e8e5.png) 

I have tried configuring the vite config 
![image](https://user-images.githubusercontent.com/7923889/122655383-8314d180-d184-11eb-972a-891d37762f71.png)
but still having the preceding slash 
![image](https://user-images.githubusercontent.com/7923889/122655418-ae97bc00-d184-11eb-945b-861269115ade.png)

**Comment by userquin** [comment]
@hubert17  where is the hosted url?

**Comment by hubert17** [comment]
@userquin https://hubert17.github.io/GabsVuetifyNoCLINodeWebpack

**Comment by userquin** [comment]
@hubert17 

You need to remove the `/` from manifest icons and `includeAssets` on `vite.config.js`:

Just lookup `// <== here` below:
```ts
VitePWA({
            base: '',
            // for prompt comment the option or just remove this option, since it is the default behavior */
            registerType: 'prompt',
            includeAssets: ['favicon.svg'], // <== here
            manifest: {
              name: 'Gabs Vue App PWA',
              short_name: 'Gabs Vue',
              description: 'Gabs Vue App + Vite + Vite PWA ',
              theme_color: '#ffffff',
              icons: [
                {
                  src: 'pwa-192x192.png', // <== here
                  sizes: '192x192',
                  type: 'image/png',
                },
                {
                  src: 'pwa-512x512.png', // <== here
                  sizes: '512x512',
                  type: 'image/png',
                },
                {
                  src: 'pwa-512x512.png', // <== here
                  sizes: '512x512',
                  type: 'image/png',
                  purpose: 'any maskable',
                },
              ],
            }
          })
```

**Comment by hubert17** [comment]
Done with <==here stuff. :) 

I emptied the base for both Vite and Vite-pwa config. But still the manifest link is being preceded with /. My recommendation is for it to behave just like the base in Vite. Where empty string is really empty string. In Vite-pwa, assiging empty string defaults base to "/". 

![image](https://user-images.githubusercontent.com/7923889/122656309-ef470380-d18b-11eb-8207-223ba35134c4.png)

![image](https://user-images.githubusercontent.com/7923889/122656287-a8590e00-d18b-11eb-8e07-a07e83ab8afe.png)

**Comment by userquin** [comment]
you were looking the page before the reload button clicked:

![imagen](https://user-images.githubusercontent.com/6311119/122656655-e985f980-d15c-11eb-9af7-78b055811205.png)

**Comment by userquin** [comment]
where is the base entry? I cannot find it.

**Comment by userquin** [comment]
right now it seems to be working ok, no errors: on network tab, sw and manifest.webmanifest

**Comment by hubert17** [comment]
@userquin 
I've added this workaround.. 
![image](https://user-images.githubusercontent.com/7923889/122656902-6e8b0600-d191-11eb-9c2c-66492f671815.png)

I hope it this would be fixed. 

> I emptied the base for both Vite and Vite-pwa config. But still the manifest link is being preceded with /. My recommendation is for it to behave just like the base in Vite. Where empty string is really empty string. In Vite-pwa, assiging empty string defaults base to "/".

![image](https://user-images.githubusercontent.com/7923889/122656962-d7727e00-d191-11eb-850f-4521b1c8dbca.png)

**Comment by userquin** [comment]
Add this below `manifest` entry on `vite.config.js`:
```js
      workbox: {
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/cdn\.jsdelivr\.net\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'jsdelivr-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
        ],
      }
```

**Comment by userquin** [comment]
You also need to add to `index.html` `crossorigin="anonymous"` to exteranl links and scripts:
```html
    <link crossorigin="anonymous" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet" />
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet" />
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet" />

    <title>Hello Vue World!</title>
    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/vue-router@3.x/dist/vue-router.js"></script>
    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/vuex@3.x/dist/vuex.js"></script>
    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/axios@0.x/dist/axios.min.js"></script>
```

**Comment by userquin** [comment]
This will make you pwa work offline.

**Comment by userquin** [comment]
I forget to include `fonts.gstatic.com`:
``js
      workbox: {
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/cdn\.jsdelivr\.net\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'jsdelivr-cache',
              expiration: {
                maxEntries: 10, // <== for testing
                maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: {
                maxEntries: 10, // <== for testing
                maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: {
                maxEntries: 10, // <== for testing
                maxAgeSeconds: 60 * 60 * 24 * 365, // <== 365 days
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
        ],
```

**Comment by userquin** [comment]
This will not be fixed, since you are using it in a wrong way.

All server backends have a document root or a default context.

This will work on any server, also on development:

```js
// src/router.js
const router = new VueRouter({
  base: '/GabsVuetifyNoCLINodeWebpack/',
  mode: 'history', // real path
  routes, // short for `routes: routes`
});
```
```js
// vite.config.js
...
  base: '/GabsVuetifyNoCLINodeWebpack/',
  plugins: [
    createVuePlugin(),
    VitePWA({
      // for prompt comment the option or just remove this option, since it is the default behavior */
      base: '/GabsVuetifyNoCLINodeWebpack/',
      registerType: 'prompt',
      includeAssets: ['favicon.svg'],
      manifest: {
        name: 'PWA Vue2',
        short_name: 'PWA Vue2',
        description: 'Vite PWA + Vue2 + Vite',
        theme_color: '#ffffff',
        start_url: '/GabsVuetifyNoCLINodeWebpack/',
        icons: [
...
```

**Comment by hubert17** [comment]
I need to do this 
![image](https://user-images.githubusercontent.com/7923889/122658400-59b56f00-d19f-11eb-8d44-d3333c210c28.png)
So that  "/" (home route) in Vue will point to "/GabsVuetifyNoCLINodeWebpack/". 
Again this became an issue because I am hosting in github.io subdirectory.

This **preceding slash in manifest's href** is the only remaining issue that I have.  If only we could have the option to set that to pure empty string (instead of defaulting it to / when base is ""), that would solve the last issue that I have. :D 

But other than that everything is working great! I lovue, vite, and you guys in vite-pwa!!! 

Here: https://github.com/hubert17/GabsVuetifyNoCLINodeWebpack 
PWA site: https://hubert17.github.io/GabsVuetifyNoCLINodeWebpack/
