### ISSUE TITLE
add background-sync

### ISSUE THREAD

**Issue by chavda-bhavik** [antfu/vite-plugin-pwa#86]
I'm trying to add background sync to the service worker, but couldn't able to find any way to add it. 
Is there any way to include our own code in the service worker or does anyone know how to add background sync with this plugin?

Any help will be highly appreciated.

**Comment by chavda-bhavik** [comment]
By following this [link](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync#basic_usage) from workbox documentation, I think I have to register a new route to the service worker.

```
import {BackgroundSyncPlugin} from 'workbox-background-sync';
import {registerRoute} from 'workbox-routing';
import {NetworkOnly} from 'workbox-strategies';

const bgSyncPlugin = new BackgroundSyncPlugin('myQueueName', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

registerRoute(
  /\/api\/.*\/*.json/,
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);
```

**Comment by userquin** [comment]
@chavda-bhavik you can write your own service worker or you can check `generateWS` workbox docs entry and see if you can do it with some plugin (if there is no background sync plugin, then you must create your own, see `injectManfest` on docs).

You can use [BackgroundSyncPlugin](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-background-sync.BackgroundSyncPlugin).

Read the docs on workbox, and then add it to the `workbox` entry on `VitePWA` configuration: you can see some example [here](https://github.com/antfu/vite-plugin-pwa/issues/82#issuecomment-864474068) how to configure a plugin.

**Comment by userquin** [comment]
@chavda-bhavik it can be done!!! inside the `tuntimeCaching` you can configure the entry `backgroundSync`: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry

**Comment by userquin** [comment]
```ts
// vite.config.ts
VitePWA({
  /* manifest and other options */
  runtimeCaching: {
    handler: 'NetworkOnly',
    urlPattern: /\/api\/.*\/*.json/,
    method: 'POST',
    options: {
      backgroundSync: {
        name: 'myQueueName',
        options: {
          maxRetentionTime: 24 * 60
        }
      }
    }
  }
})
```

**Comment by chavda-bhavik** [comment]
Thank you for your help @userquin. I think this is all that I need to implement, will go through workbox docs for further implementation and testing and will close this as soon as I will be able to implement it. Thank you again for your help and reference.

**Comment by chavda-bhavik** [comment]
Your solution worked @userquin, thanks. I was able to implement it. Can you say where can I see for further `workbox` and `manifest` configuration in this plugin, like the below schema?

```
VitePWA({
    /* manifest and other options */,
   workbox: {
     runtimeCaching: [{
        handler: 'NetworkOnly',
        urlPattern: /\/api\/.*\/*.json/,
        method: 'POST',
        options: {
          backgroundSync: {
            name: 'myQueueName',
            options: {
              maxRetentionTime: 24 * 60
            }
          }
        }
      }]
   }
})
```

**Comment by userquin** [comment]
In this plugin there is no such examples, since we just delegate to `generateWS` on the virtual module.

It is out of the scope of this repo, just go to workbox site, there are examples there.

I hint some ppl to include some plugins for external resources and so the app work offline:

https://github.com/antfu/vite-plugin-pwa/issues/82#issuecomment-864474068

Beware, you need to include crossorigin with anonymous such external resources:

https://github.com/antfu/vite-plugin-pwa/issues/82#issuecomment-864473838

**Comment by chavda-bhavik** [comment]
thanks @userquin. closing this.
