### ISSUE TITLE
docs(wip): new docs site available at https://vite-plugin-pwa.netlify.app/

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-pwa#88]
@antfu to keep track, I'll add to docs some hints and maybe a New example using some plugins using `generateWS` and `injectManifest` strategies.

**Comment by userquin** [comment]
/cc @antfu 

https://github.com/antfu/vite-plugin-pwa/issues/95#issuecomment-890187104

https://github.com/antfu/vite-plugin-pwa/issues/95#issuecomment-890218046

**Comment by BroJenuel** [comment]
Documentation for vite-plugin-pwa would be awesome.

**Comment by userquin** [comment]
Almost everything on the readme integrated on new docs, also added:

- vanilla js, typescript, vue2, vue3 and vitepress integration
- included deployment for: apache http server 2.4 and netlify, WIP for AWS Amplify and Vercel.
- workbox: WIP

**Comment by userquin** [comment]
Add other framework samples on new docs: #96

**Comment by userquin** [comment]
We have the new docs app on netlify (it's a pwa, it couldn't be otherwise ;) ): https://vite-plugin-pwa.netlify.app/

We need feedback from the community: PR are welcome.

Pending entries:
- deployment: AWS/AWS Amplify and Vercel
- frameworks: react and svelte

**Comment by BroJenuel** [comment]
wow awesome,, I really like the docs,, and the Logo is so coooooooooooooolll!!! Nicely done.

**Comment by userquin** [comment]
> 
> 
> wow awesome,, I really like the docs,, and the Logo is so coooooooooooooolll!!! Nicely done.

cortesy of @antfu I also love it

**Comment by userquin** [comment]
@MartinMalinda @scambier @armenr @husayt your feedback are welcome

**Comment by userquin** [comment]
Included `Svelte` entry: it should work with `Svelte`, but using `SvelteKit` you should use its own `service worker module`.

**Comment by scambier** [comment]
I've read most of the docs, it's really clear. Well done!

**Comment by userquin** [comment]
> 
> 
> I've read most of the docs, it's really clear. Well done!

Thx Simon

**Comment by userquin** [comment]
@scambier You have included in new `0.9.3` the logic to auto check for updates, remember #33: https://vite-plugin-pwa.netlify.app/guide/periodic-sw-updates.html

**Comment by scambier** [comment]
I'll update as soon as I'm working again on my project (presumably in a month or two...) 👍

**Comment by armenr** [comment]
@userquin - I will get to work on Amplify docs!

**Comment by userquin** [comment]
New `0.10.0` version released with svelte and react virtual modules and 4 examples projects with basic and router.

I Will also update the docs site today.

**Comment by husayt** [comment]
@userquin my only feedback is that I am so impressed, from readme to proper website with detailed docs overnight! This is great. I found all the information useful.

Thanks

**Comment by userquin** [comment]
First review done, includes following changes:

- Frameworks:
  - Vite: includes custom vite virtual modules references
  - Svelte: modified to use `svelte` virtual module
  - React: included using `react` virtual module

- Examples: new entry
  - Vue 3
  - React
  - Svelte
  - Vitepress

- Deployment:
  - Added entry `Testing your application on production`
  - Included `NGINX` configuration
  - Include configuration file name for `Apache`

**Comment by userquin** [comment]
@antfu List of pending things:
- review 2: work in progress (@userquin: review some wording + change some items order)
- add `injectManifest` example for `svelte` and reference in docs: work in progress (@userquin)
- add `injectManifest` example for `react` and reference in docs: work in progress (@userquin)
- fix edit page: seems we need to add somehting to the codebase and/or github
- add algolia search to docs site?
- Vercel
- AWS (@armenr)

**Comment by userquin** [comment]
I forgot to add publish a `tweet` (patak says me `vite_js` will retweet it) 😅

**Comment by userquin** [comment]
Second review done, includes following changes (see PR #110):
- review 2: some entries modified, see commits
- add injectManifest example for svelte and reference in docs
- add injectManifest example for react and reference in docs

**Comment by dheimoz** [comment]
great work as always @userquin !!!!!!

**Comment by userquin** [comment]
@armenr any progress on the AWS docs? I guess you will be on vacation (or very busy) ;)

**Comment by armenr** [comment]
@userquin - I have actually prepared an AWESOME example boilerplate, I will update with that in the next day or two...I got sidetracked while fixing one of JavaScript's + Vue's most ANNOYING and COMMON problems (formatting + linting + VSCode). 

All the code (including the best possible linting setup) will be shared soon :)

**Comment by antfu** [comment]
Close as we have moved the readme to the new docs.
