### ISSUE TITLE
workbox-window not installed by pnpm

### ISSUE THREAD

**Issue by h-guliyev** [antfu/vite-plugin-pwa#89]
I had an issue below where it could not find `workbox-window` during build. had to install `workbox-window` directly and that solved it. Seems it is not properly picking it up from peer-dependencies.

```bash
vite v2.4.1 building for production...
transforming...
✓ 30 modules transformed.
[vite-plugin-pwa] [vite]: Rollup failed to resolve import "workbox-window" from "..\..\..\..\..\..\@vite-plugin-pwa\virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "workbox-window" from "..\..\..\..\..\..\@vite-plugin-pwa\virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (C:\myui\node_modules\.pnpm\vite@2.4.1\node_modules\vite\dist\node\chunks\dep-cc49d7be.js:51142:19)
    at onwarn (C:\myui\node_modules\.pnpm\vite@2.4.1\node_modules\vite\dist\node\chunks\dep-cc49d7be.js:50932:13)
    at Object.onwarn (C:\myui\node_modules\.pnpm\rollup@2.52.7\node_modules\rollup\dist\shared\rollup.js:20334:13)
    at ModuleLoader.handleResolveId (C:\myui\node_modules\.pnpm\rollup@2.52.7\node_modules\rollup\dist\shared\rollup.js:19689:26)
    at C:\myui\node_modules\.pnpm\rollup@2.52.7\node_modules\rollup\dist\shared\rollup.js:19636:22
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (C:\myui\node_modules\.pnpm\rollup@2.52.7\node_modules\rollup\dist\shared\rollup.js:19634:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (C:\myui\node_modules\.pnpm\rollup@2.52.7\node_modules\rollup\dist\shared\rollup.js:19610:9)
    at async C:\myui\node_modules\.pnpm\rollup@2.52.7\node_modules\rollup\dist\shared\rollup.js:19583:48
 ERROR  Command failed with exit code 1.
 ```

**Comment by userquin** [comment]
@h-guliyev provide a small repro or provide some more info, like: framework (vue, react...), `vite` configuration file (at least pwa plugin options)...

**Comment by kmilogp8496** [comment]
Hi, I'm having this issue, but only when building inside a docker image. Local it does not happen. Thanks

**Comment by kmilogp8496** [comment]
Solved by adding `workbox-window` to devDependencies

**Comment by husayt** [comment]
İ have done the same

**Comment by userquin** [comment]
@husayt @kmilogp8496 could provide at least this info and your `vite.config.ts` file?:
```shell
npx envinfo --npmPackages vite,@vitejs/plugin-vue,vite-plugin-pwa --binaries --browsers
```

**Comment by husayt** [comment]
Yes, sure. I don't think its vite config related, more like pnpm. as it can't find `workbox-window` and it has to be manually added

```
Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @vitejs/plugin-vue: ^1.2.4 => 1.2.4 
    vite: ^2.4.1 => 2.4.1 
    vite-plugin-pwa: ^0.8.1 => 0.8.1 
    ```

**Comment by userquin** [comment]
@husayt the only difference I see is that I use node 15 and npm 7. Can you include the typescript configuration (`tsconfig.json`) here?
```shell
npx envinfo --npmPackages vite,@vitejs/plugin-vue,vite-plugin-pwa --binaries --browsers

  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.164
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.71)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @vitejs/plugin-vue: ^1.2.5 => 1.2.5
    vite: ^2.4.2 => 2.4.2
    vite-plugin-pwa: ^0.8.1 => 0.8.1
```

**Comment by husayt** [comment]
```ts
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "ESNext",
    "target": "es2016",
    "lib": ["DOM", "ESNext"],
    "strict": true,
    "esModuleInterop": true,
    "incremental": false,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "allowJs": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "types": [
      "vite/client"
    ],
    "paths": {
      "~/*": ["src/*"]
    }
  },
  "exclude": ["dist", "node_modules"]
}

```

**Comment by userquin** [comment]
@husayt I'll try to fix including `workbox-window` and `workbox-build` as `peer` dependencies.

**Comment by userquin** [comment]
@husayt @kmilogp8496  can you test with `0.8.2` version? Wait a few minutes, released right now...

**Comment by husayt** [comment]
@userquin it looks like working now. I will keep my eye on it. Thanks

**Comment by kmilogp8496** [comment]
npx envinfo --npmPackages vite,@vitejs/plugin-vue,vite-plugin-pwa --binaries --browsers
Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^1.2.4 => 1.2.4 
    vite: ^2.4.1 => 2.4.3 
    vite-plugin-pwa: ^0.8.2 => 0.8.2

**Comment by kmilogp8496** [comment]
```
tsconfig.json

{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "ESNext",
    "target": "es2016",
    "lib": ["DOM", "ESNext"],
    "strict": true,
    "esModuleInterop": true,
    "incremental": false,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "types": [
      "vite/client",
      "vite-plugin-pages/client",
      "vite-plugin-vue-layouts/client"
    ],
    "paths": {
      "~/*": ["src/*"]
    }
  },
  "exclude": ["dist", "node_modules"]
}

```

**Comment by kmilogp8496** [comment]
Hi guys, thank you for your quick response

Upgraded package to version 0.8.2 and still getting the same error

```
[vite-plugin-pwa] [vite]: Rollup failed to resolve import "workbox-window" from "../@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "workbox-window" from "../@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
```

I'm using docker, this is my Dockerfile

```
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN npm install -g pnpm


RUN pnpm install
COPY ./ .
RUN pnpm build
```

**Comment by husayt** [comment]
Try to remove your lock file and install again. For me that fixed it

**Comment by kmilogp8496** [comment]
> Try to remove your lock file and install again. For me that fixed it

This did not work, thank you for your help, I'll add it to the package.json for now.

**Comment by zynth17** [comment]
got the same problem and ended up installing workbox-window manually

**Comment by r-moore** [comment]
still seems to be a problem

**Comment by userquin** [comment]
@r-moore we are not able to fix this, so we suggest you to install it as dev dependency...

**Comment by arackaf** [comment]
Just chiming in here. I don't think this is a bug with vite-plugin-pwa. I got bitten by this. Deleting the package-lock.json, deleting node_modules and then running a fresh install causes workbox-window to get pulled in.

**Comment by armenr** [comment]
I just got hit by the same thing.

This seems to fix the problem in a repeatable and reliable way (both in my CI pipeline, as well as my local environment):

`shamefully-hoist=true`

:)

**Comment by HazyFish** [comment]
This issue still exists with `pnpm` both locally and on GitHub Actions 

```
[vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "workbox-window" from "../../../../../@vite-plugin-pwa/virtual:pwa-register/react".
```

```
+ vite 3.1.0
+ vite-plugin-pwa 0.12.6
```

**Comment by lanseria** [comment]
set `.npmrc` for pnpm
```
shamefully-hoist=true
strict-peer-dependencies=false
```

**Comment by fberger-cs** [comment]
still have this problem with netlify pipeline. Workarounds above don't work for me

**Comment by userquin** [comment]
@fberger-cs try also adding `auto-install-peers=true`

**Comment by fberger-cs** [comment]
Hi @userquin, thanks for your suggestion but it still doesn't work see netlify logs below:

> 7:59:15 PM:   1. build.command from netlify.toml
7:59:15 PM: ────────────────────────────────────────────────────────────────
7:59:15 PM: ​
7:59:15 PM: $ pnpm run build
7:59:16 PM: > @0.0.34 build /opt/build/repo
7:59:16 PM: > vite-ssg build
7:59:17 PM: [vite-ssg] Build for client...
7:59:17 PM: vite v3.2.5 building for production...
7:59:17 PM: transforming...
7:59:19 PM: ✓ 122 modules transformed.
7:59:19 PM: rendering chunks...
7:59:19 PM: (node:4843) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
7:59:19 PM: (Use `node --trace-warnings ...` to show where the warning was created)
7:59:20 PM: dist/assets/8.c5a68910.svg                                                   6.58 KiB
7:59:20 PM: dist/index.html                                                              1.77 KiB
7:59:20 PM: dist/manifest.webmanifest                                                    0.38 KiB
[some logs...]
7:59:20 PM: dist/assets/virtual_pwa-register.c7843bc1.js                                 0.60 KiB / gzip: 0.41 KiB
7:59:20 PM: dist/assets/app.735420f8.js                                                  174.46 KiB / gzip: 63.24 KiB
7:59:20 PM: [vite-ssg] An internal error occurred.
7:59:20 PM: [vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
7:59:20 PM: file:///opt/build/repo/node_modules/.pnpm/vite-plugin-pwa@0.13.3_x7bmrdf5vv7jofix4vzvx6ucm4/node_modules/vite-plugin-pwa/dist/index.mjs:6
7:59:20 PM:   throw new Error('Dynamic require of "' + x + '" is not supported');
7:59:20 PM:         ^
7:59:20 PM: Error: Dynamic require of "workbox-build" is not supported
7:59:20 PM:     at file:///opt/build/repo/node_modules/.pnpm/vite-plugin-pwa@0.13.3_x7bmrdf5vv7jofix4vzvx6ucm4/node_modules/vite-plugin-pwa/dist/index.mjs:6:9
7:59:20 PM:     at loadWorkboxBuild (file:///opt/build/repo/node_modules/.pnpm/vite-plugin-pwa@0.13.3_x7bmrdf5vv7jofix4vzvx6ucm4/node_modules/vite-plugin-pwa/dist/index.mjs:257:12)
7:59:20 PM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
7:59:20 PM:     at async generateServiceWorker (file:///opt/build/repo/node_modules/.pnpm/vite-plugin-pwa@0.13.3_x7bmrdf5vv7jofix4vzvx6ucm4/node_modules/vite-plugin-pwa/dist/index.mjs:299:26)
7:59:20 PM:     at async _generateSW (file:///opt/build/repo/node_modules/.pnpm/vite-plugin-pwa@0.13.3_x7bmrdf5vv7jofix4vzvx6ucm4/node_modules/vite-plugin-pwa/dist/index.mjs:468:5)
7:59:20 PM:     at async Object.handler (file:///opt/build/repo/node_modules/.pnpm/vite-plugin-pwa@0.13.3_x7bmrdf5vv7jofix4vzvx6ucm4/node_modules/vite-plugin-pwa/dist/index.mjs:597:11)
7:59:20 PM:     at async PluginDriver.hookParallel (file:///opt/build/repo/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22670:17)
7:59:20 PM:     at async Object.close (file:///opt/build/repo/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23750:13)
7:59:20 PM:     at async Promise.all (index 0)
7:59:20 PM:     at async build (file:///opt/build/repo/node_modules/.pnpm/vite@3.2.5_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45548:13)
7:59:20 PM:     at async build (file:///opt/build/repo/node_modules/.pnpm/vite-ssg@0.21.2_kaif6y5mbm4jgos2hjpiokpkim/node_modules/vite-ssg/dist/shared/vite-ssg.4a3d00bb.mjs:956:3)
7:59:20 PM:     at async Object.handler (file:///opt/build/repo/node_modules/.pnpm/vite-ssg@0.21.2_kaif6y5mbm4jgos2hjpiokpkim/node_modules/vite-ssg/dist/node/cli.mjs:29:5) {
7:59:20 PM:   code: 'PLUGIN_ERROR',
7:59:21 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
7:59:20 PM:   plugin: 'vite-plugin-pwa:build',
7:59:20 PM:   hook: 'closeBundle'
7:59:20 PM: }
7:59:20 PM: Node.js v18.8.0
7:59:20 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
7:59:20 PM: ​
7:59:20 PM:   "build.command" failed                                        
7:59:20 PM: ────────────────────────────────────────────────────────────────
7:59:20 PM: ​
7:59:20 PM:   Error message
7:59:20 PM:   Command failed with exit code 1: pnpm run build (https://ntl.fyi/exit-code-1)
7:59:20 PM: ​
7:59:20 PM:   Error location
7:59:20 PM:   In build.command from netlify.toml:
7:59:20 PM:   pnpm run build

**Comment by userquin** [comment]
@fberger-cs is build working on your local? can you provide a minimal repro?

**Comment by fberger-cs** [comment]
build is fine locally:

> build is fine locally:

> ➜  git:(main) node -v   
v18.8.0
➜  git:(main) pnpm run build
@0.0.34 build /Users/...
vite-ssg build
[vite-ssg] Build for client...
vite v3.2.5 building for production...
✓ 122 modules transformed.
rendering chunks (5)...(node:18983) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
dist/assets/8.c5a68910.svg                                                   6.58 KiB
dist/index.html                                                              1.77 KiB
dist/manifest.webmanifest                                                    0.38 KiB
dist/ssr-manifest.json                                                       8.71 KiB
dist/assets/virtual_pwa-register.22f350d7.js                                 0.60 KiB / gzip: 0.41 KiB
dist/assets/404.89660149.js                                                  0.49 KiB / gzip: 0.35 KiB
[...]
dist/assets/workbox-window.prod.es5.6954f450.js                              5.17 KiB / gzip: 2.15 KiB
dist/assets/privacy.1892fa5d.css                                             0.44 KiB / gzip: 0.23 KiB
dist/assets/index.8a7454af.css                                               19.44 KiB / gzip: 4.76 KiB
dist/assets/terms.9f790a91.js                                                29.29 KiB / gzip: 10.16 KiB
dist/assets/privacy.57d359f3.js                                              28.89 KiB / gzip: 9.12 KiB
dist/assets/app.87d79505.js                                                  174.46 KiB / gzip: 63.25 KiB
PWA v0.13.3
mode      generateSW
precache  19 entries (274.06 KiB)
files generated
  dist/sw.js
  dist/workbox-30e9d199.js
[vite-ssg] Build for server...
vite v3.2.5 building SSR bundle for production...
✓ 84 modules transformed.
.vite-ssg-temp/manifest.webmanifest                         0.38 KiB
.vite-ssg-temp/main.mjs                                     100.28 KiB
.vite-ssg-temp/assets/virtual_pwa-register.82e0e621.js      1.09 KiB
[...]
.vite-ssg-temp/assets/privacy.e15345e1.js                   136.78 KiB
.vite-ssg-temp/assets/FAQ.6f0ea5e3.js                       21.53 KiB
.vite-ssg-temp/assets/workbox-window.prod.es5.6954f450.js   7.43 KiB
.vite-ssg-temp/assets/style.bc24cd7c.css                    25.26 KiB
[vite-ssg] Rendering Pages... (6)
[vite-ssg] Critical CSS generation enabled via `critters`
dist/index.html       22.64 KiB
dist/.html            22.64 KiB
[...]
dist/privacy.html     44.12 KiB
dist/faq.html         16.04 KiB
[vite-ssg] Regenerate PWA...
PWA v0.13.3
mode      generateSW
precache  23 entries (418.08 KiB)
files generated
  dist/sw.js
  dist/workbox-30e9d199.js


sry the repo must stay private so I will dior a bit more

**Comment by userquin** [comment]
@fberger-cs I only need a minimal reproduction with the error on local, if it is only failing when deploying, check lock file has been updated once you have run `pnpm install` when changing `.npmrc` (or just try removing `node_modules` and lock file and installing again dependendencies, don't forget to update lock file).

**Comment by fberger-cs** [comment]
just found a solution: seems like it has nothing to do with my code but it is something related to the build settings of the netlify pipeline

What I did:
1. in netlify > my project > build & deploy > build settings > build command:
- changed it from 'npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build' to 'npm run build'
2. then inside my code
- rm -rf pnpm-lock.yaml node_modules
- nvm use 18.8.0 && npm i
- pushed to git so that it triggers a netlify build
and netlify build worked just fine

I guess netlify is doing some bad caching that I could not fix even with their tooltip option 'clear cache and retry with latest commit branch'

anyway thx @userquin

**Comment by userquin** [comment]
@fberger-cs pnpm should work without the cache, IIRC, it was fixed a few months ago, check vitesse toml file: https://github.com/antfu/vitesse/blob/main/netlify.toml#L6

**Comment by segevfiner** [comment]
So probably the correct thing is adding to `.npmrc`:
```
public-hoist-pattern[]=workbox-window
```
