### ISSUE TITLE
Generic client

### ISSUE THREAD

**Issue by ghostdevv** [antfu/vite-plugin-pwa#96]
There is a way to create a [pop up for vue](https://github.com/antfu/vite-plugin-pwa/blob/master/examples/vue-basic/src/ReloadPrompt.vue) but none for people who don't use vue, for example Svelte users

**Comment by userquin** [comment]
@ghostdevv see this comment https://github.com/antfu/vite-plugin-pwa/issues/65#issuecomment-845202658

**Comment by ghostdevv** [comment]
@userquin I don't use Svelte Kit, I use [Routify](https://routify.dev)

**Comment by userquin** [comment]
You have the component there inside components folder  just use it as a guide.

**Comment by ghostdevv** [comment]
@userquin there would be significantly less boilerplate if this vite plugin offered a generic solution, if generic isn't possible then a svelte and react alternatives

**Comment by userquin** [comment]
@ghostdevv I'm finishing the new docs, you can view the new docs package, and for framework just go to docs/frmawoework directory, PR are welcome. I have included vue (vue 2 and 3 exmaples) and vitepress.

**Comment by ghostdevv** [comment]
How does this relate to generic/framework specific clients? A little confused :sweat_smile:

**Comment by userquin** [comment]
@ghostdevv This repo will not include any ui component framework, the new docs will just include some minimal ui snippet so ppl can use it as a guide: we'll include main frameworks without any ui framwork, and so we will have vue, svelte and react.

See this page markdown file: https://github.com/antfu/vite-plugin-pwa/blob/master/docs/frameworks/vue.md

There will be one for each framework with the snippet mentioned above.

**Comment by ghostdevv** [comment]
Sounds good

**Comment by userquin** [comment]
@ghostdevv Can you provide a repowith a minimal repro where I can play with svelte and Routify?

**Comment by userquin** [comment]
@ghostdevv I close this issue, added hint on #88

**Comment by userquin** [comment]
@ghostdevv see https://vite-plugin-pwa.netlify.app/frameworks/svelte.html#using-svelte

![imagen](https://user-images.githubusercontent.com/6311119/128554468-c6b7016d-fe47-434b-a8d3-c6f0070f3861.png)

Once clicked on reload button 

![imagen](https://user-images.githubusercontent.com/6311119/128554526-e568da47-d539-4585-a5cb-e8fdc56d8d33.png)

**Comment by userquin** [comment]
@ghostdevv I'm working for integrating also `svelte`: `Svelte Kit` will not be supported since it has its own `service worker` module.

I also include some working examples on the examples package: using svelte and `Routify`.

There will be a basic and a router example similar to vue examples.

**Comment by ghostdevv** [comment]
I'll take a look soon, thank you @userquin

**Comment by userquin** [comment]
@ghostdevv see this https://github.com/userquin/vite-plugin-pwa/tree/feat/add-svelte, you can view `svelte-basic` and `svelte-routify` in examples directory. Maybe tmr will be merged here, I need to talk with antfu...

**Comment by ghostdevv** [comment]
That's amazing, thank you so much!

**Comment by userquin** [comment]
@ghostdevv virtual module for svelte and for react included on `0.10.0` versión. There are also 4 New examples 2 for svelte and 2 for react.

I Will also update the docs site...

**Comment by userquin** [comment]
@ghostdevv docs ready for svelte and react

**Comment by ghostdevv** [comment]
Awesome ty
